In [ ]:
import pandas as pd

file_id = "1QGFb8PLgP-1i0eTTGu0n-F7B5mSKmQSS"
url = f"https://drive.google.com/uc?id={file_id}"

df = pd.read_csv(url)

print(df.shape)
df.head()

(16993, 29)

,ID,ID_Entidad,Operacion,Tipo_Propiedad,Titulo,Descripcion,Fecha_Publicacion,Antiguedad,Apto_Credito,Amenities,...,Superficie_Total_m2,Superficie_Cubierta_m2,Direccion,Barrio,Ubicacion,Latitud,Longitud,Estado,ID_Interno,Link
0,639768,dc889455-70ed-4d9f-b046-7bb7b5d97a4e,sale,departamento_estandar,Venta Depto 2 Ambientes en pozo en el Barrio N...,Departamento 2 Ambientes en pozo en el barrio...,NaN,-2.0,False,Electricidad | Agua | Internet | Aire Acondici...,...,58.0,52.0,Avenida Cabildo 4900,Nuñez,"Nuñez, Capital Federal",-34.539389,-58.475075,active,420571172-19,https://www.remax.com.ar/listings/venta-depto-...
1,639767,f20fce8e-1978-4158-8d38-885bf36dbf6e,sale,departamento_estandar,Venta Depto. 2 Ambientes Balcón en Nuñez,Departamento 2 Ambientes con Balcón a Jardīn d...,NaN,1.0,False,Electricidad | Agua | Internet | Aire Acondici...,...,52.0,44.0,Deheza 2300,Nuñez,"Nuñez, Capital Federal",-34.541243,-58.473025,active,420571172-18,https://www.remax.com.ar/listings/venta-depto-...
2,639766,7ac08d6f-4d6b-4f8d-bafe-3383754f65b2,sale,departamento_estandar,Venta Depto. 2 Amb. balcón a estrenar en Nuñez,Departamento 2 ambientes a estrenar con dispos...,NaN,1.0,False,Aire Acondicionado | Seguridad | Pileta | Saló...,...,54.0,46.0,Avenida Cabildo 4600,Nuñez,"Nuñez, Capital Federal",-34.541654,-58.473327,active,420571172-17,https://www.remax.com.ar/listings/venta-depto-...
3,639753,e3ee2b02-f6ca-491d-8668-f68e1910f663,sale,departamento_estandar,Venta depto 4 ambientes en Saavedra,Amplio 4 ambientes al frente con excelente ubi...,NaN,56.0,False,NaN,...,74.0,74.0,Paroissien 3800,Saavedra,"Saavedra, Capital Federal",-34.552870,-58.483751,active,421281075-30,https://www.remax.com.ar/listings/venta-depto-...
4,639745,f52cb804-2e0a-444c-93ef-cd3a3c3168db,sale,departamento_estandar,Venta departamento 3 ambientes Floresta,¡Luminoso 3 ambientes con vista abierta y exce...,NaN,16.0,True,NaN,...,58.0,53.0,Araujo 2900,Barrio Samore,"Barrio Samore, Villa Lugano, Capital Federal",-34.665952,-58.475327,active,420251189-202,https://www.remax.com.ar/listings/venta-depart...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16993 entries, 0 to 16992
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      16993 non-null  int64
 1   ID_Entidad              16993 non-null  object
 2   Operacion               16993 non-null  object
 3   Tipo_Propiedad          16993 non-null  object
 4   Titulo                  16993 non-null  object
 5   Descripcion             16887 non-null  object
 6   Fecha_Publicacion       0 non-null      float64
 7   Antiguedad              16419 non-null  float64
 8   Apto_Credito            16887 non-null  object
 9   Amenities               12962 non-null  object
 10  Moneda                  16993 non-null  object
 11  Precio_Valor            16993 non-null  float64
 12  Moneda_Expensas         16991 non-null  object
 13  Expensas                15778 non-null  float64
 14  Precio_m2_Total         16988 non-null  float64
 15  Precio_m2_Cubierto      16477 non-null  float64
 16  Ambientes               16993 non-null  int64
 17  Dormitorios             16993 non-null  int64
 18  Baños                   16993 non-null  int64
 19  Superficie_Total_m2     16993 non-null  float64
 20  Superficie_Cubierta_m2  16993 non-null  float64
 21  Direccion               16993 non-null  object
 22  Barrio                  16992 non-null  object
 23  Ubicacion               16992 non-null  object
 24  Latitud                 16993 non-null  float64
 25  Longitud                16993 non-null  float64
 26  Estado                  16993 non-null  object
 27  ID_Interno              16993 non-null  object
 28  Link                    16993 non-null  object
dtypes: float64(10), int64(4), object(15)
memory usage: 3.8+ MB

In [ ]:
faltantes = pd.DataFrame({
    "Cantidad": df.isna().sum(),
    "Porcentaje": (df.isna().mean() * 100).round(2)
})

faltantes = faltantes[faltantes["Cantidad"] > 0].sort_values(
    "Porcentaje",
    ascending=False
)

faltantes

                    Cantidad  Porcentaje
Fecha_Publicacion      16993      100.00
Amenities               4031       23.72
Expensas                1215        7.15
Antiguedad               574        3.38
Precio_m2_Cubierto       516        3.04
Descripcion              106        0.62
Apto_Credito             106        0.62
Precio_m2_Total            5        0.03
Moneda_Expensas            2        0.01
Barrio                     1        0.01
Ubicacion                  1        0.01

In [ ]:
print("Filas completamente duplicadas:", df.duplicated().sum())
print("ID duplicados:", df["ID"].duplicated().sum())
print("ID_Entidad duplicados:", df["ID_Entidad"].duplicated().sum())
print("Links duplicados:", df["Link"].duplicated().sum())

Filas completamente duplicadas: 0
ID duplicados: 0
ID_Entidad duplicados: 0
Links duplicados: 4

In [ ]:
df[df["Link"].duplicated(keep=False)][
    ["ID", "ID_Entidad", "Titulo", "Tipo_Propiedad", "Precio_Valor", "Barrio", "Link"]
].sort_values("Link")

,ID,ID_Entidad,Titulo,Tipo_Propiedad,Precio_Valor,Barrio,Link
5118,613459,40ca40d6-7bdd-450a-9ef1-5dc981bb61e8,Venta Departamento 3 Amb Desarrollo Villa Urquiza,departamento_estandar,315000.0,Villa Urquiza,https://www.remax.com.ar/listings/venta-depart...
15727,473067,aa82aea4-4143-45af-8163-a25ece2068c3,Venta Departamento 3 Amb Desarrollo Villa Urquiza,departamento_estandar,248318.0,Villa Urquiza,https://www.remax.com.ar/listings/venta-depart...
4271,618989,f6d0cb1d-5245-4995-99b5-f69911de484d,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,departamento_estandar,96000.0,Flores,https://www.remax.com.ar/listings/venta-deptos...
4272,618416,b9e7fd51-657c-4c3d-b17c-6d266458a11d,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,departamento_estandar,105000.0,Flores,https://www.remax.com.ar/listings/venta-deptos...
4273,618990,71f136c5-a5e8-4090-bf09-51132c86fa59,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,departamento_estandar,86000.0,Flores,https://www.remax.com.ar/listings/venta-deptos...
1658,632157,db0bc845-42f3-4d78-8ab7-4a83579c88ba,VENTA EN POZO NUÑEZ 2- 3 AMB ANTICIPO Y 60 CUOTAS,departamento_estandar,154664.0,Nuñez,https://www.remax.com.ar/listings/venta-en-poz...
2083,630104,7c86fdcf-4832-48ad-ad5b-946281868eab,VENTA EN POZO NUÑEZ 2- 3 AMB ANTICIPO Y 60 CUOTAS,departamento_estandar,118351.0,Nuñez,https://www.remax.com.ar/listings/venta-en-poz...

In [ ]:
df["Tipo_Propiedad"].value_counts()

Tipo_Propiedad
departamento_estandar        8880
ph                           1899
departamento_monoambiente    1453
casa                          896
cochera                       649
departamento_semipiso         592
terrenos_y_lotes              548
local                         457
oficina                       438
departamento_duplex           329
departamento_piso             305
deposito                       88
galpon                         71
departamento_loft              60
casa_duplex                    58
casa_triplex                   54
edificio                       53
departamento_triplex           48
consultorio                    33
departamento_penthouse         29
fondo_de_comercio              28
hotel                          20
otros                           5
Name: count, dtype: int64

In [ ]:
df_limpio = df.copy()

print("Registros en la base original:", len(df))
print("Registros en la copia de trabajo:", len(df_limpio))

Registros en la base original: 16993
Registros en la copia de trabajo: 16993

In [ ]:
df_limpio = df_limpio[
    df_limpio["Tipo_Propiedad"].str.startswith("departamento_")
].copy()

print("Registros antes del filtro:", len(df))
print("Departamentos después del filtro:", len(df_limpio))

Registros antes del filtro: 16993
Departamentos después del filtro: 11696

In [ ]:
df_limpio["Moneda"].value_counts(dropna=False)

Moneda
USD    11696
Name: count, dtype: int64

In [ ]:
print("Precio igual a 0:",
      (df_limpio["Precio_Valor"] == 0).sum())

print("Precio menor a 0:",
      (df_limpio["Precio_Valor"] < 0).sum())

Precio igual a 0: 0
Precio menor a 0: 0

In [ ]:
print("Superficie total igual a 0:",
      (df_limpio["Superficie_Total_m2"] == 0).sum())

print("Superficie total menor a 0:",
      (df_limpio["Superficie_Total_m2"] < 0).sum())

Superficie total igual a 0: 0
Superficie total menor a 0: 0

In [ ]:
print("Superficie cubierta igual a 0:",
      (df_limpio["Superficie_Cubierta_m2"] == 0).sum())

print("Superficie cubierta menor a 0:",
      (df_limpio["Superficie_Cubierta_m2"] < 0).sum())

Superficie cubierta igual a 0: 1
Superficie cubierta menor a 0: 0

In [ ]:
df_limpio.loc[
    df_limpio["Superficie_Cubierta_m2"] == 0,
    ["ID", "Titulo", "Precio_Valor",
     "Superficie_Total_m2", "Superficie_Cubierta_m2",
     "Barrio", "Link"]
]

,ID,Titulo,Precio_Valor,Superficie_Total_m2,Superficie_Cubierta_m2,Barrio,Link
5859,609401,DEPTO TIPO LOFT EN VTA RECICLADO A NUEVO LUMINOSO,75000.0,37.87,0.0,Balvanera,https://www.remax.com.ar/listings/depto-tipo-l...

In [ ]:
print(
    "Superficie cubierta mayor a superficie total:",
    (df_limpio["Superficie_Cubierta_m2"] > df_limpio["Superficie_Total_m2"]).sum()
)

Superficie cubierta mayor a superficie total: 0

In [ ]:
print("Ambientes igual a 0:",
      (df_limpio["Ambientes"] == 0).sum())

print("Ambientes menor a 0:",
      (df_limpio["Ambientes"] < 0).sum())

Ambientes igual a 0: 1
Ambientes menor a 0: 0

In [ ]:
df_limpio.loc[
    df_limpio["Ambientes"] == 0,
    ["ID", "Titulo", "Tipo_Propiedad", "Precio_Valor",
     "Ambientes", "Dormitorios", "Baños",
     "Superficie_Total_m2", "Barrio", "Link"]
]

,ID,Titulo,Tipo_Propiedad,Precio_Valor,Ambientes,Dormitorios,Baños,Superficie_Total_m2,Barrio,Link
11987,563405,MONOAMBIENTE balcón sum excelente ubicación,departamento_monoambiente,79000.0,0,0,1,31.35,Villa del Parque,https://www.remax.com.ar/listings/monoambiente...

In [ ]:
df_limpio.loc[df_limpio["ID"] == 563405, "Ambientes"] = 1

print("Ambientes igual a 0:",
      (df_limpio["Ambientes"] == 0).sum())

Ambientes igual a 0: 0

In [ ]:
print("Baños igual a 0:",
      (df_limpio["Baños"] == 0).sum())

print("Baños menor a 0:",
      (df_limpio["Baños"] < 0).sum())

Baños igual a 0: 0
Baños menor a 0: 0

In [ ]:
print("Dormitorios igual a 0:",
      (df_limpio["Dormitorios"] == 0).sum())

print("Dormitorios menor a 0:",
      (df_limpio["Dormitorios"] < 0).sum())

Dormitorios igual a 0: 1486
Dormitorios menor a 0: 0

In [ ]:
print("Antigüedad faltante:",
      df_limpio["Antiguedad"].isna().sum())

print("Antigüedad igual a 0:",
      (df_limpio["Antiguedad"] == 0).sum())

print("Antigüedad menor a 0:",
      (df_limpio["Antiguedad"] < 0).sum())

Antigüedad faltante: 104
Antigüedad igual a 0: 1426
Antigüedad menor a 0: 185

In [ ]:
df_limpio.loc[
    df_limpio["Antiguedad"] < 0,
    "Antiguedad"
].value_counts().sort_index()

Antiguedad
-3.0     11
-2.0     71
-1.0    103
Name: count, dtype: int64

In [ ]:
df_limpio.loc[
    df_limpio["Antiguedad"] < 0,
    ["ID", "Titulo", "Antiguedad", "Barrio"]
].head(15)

,ID,Titulo,Antiguedad,Barrio
0,639768,Venta Depto 2 Ambientes en pozo en el Barrio N...,-2.0,Nuñez
222,638842,3 Dormitorios + Dep. | SUCÁ | Financiación,-2.0,Balvanera
225,638837,3 Dormitorios+SUCÁ | Financiado-,-2.0,Balvanera
228,638821,2 Dormitorios + Dependencia | Balcón | Financiado,-1.0,Balvanera
342,638221,VENTA MONOAMBIENTE NUÑEZ POZO FINANC ENTREGA 2...,-2.0,Nuñez
343,638220,VENTA 2 AMBIENTES NUÑEZ POZO FINANC ENTREGA 2028.,-2.0,Nuñez
478,637636,VENTA Monoambiente POZO Colegiales Parrilla,-1.0,Colegiales
479,637634,VENTA 2 ambientes POZO Colegiales Balcon Parrilla,-1.0,Colegiales
480,637632,VENTA 2 ambientes POZO Colegiales Balcon Parrilla,-1.0,Colegiales
481,637630,VENTA 3 ambientes POZO Colegiales TERRAZA PROPIA,-1.0,Colegiales
670,636664,VENTA MONO AMBIENTE DESDE POZO V. URQUIZA,-1.0,Villa Urquiza
671,636663,VENTA DPTO 3 AMBIENTES EN ÚLTIMO PISO V. URQUIZA,-1.0,Villa Urquiza
778,636197,2 ambientes en venta - Villa Devoto,-1.0,Villa Devoto
969,635450,VENTA 2 AMBIENTES Y MEDIO VILLA CRESPO CON BALCON,-1.0,Villa Crespo
990,635368,VENTA 1 AMBIENTE VILLA CRESPO A ESTRENAR,-1.0,Villa Crespo

In [ ]:
en_pozo = (
    df_limpio["Titulo"].str.contains("pozo", case=False, na=False) |
    df_limpio["Descripcion"].str.contains("pozo", case=False, na=False)
)

print("Departamentos que mencionan 'pozo':", en_pozo.sum())

Departamentos que mencionan 'pozo': 575

In [ ]:
print(
    "Antigüedad negativa que menciona 'pozo':",
    ((df_limpio["Antiguedad"] < 0) & en_pozo).sum()
)

print(
    "Antigüedad negativa que NO menciona 'pozo':",
    ((df_limpio["Antiguedad"] < 0) & ~en_pozo).sum()
)

Antigüedad negativa que menciona 'pozo': 99
Antigüedad negativa que NO menciona 'pozo': 86

In [ ]:
df_limpio.loc[
    (df_limpio["Antiguedad"] < 0) & (~en_pozo),
    ["ID", "Titulo", "Antiguedad", "Descripcion"]
].head(20)

,ID,Titulo,Antiguedad,Descripcion
222,638842,3 Dormitorios + Dep. | SUCÁ | Financiación,-2.0,\n# PROYECTO en Construccion en ANCHORENA 807 ...
225,638837,3 Dormitorios+SUCÁ | Financiado-,-2.0,Torre en construccion en ANCHORENA y SAN LUI...
228,638821,2 Dormitorios + Dependencia | Balcón | Financiado,-1.0,CORRIENTES 2100 | 3 AMBIENTES + DEPENDENCIA | ...
671,636663,VENTA DPTO 3 AMBIENTES EN ÚLTIMO PISO V. URQUIZA,-1.0,EXCLUSIVO DPTO 3 AMBIENTES EN ÚLTIMO PISO EN V...
969,635450,VENTA 2 AMBIENTES Y MEDIO VILLA CRESPO CON BALCON,-1.0,VENTA DEPARTAMENTO VILLA CRESPO DOS AMBIENTES ...
990,635368,VENTA 1 AMBIENTE VILLA CRESPO A ESTRENAR,-1.0,\nVENTA 1 AMBIENTE - VILLA CRESPO\n\nFinancia...
1285,633976,DEPARTAMENTO venta 2 AMBIENTES 42 METROS Cabal...,-2.0,Ubicado estratégicamente en el corazón de Caba...
2511,628105,VENTA DEPTO 3 AMB C/ BALC/ AMENT/ EXC VILLA DE...,-1.0,VENTA DEPARTAMENTO 3 AMBIENTES CON BALCÓN EN V...
2512,628104,VENTA DPTO 3 AMB C/ BALC/ AMENIT/EXC VILLA DEVOTO,-1.0,VENTA DEPARTAMENTO 3 AMBIENTES CON BALCÓN EN V...
2515,628101,VENTA MONOAMBIENTE DIVISIBLE C/ BALC/ AMEN DE...,-1.0,MONOAMBIENTE DIVISIBLE CON BALCÓN + AMENITIES ...
2660,627435,VENTA DEPARTAMENTO 2 AMBIENTES NUÑEZ BALCON,-1.0,VENTA | DEPARTAMENTO 2 AMBIENTES EN NUÑEZ\n\nE...
3103,625206,Monoambiente Oportunidad de Inversion Financia...,-2.0,"MONOAMBIENTE A ESTRENAR EN VENTA EN COGHLAN, C..."
3125,625116,VENTA DEPARTAMENTO MONOAMBIENTE EN VILLA ORTUZAR,-1.0,VENTA EXCELENTE DEPARTAMENTO MONOAMBIENTE EN E...
3170,624866,VENTA MONOAMBIENTE PALERMO IDEAL INVERSION,-2.0,VENTA DEPARTAMENTO MONOAMBIENTE PALERMO HOLLYW...
4037,619875,Dto 2 ambientes en venta c/toilette Colegiales,-1.0,Listo para ingresar!!!\n\nDepartamento 2 ambie...
4116,619431,VENTA DUPLEX 2 AMBIENTES PALERMO HOLYWOOD BALCON,-2.0,"More III | Palermo Hollywood | Fitz Roy 2145, ..."
4293,618289,VENTA DEPARTAMENTO 2 AMBIENTES PALERMO AIR BNB,-2.0,"More III | Palermo Hollywood | Fitz Roy 2145, ..."
4826,615238,VENTA 2 AMBIENTES EN CONSTRUCCION VILLA CRESPO,-2.0,---START VILLA CRESPO--- ---INVERSION--- ...
4829,615230,VENTA DEPARTAMENTO MONOAMBIENTE PALERMO HOLYWOOD,-2.0,"More III | Palermo Hollywood | Fitz Roy 2145, ..."
5052,614062,VENTA DEPARTAMENTO 3 AMBIENTES VILLA CRESPO BA...,-2.0,DEPARTAMENTO 3 AMBIENTES EN VENTA | START VILL...

In [ ]:
patron_nuevo = r"pozo|a estrenar|en construcci[oó]n|proyecto|entrega"

nuevo_antiguedad_0 = df_limpio[
    (df_limpio["Antiguedad"] == 0) &
    (
        df_limpio["Titulo"].str.contains(patron_nuevo, case=False, na=False) |
        df_limpio["Descripcion"].str.contains(patron_nuevo, case=False, na=False)
    )
]

print("Antigüedad 0:", (df_limpio["Antiguedad"] == 0).sum())
print("Antigüedad 0 con indicios de propiedad nueva:", len(nuevo_antiguedad_0))

Antigüedad 0: 1426
Antigüedad 0 con indicios de propiedad nueva: 1339

In [ ]:
casos_antiguedad_0 = df_limpio[
    (df_limpio["Antiguedad"] == 0) &
    ~(
        df_limpio["Titulo"].str.contains(patron_nuevo, case=False, na=False) |
        df_limpio["Descripcion"].str.contains(patron_nuevo, case=False, na=False)
    )
]

casos_antiguedad_0[
    ["ID", "Titulo", "Antiguedad", "Descripcion"]
].head(20)

,ID,Titulo,Antiguedad,Descripcion
487,637519,Venta Monoambiente Palermo Hollywood,0.0,"MONOAMBIENTE EN VENTA EN PALERMO HOLLYWOOD, CA..."
728,636427,VENTA DEPARTAMENTO 4 AMB VILLA DEL PARQUE ESTR...,0.0,"En un piso octavo al contra frente, con orient..."
814,636043,DEPARTAMENTO EN VENTA 3 AMBIENTES BALVANERA,0.0,DEPARTAMENTO 3 AMBIENTES EN VENTA\n\nORIENTACI...
987,635372,VENTA DEPARTAMENTO 3 AMBIENTES BALCON ALMAGRO,0.0,DEPARTAMENTO 3 AMBIENTES IMPECABLE - MUDATE YA...
1072,634913,DEPARTAMENTO VENTA BALVANERA FINANCIADO 84 CUOTAS,0.0,\n DEPARTAMENTO 3 AMBIE...
1093,634831,VENTA 3 AMB - VILLA LURO - 80 M2 - SUITE,0.0,...
1094,634830,VENTA 2 AMB - VILLA LURO - 54 M2 - SUITE - TOI...,0.0,********* PRE-VENTA *********\nFORMA DE PAGO 3...
1095,634829,VENTA 2 AMB - VILLA LURO - 48 M2 - SUITE - TOI...,0.0,********* PRE-VENTA *********\nFORMA DE PAGO 3...
1428,633267,VENTA DEPTO 2 AMB EN RECOLETA CON AMPLIO BALCON,0.0,"DEPARTAMENTO 2 AMBIENTES EN VENTA EN RECOLETA,..."
1440,633243,VENTA DEPTO MONOAMBIENTE BELGRANO R FULL AMENI...,0.0,"Maker Belgrano, es un emprendimiento desarroll..."
1619,632316,VENTA Monoambiente RECOLETA luminoso CON RENTA,0.0,VENTA | MONOAMBIENTE EN RECOLETA CON RENTA – I...
1936,630784,Departamento Monoambiente Venta Villa Santa Rita,0.0,Departamento Monoambiente en el 8° piso al con...
1937,630780,Departamento 2 Ambientes en Venta Villa Santa ...,0.0,\nDepartamento de 2 Ambientes en el 7° piso.\...
2043,630244,VENTA 2 AMB - VILLA LURO - 48 M2 - 4º B,0.0,********* PRE-VENTA *********\nFORMA DE PAGO 3...
2044,630243,VENTA 2 AMB - VILLA LURO - 48 M2 - 8º B,0.0,********* PRE-VENTA *********\nFORMA DE PAGO 3...
2105,630026,VENTA DEPARTAMENTO MONOAMBIENTE EN PALERMO,0.0,VENTA DEPARTAMENTO MONOAMBIENTE EN PALERMO\nPo...
2106,630025,VENTA DEPARTAMENTO 2 AMBIENTES PALERMO,0.0,VENTA DEPARTAMENTO 2 AMBIENTES PALERMO \nPoses...
2107,630024,VENTA DEPARTAMENTO 3 AMBIENTES EN PALERMO,0.0,VENTA DEPARTAMENTO 3 AMBIENTES EN PALERMO\nPos...
2399,628679,2 Ambientes con Balcón en Núñez Excelente Ubic...,0.0,Venta de Departamento de 2 Ambientes en el Nue...
2456,628410,Venta Depto 4 amb Edificio Vicenza Caballito,0.0,Viví en un edificio de categoría diseñado por ...

In [ ]:
patron_nuevo = (
    r"pozo|a estrenar|estrenar|en construcci[oó]n|"
    r"proyecto|entrega|pre[\s-]?venta|emprendimiento|posesi[oó]n"
)

es_nuevo = (
    df_limpio["Titulo"].str.contains(patron_nuevo, case=False, na=False) |
    df_limpio["Descripcion"].str.contains(patron_nuevo, case=False, na=False) |
    (df_limpio["Antiguedad"] < 0)
)

print("Departamentos identificados como nuevos/en desarrollo:", es_nuevo.sum())
print("Departamentos restantes:", (~es_nuevo).sum())

Departamentos identificados como nuevos/en desarrollo: 3371
Departamentos restantes: 8325

In [ ]:
df_limpio.loc[
    es_nuevo,
    ["ID", "Titulo", "Antiguedad"]
].sample(20, random_state=42)

           ID                                             Titulo  Antiguedad
16452  390765       VENTA COGHLAN MODERNO 2 AMBIENTES CON BALCON         1.0
4642   616139                    MONOAMBIENTE VENTA VILLA DEVOTO         5.0
13929  535996             Venta Monoambiente a estrenar Floresta         3.0
554    637160      VENTA DEPARTAMENT0 2 AMBIENTES ESTRENAR NUÑEZ         0.0
9722   584715               Mono I Balcon al frente I a Estrenar         0.0
2736   627115        VENTA MONOAMBIENTE A ESTRENAR VILLA URQUIZA         0.0
11599  567749  3 ambientes con balcon en almagro - Subte Line...        50.0
342    638221  VENTA MONOAMBIENTE NUÑEZ POZO FINANC ENTREGA 2...        -2.0
796    636110  VENTA DEPTO PB 2 AMBIENTES CON PATIO - VILLA REAL         0.0
11732  566252  Venta Monoambiente a Estrenar + AMENITIES Flor...         0.0
15084  506359     Venta Pozo Depto 2 Amb V. Pueyrredón 84 cuotas         0.0
1754   631589   departamento 1 ambiente a estrenar Villa Urquiza         0.0
8207   594502  VENTA 2 AMBIENTES VILLA URQUIZA AMENITIES ESTR...         1.0
5225   612913  VENTA POZO 2 AMB BALCON TERAZA AMENITIES CABAL...        -2.0
1902   630899  Venta monoabiente en Torre a estrenar en Barracas         2.0
3829   621153   DEPARTAMENTO MONOAMBIENTE A ESTRENAR - VERSALLES         0.0
5386   612007         MONOAMBIENTE EN VENTA EN MONTE CASTRO CABA         1.0
13344  546010  DEPARTAMENTO 3 AMBIENTES VENTA BELGRANO A ESTR...         0.0
2312   629093      Venta en construcción, monoambiente Monserrat         3.0
7195   601497       Venta departamento 3 amb A Estrenar - P.Chas         1.0

In [ ]:
df_limpio.loc[
    df_limpio["ID"].isin([390765, 616139, 567749, 636110, 612007]),
    ["ID", "Titulo", "Descripcion", "Antiguedad"]
]

,ID,Titulo,Descripcion,Antiguedad
796,636110,VENTA DEPTO PB 2 AMBIENTES CON PATIO - VILLA REAL,VENTA DEPTO PB 2 AMBIENTES CON PATIO- VILLA RE...,0.0
4642,616139,MONOAMBIENTE VENTA VILLA DEVOTO,"MONOAMBIENTE EN VENTA EN VILLA DEVOTO, CAPITAL...",5.0
5386,612007,MONOAMBIENTE EN VENTA EN MONTE CASTRO CABA,PRE-VENTA MONOAMBIENTE EN MONTE CASTRO CAPITAL...,1.0
11599,567749,3 ambientes con balcon en almagro - Subte Line...,DEPARTAMENTO 3 AMBIENTES VENTA ALMAGRO CAPITAL...,50.0
16452,390765,VENTA COGHLAN MODERNO 2 AMBIENTES CON BALCON,EXCELENTE OPORTUNIDAD DE INVERSION\n\nEQUIPO R...,1.0

In [ ]:
import re

terminos = [
    "pozo",
    "a estrenar",
    "estrenar",
    "en construccion",
    "en construcción",
    "proyecto",
    "entrega",
    "pre-venta",
    "preventa",
    "emprendimiento",
    "posesion",
    "posesión"
]

for id_prop in [390765, 616139, 567749, 636110, 612007]:
    fila = df_limpio[df_limpio["ID"] == id_prop].iloc[0]
    texto = (str(fila["Titulo"]) + " " + str(fila["Descripcion"])).lower()

    encontrados = [termino for termino in terminos if termino in texto]

    print(id_prop, "->", encontrados)

390765 -> ['en construccion', 'entrega', 'preventa']
616139 -> ['a estrenar', 'estrenar']
567749 -> ['proyecto']
636110 -> ['a estrenar', 'estrenar']
612007 -> ['proyecto', 'entrega', 'pre-venta', 'emprendimiento']

In [ ]:
patron_nuevo_fuerte = r"pozo|a estrenar|estrenar|en construcci[oó]n|pre[\s-]?venta"

mask_ant0 = df_limpio["Antiguedad"] == 0

mask_nuevo_fuerte = (
    df_limpio["Titulo"].str.contains(patron_nuevo_fuerte, case=False, na=False) |
    df_limpio["Descripcion"].str.contains(patron_nuevo_fuerte, case=False, na=False)
)

print("Antigüedad 0 total:", mask_ant0.sum())
print("Antigüedad 0 con indicios fuertes de nuevo:",
      (mask_ant0 & mask_nuevo_fuerte).sum())
print("Antigüedad 0 sin esos indicios:",
      (mask_ant0 & ~mask_nuevo_fuerte).sum())

Antigüedad 0 total: 1426
Antigüedad 0 con indicios fuertes de nuevo: 1156
Antigüedad 0 sin esos indicios: 270

In [ ]:
es_nuevo_conservador = (
    (df_limpio["Antiguedad"] < 0) |
    (
        (df_limpio["Antiguedad"] == 0) &
        mask_nuevo_fuerte
    )
)

print("Departamentos identificados como nuevos/en desarrollo:",
      es_nuevo_conservador.sum())

print("Departamentos que quedarían para análisis:",
      (~es_nuevo_conservador).sum())

Departamentos identificados como nuevos/en desarrollo: 1341
Departamentos que quedarían para análisis: 10355

In [ ]:
df_limpio.loc[
    es_nuevo_conservador,
    ["ID", "Titulo", "Antiguedad"]
].sample(20, random_state=42)

           ID                                             Titulo  Antiguedad
8835   590586                 Venta depto emprendimiento Lugones         0.0
5549   611079      VENTA DE DEPARTAMENTO MONOAMBIENTE EN PALERMO        -1.0
5807   609776    Venta Monoambiente -Con renta desde Pozo 500USD         0.0
4326   618130  Monoambiente en Venta con Balcón al Frente en ...         0.0
2353   628936  VENTA 1 AMB A ESTRENAR FULL AMENITIES EN SAN T...         0.0
2758   627051      Departamento Venta 3 Amb Caballito A Estrenar         0.0
13630  540670       Dep 2 ambientes en venta c/balcón Colegiales        -1.0
5075   613750       Venta depto monoambiente en Nuñez a estrenar         0.0
10515  578231  BARRIO NAON 4 AMB 131 M2 PATIO ESTRENAR CATEGORIA         0.0
7522   599272  VENTA DEPARTAMENTO 2 AMBIENTES A ESTRENAR PARR...         0.0
12841  552885     VENTA DEPTO 3 AMB FULL AMENITIES VILLA URQUIZA         0.0
13771  538227   DEPARTAMENTO 2 AMBIENTES VENTA PALERMO AMENITIES         0.0
613    636948               Venta 2 ambientes a estrenar Almagro         0.0
2459   628399    Venta 4 amb Edificio Vicenza Caballito Estrenar         0.0
13669  539910   VENTA 2 AMB LA ISLA RECOLETA FULL AMENITIES POZO        -2.0
6122   607553     Venta 1 amb Nuñez POZO FINANCIACION 180 cuotas         0.0
6707   604162    MONOAMBIENTE IMPECABLE ARMENIA Y GORRITI P.SOHO         0.0
12117  561760  Blanco Encalada  2009 Piso 3 Dpto A (1428), Co...         0.0
5434   611776  VENTA DEPTO 4 AMB EN ALMAGRO A ESTRENAR C TERRAZA         0.0
9212   588310       Duplex 2 Amb c/balcón. A estrenar. Caballito         0.0

In [ ]:
df_limpio = df_limpio.loc[~es_nuevo_conservador].copy()

print("Departamentos luego de excluir nuevos/en desarrollo:", len(df_limpio))

Departamentos luego de excluir nuevos/en desarrollo: 10355

In [ ]:
faltantes_limpio = pd.DataFrame({
    "Cantidad": df_limpio.isna().sum(),
    "Porcentaje": (df_limpio.isna().mean() * 100).round(2)
})

faltantes_limpio = faltantes_limpio[
    faltantes_limpio["Cantidad"] > 0
].sort_values("Porcentaje", ascending=False)

faltantes_limpio

                    Cantidad  Porcentaje
Fecha_Publicacion      10355      100.00
Amenities               1908       18.43
Antiguedad               104        1.00
Descripcion              103        0.99
Apto_Credito             103        0.99
Moneda_Expensas            1        0.01
Precio_m2_Cubierto         1        0.01
Barrio                     1        0.01
Ubicacion                  1        0.01

In [ ]:
df_limpio.loc[
    df_limpio["Antiguedad"].isna(),
    ["ID", "Titulo", "Descripcion", "Antiguedad"]
].head(20)

,ID,Titulo,Descripcion,Antiguedad
10,639751,VENTA MIDOKI ARGERICH 2783 VILLA DEL PARQUE,NaN,NaN
31,639663,Emprendimiento en Lavalle 4018,NaN,NaN
33,639657,EMPRENDIMIENTO EN LAVALLE 4078,NaN,NaN
71,639535,"VENTA DPTOS. EN POZO 1,2 Y 3 AMB TRON BUILDING",NaN,NaN
114,639331,VENTA DPTOS DE 1 Y 2 AMB-AMENITIES DESDE 95.92...,NaN,NaN
241,638776,EMPRENDIMIENTO EN ALMAGRO ENTREGA OCTUBRE 2026,NaN,NaN
363,638648,SKY ANCHORENA FINANCIACION AMENITIES PREMIUM,NaN,NaN
507,637544,DEPARTAMENTOS EN POZO MINIMO ANTICIPO VILLA CR...,NaN,NaN
1026,635642,Emprendimiento Punto Caballito Avda Directorio...,NaN,NaN
1617,633311,Venta pozo Emprendimiento Villa ortuzar,NaN,NaN
1740,632337,VENTA DTO POZO 1 - 2 - 3 AMB DONATO ALVAREZ,NaN,NaN
2059,630242,SOLACE ESTOMBA,NaN,NaN
2232,629425,EMPRENDIMIENTO AL POZO - BELGRANO,NaN,NaN
2818,626767,Residencias de Villa del Parque,NaN,NaN
2956,625979,VENTA DPTOS 2 Y 3 AMBIENTES EN SAAVEDRA! PERMUTA,NaN,NaN
3279,624240,Emprendimiento Well Thomas,NaN,NaN
4271,618989,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,NaN,NaN
4272,618416,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,NaN,NaN
4273,618990,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,NaN,NaN
4276,618406,VENTA DEPTOS. EN POZO FLORES 2 Y 3 AMB C/AMENI...,NaN,NaN

In [ ]:
mask_antiguedad_na = df_limpio["Antiguedad"].isna()

mask_nuevo_faltante = (
    mask_antiguedad_na &
    (
        df_limpio["Titulo"].str.contains(
            patron_nuevo_fuerte, case=False, na=False
        ) |
        df_limpio["Descripcion"].str.contains(
            patron_nuevo_fuerte, case=False, na=False
        )
    )
)

print("Antigüedad faltante total:", mask_antiguedad_na.sum())
print("Con indicios fuertes de nuevo:", mask_nuevo_faltante.sum())
print("Sin indicios fuertes:", (mask_antiguedad_na & ~mask_nuevo_faltante).sum())

Antigüedad faltante total: 104
Con indicios fuertes de nuevo: 44
Sin indicios fuertes: 60

In [ ]:
df_limpio = df_limpio.loc[~mask_nuevo_faltante].copy()

print("Departamentos restantes:", len(df_limpio))
print("Antigüedad faltante restante:", df_limpio["Antiguedad"].isna().sum())

Departamentos restantes: 10311
Antigüedad faltante restante: 60

In [ ]:
df_limpio["Precio_m2_Total"].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    10311.000000
mean      2209.419331
std        829.673648
min          0.290000
1%         789.007000
5%        1140.915000
25%       1661.840000
50%       2097.560000
75%       2603.890000
95%       3672.110000
99%       4824.404000
max      15403.420000
Name: Precio_m2_Total, dtype: float64

In [ ]:
extremos_precio_m2 = pd.concat([
    df_limpio.nsmallest(10, "Precio_m2_Total"),
    df_limpio.nlargest(10, "Precio_m2_Total")
])

extremos_precio_m2[
    [
        "ID", "Titulo", "Barrio",
        "Precio_Valor", "Superficie_Total_m2",
        "Precio_m2_Total"
    ]
]

,ID,Titulo,Barrio,Precio_Valor,Superficie_Total_m2,Precio_m2_Total
9826,583834,"Venta Departamento Dúplex Penthouse, Belgrano",Belgrano,58.0,197.00,0.29
643,636809,ALQUILER DEPTO 3 AMB C/COCHERA 2 HAB/SUITE CAÑ...,Las Cañitas,2300.0,127.00,18.11
4023,619962,VENTA DEPARTAMENTO 5 AMB VILLA SOLDATI A RECICLAR,Villa Soldati,29000.0,99.00,292.93
15823,465887,VENTA DEPARTAMENTO 3 AMB + CONSTRUCCION MIXTA ...,La Boca,70000.0,186.00,376.34
8810,590743,VENTA DEPARTAMENTO 5 AMBIENTES VILLA SOLDATI,Villa Soldati,30000.0,77.80,385.60
10371,579629,Venta 5 ambientes Villa Soldati,Villa Soldati,32500.0,83.00,391.57
8292,594028,VENTA NUDA PROPIEDAD DPTO 2 AMB SAN CRISTOBAL,San Cristobal,30000.0,68.90,435.41
14132,531879,"VENTA DEPTO 4 AMB LUGANO +PATIO TECH, LUMINOSO",Villa Lugano,31000.0,69.81,444.06
10691,576765,Departamento en Venta Tribunales Terraza,Barrio Norte,49900.0,111.66,446.89
10271,580438,Departamento 5 ambientes en el Barrio Piedrabuena,Villa Lugano,44000.0,95.00,463.16
13791,537642,PISO 34 -TERMINADO con materiales premium unicos,Palermo,6300000.0,409.00,15403.42
6547,605137,EXCLUSIVO PISO ALTO EN TORRES DECO POLO,Las Cañitas,1450000.0,156.00,9294.87
16064,444264,VENTA DEPARTAMENTO 5 AMB + DEP TORRE BELLINI N...,Nuñez,2900000.0,334.62,8666.55
806,636067,VENTA ESPECTACULAR PISO ALTO CHATEAU LIBERTADOR,Nuñez,4400000.0,511.04,8609.89
14123,532144,VENTA DEPTO 2AMB C/ COCHERA BAULERA FULL AMENI...,Belgrano,495000.0,60.23,8218.50
501,637447,Piso muy alto en Le Parc Puerto Madero Vista 360°,Puerto Madero,1450000.0,178.47,8124.61
12333,559265,VENTA DEPARTAMENTO NUÑEZ CUATRO AMBIENTES EN T...,Nuñez,1790000.0,225.00,7955.56
10152,581379,Departamento 4 Amb. C/Cochera Torre Decó - Pis...,Recoleta,1200000.0,156.27,7679.02
15888,460558,"Departamento sempiso P 11, 3 suite 2 coch amen...",Palermo Chico,1300000.0,172.50,7536.23
271,638556,Departamento de 3 ambientes en Venta en Palermo,Palermo,560000.0,74.76,7490.64

In [ ]:
df_limpio["Operacion"].value_counts(dropna=False)

Operacion
sale    10311
Name: count, dtype: int64

In [ ]:
mask_alquiler = (
    df_limpio["Titulo"].str.contains(r"\balquiler\b", case=False, na=False)
)

print("Publicaciones 'sale' que mencionan ALQUILER en el título:", mask_alquiler.sum())

df_limpio.loc[
    mask_alquiler,
    ["ID", "Titulo", "Precio_Valor", "Barrio", "Operacion"]
]

Publicaciones 'sale' que mencionan ALQUILER en el título: 4

,ID,Titulo,Precio_Valor,Barrio,Operacion
643,636809,ALQUILER DEPTO 3 AMB C/COCHERA 2 HAB/SUITE CAÑ...,2300.0,Las Cañitas,sale
5957,608659,VENTA MONOAMBIENTE MODERNO CON CONTRATO ALQUILER,83000.0,Balvanera,sale
9131,588949,Alquiler Tres ambientes en Villa Crespo,127000.0,Villa Crespo,sale
12351,558953,"VENTA DEPARTAMENTO 3 AMB BELGRANO R, CON ALQUI...",189000.0,Belgrano R,sale

In [ ]:
for id_prop in [636809, 588949]:
    fila = df_limpio[df_limpio["ID"] == id_prop].iloc[0]

    print("\nID:", id_prop)
    print("Título:", fila["Titulo"])
    print("Precio:", fila["Precio_Valor"])
    print("Descripción:")
    print(fila["Descripcion"])
    print("-" * 80)

ID: 636809
Título: ALQUILER DEPTO 3 AMB C/COCHERA 2 HAB/SUITE CAÑITAS
Precio: 2300.0
Descripción:
Se alquila departamento a estrenar de categoría en el corazón del barrio Las Cañitas, la propiedad esta dispuesta al frente de un tercer piso super tranquilo, Allí la calle 11 de septiembre no cuenta con salida y hay muy poca circulación.
La zona es divina, conocido Barrio trendy, con infinidad de opciones gastronómicas. A metros de la estación de subte Olleros sobre Av. cabildo y próximo a Av. Libertador, zona codiciada por turistas que visitan nuestra Capital.
Con orientación este, recibe todo el sol de mañana, es super luminoso, aberturas con Doble vidrio hermético.  Cuenta con living comedor con cocina integrada. Isla equipada con horno eléctrico y anafe de calidad.
Aire frio calor y salida al balcón corrido al igual que el resto de los ambientes.
Toilette de recepción.
Dos habitaciones en suite con placard y aires acondicionados .
Dependencia de servicio.
Cochera en el primer subsuelo.
El edificio cuenta con Totem de seguridad, Pileta con solarium en el último piso. Parrilla y  Gimnasio.

Las superficies son aproximadas.
--------------------------------------------------------------------------------

ID: 588949
Título: Alquiler Tres ambientes en Villa Crespo
Precio: 127000.0
Descripción:
Departamento tres ambientes en alquiler, piso alto ,muy luminoso,  contrafrente.
Living Comedor, con pisos en parquet y salida al balcón corrido.
Un pasillo  distribuye los dos dormitorios ,el primero con puerta ventana salida  al balcón , y uno mas pequeño con ventana que da al balcón. Ambos ambientes con sus respectivos placares .
Un baño completo con bañera y ventana.
La cocina es amplia con mucho lugar de guardado , lavadero y toilette.
El departamento NO tiene aire acondicionado , estufa de tiro balanceado en el living

Ubicado en el barrio de Villa Crespo, a una cuadra de Avenida  Corrientes,  con muchísimos medios de transporte , linea B de subte(estación Pugliese)
Rodeado de negocios, supermercados, muy buena oferta gastronómica, a cuadras del parque Centenario.

Requisitos de alquiler
Un mes de adelanto, un mes de deposito.
Demostración de ingresos con recibos en blanco
Seguro de caución preaprobado (Finaer o  garantía ya)
 Garantía propietaria de CABA, pedido de informes de dominio e inhibición  y nuevos pedidos de informes al comenzar el segundo año de locación , ambos a cargo del locatario.
Aumento trimestral según IPC

--------------------------------------------------------------------------------

In [ ]:
ids_alquiler = [636809, 588949]

df_limpio = df_limpio.loc[
    ~df_limpio["ID"].isin(ids_alquiler)
].copy()

print("Departamentos restantes:", len(df_limpio))
print("¿Siguen los alquileres?:", df_limpio["ID"].isin(ids_alquiler).sum())

Departamentos restantes: 10309
¿Siguen los alquileres?: 0

In [ ]:
fila = df_limpio[df_limpio["ID"] == 583834].iloc[0]

print("Título:", fila["Titulo"])
print("Precio cargado:", fila["Precio_Valor"])
print("Superficie total:", fila["Superficie_Total_m2"])
print("Precio m²:", fila["Precio_m2_Total"])
print("\nDescripción:")
print(fila["Descripcion"])

Título: Venta Departamento  Dúplex  Penthouse, Belgrano
Precio cargado: 58.0
Superficie total: 197.0
Precio m²: 0.29

Descripción:
PASEO DEL ÁNGEL | CASA DEL ÁNGEL
Arcos y Sucre | Belgrano

Exclusivo departamento en dúplex con palier privado, 2 cocheras y excelente luminosidad, ubicado en uno de los edificios más emblemáticos de Belgrano: Casa del Ángel.

Ubicado sobre la calle Arcos esquina Sucre, a pasos de Av. Cabildo, Barrancas de Belgrano, medios de transporte, polo gastronómico y comercial.

La propiedad se desarrolla en dos plantas y combina amplitud, funcionalidad y una excelente distribución.

Al ingresar nos encontramos con un amplio living comedor al frente, con salida a balcón corrido y orientación Este, lo que garantiza sol directo y gran luminosidad durante gran parte del día. Cuenta además con espacio para comedor diario o sector de TV.

La cocina es independiente, con ventilación natural, conexión a gas y espacio para lavavajillas. La unidad posee doble circulación, con ingreso principal por palier privado e ingreso de servicio.

En esta planta también se encuentra un toilette de recepción.

En la planta superior se ubican los dormitorios. Originalmente diseñado como un 4 ambientes, actualmente cuenta con 2 dormitorios de excelentes dimensiones.

La master suite se destaca por su amplitud, vestidor y baño completo con doble bacha. El segundo dormitorio posee placard con interiores, persianas y aire acondicionado frío/calor. Además, cuenta con un segundo baño completo.

Dependencia de servicio con baño y lavadero independiente.

La propiedad incluye cochera doble fija y cubierta con acceso por rampa.


cocheras en primer piso y baulera en subsuelo

Características destacadas:
* Palier privado
* Doble ingreso
* Orientación Este
* Balcón al frente
* Muy luminoso
* Aire acondicionado frío/calor
* Cocina a gas natural
* Cochera doble fija y cubierta
* Seguridad presencial 24 hs
* Encargado con vivienda

El edificio, de gran categoría y trayectoria en la zona, cuenta con 20 pisos distribuidos en cuerpos A y B, 2 ascensores principales y ascensor de servicio.

SUPERFICIE POR ESCRITURA
Cubierta: 152,55 m²
Semicubierta: 5,09 m²
Descubierta: 17,53 m²
TOTAL: 175,17 m²

SUPERFICIE REAL APROXIMADA
185 m² cubiertos + 12 m² descubiertos

Las medidas y superficies son aproximadas y surgirán del título de propiedad respectivo

In [ ]:
df_limpio = df_limpio.loc[df_limpio["ID"] != 583834].copy()

print("Departamentos restantes:", len(df_limpio))
print("Precio m² mínimo:", df_limpio["Precio_m2_Total"].min())

Departamentos restantes: 10308
Precio m² mínimo: 292.93

In [ ]:
precio_m2_calculado = (
    df_limpio["Precio_Valor"] / df_limpio["Superficie_Total_m2"]
)

diferencia = (
    df_limpio["Precio_m2_Total"] - precio_m2_calculado
).abs()

print("Diferencia máxima:", diferencia.max())
print("Casos con diferencia > 1 USD/m²:", (diferencia > 1).sum())

Diferencia máxima: 0.005000000000109139
Casos con diferencia > 1 USD/m²: 0

In [ ]:
df_limpio[
    ["Precio_Valor", "Superficie_Total_m2", "Superficie_Cubierta_m2"]
].describe(
    percentiles=[0.01, 0.05, 0.50, 0.95, 0.99]
)

       Precio_Valor  Superficie_Total_m2  Superficie_Cubierta_m2
count  1.030800e+04         10308.000000            10308.000000
mean   1.646387e+05            73.112516               63.604624
std    1.728897e+05            49.471326               40.073851
min    2.000000e+04            13.410000                0.000000
1%     3.950000e+04            22.000000               21.452100
5%     5.300000e+04            29.320500               27.167000
50%    1.200000e+05            59.940000               52.785000
95%    4.100000e+05           167.039000              139.413500
99%    8.200000e+05           264.929900              218.000000
max    6.300000e+06           726.000000              549.360000

In [ ]:
df_limpio.loc[
    df_limpio["Superficie_Cubierta_m2"] == 0,
    ["ID", "Titulo", "Barrio", "Superficie_Total_m2", "Superficie_Cubierta_m2"]
]

,ID,Titulo,Barrio,Superficie_Total_m2,Superficie_Cubierta_m2
5859,609401,DEPTO TIPO LOFT EN VTA RECICLADO A NUEVO LUMINOSO,Balvanera,37.87,0.0

In [ ]:
import numpy as np

df_limpio.loc[
    df_limpio["Superficie_Cubierta_m2"] == 0,
    "Superficie_Cubierta_m2"
] = np.nan

print("Superficies cubiertas en 0:",
      (df_limpio["Superficie_Cubierta_m2"] == 0).sum())

print("Superficies cubiertas faltantes:",
      df_limpio["Superficie_Cubierta_m2"].isna().sum())

Superficies cubiertas en 0: 0
Superficies cubiertas faltantes: 1

In [ ]:
print("Expensas faltantes:", df_limpio["Expensas"].isna().sum())
print("Expensas iguales a 0:", (df_limpio["Expensas"] == 0).sum())
print("Expensas negativas:", (df_limpio["Expensas"] < 0).sum())

df_limpio["Expensas"].describe(
    percentiles=[0.01, 0.05, 0.50, 0.95, 0.99]
)

Expensas faltantes: 0
Expensas iguales a 0: 1310
Expensas negativas: 0

count    1.030800e+04
mean     2.368402e+05
std      2.596071e+06
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
50%      1.680000e+05
95%      5.930000e+05
99%      1.000000e+06
max      2.628791e+08
Name: Expensas, dtype: float64

In [ ]:
df_limpio.nlargest(15, "Expensas")[
    [
        "ID", "Titulo", "Barrio",
        "Precio_Valor", "Moneda_Expensas", "Expensas"
    ]
]

,ID,Titulo,Barrio,Precio_Valor,Moneda_Expensas,Expensas
2308,629105,venta PH 2 ambientes terraza privada cochera,Palermo,209000.0,ARS,262879132.0
14701,517881,VISTA AL RIO 360! FULL AMENITIES,Palermo,1130000.0,ARS,2700000.0
2752,627062,Venta Triplex palermo alto Vista a jardines 7 amb,Palermo,2700000.0,ARS,2500000.0
3923,620516,Venta departamento 4 ambientes Palermo,Palermo,1100000.0,ARS,2500000.0
13980,535724,VENTA DEPTO EN DÚPLEX EN LIBERTADOR 336 DE 58...,Recoleta,2500000.0,ARS,2500000.0
14060,533502,Impresionante Triplex en la mejor zona de Reco...,Recoleta,1500000.0,ARS,2500000.0
14819,514320,"VENTA 3 AMB + Dep. C/ COCHERA en ""ALVEAR TOWER""",Puerto Madero,1000000.0,ARS,2500000.0
10770,575893,Recoleta - VENTA - Con cochera - FINANCIACION,Recoleta,1430000.0,ARS,2300000.0
406,637941,"Venta Penthouse 6 ambientes, piscina 3 cocheras",Belgrano,1980000.0,ARS,2200000.0
11066,572894,Departamento en venta edificio Kavanagh,Retiro,1380000.0,ARS,2110875.0
1289,633947,VENTA DUPLEX PISO ALTO CON TERRAZA PROPIA BELG...,Belgrano,629000.0,ARS,2100000.0
1940,630774,VENTA PISO 5 AMBIENTES C/3 COCHERAS EN BELGRANO C,Belgrano C,750000.0,ARS,2100000.0
6741,603957,EXCLUSIVO PISO DE CATEGORIA EN LA IMPRENTA,Las Cañitas,750000.0,ARS,2100000.0
2773,626991,"Depto.8 Amb.San Nicolas,315 m2,Divisibles,Premium",Centro / Microcentro,297000.0,ARS,2000000.0
8044,595704,VENTA PENTHOUSE BELGRANO 6 AMBIENTES + DEPENDE...,Belgrano,980000.0,ARS,2000000.0

In [ ]:
fila = df_limpio[df_limpio["ID"] == 629105].iloc[0]

print("Título:", fila["Titulo"])
print("Tipo:", fila["Tipo_Propiedad"])
print("Precio:", fila["Precio_Valor"])
print("Expensas:", fila["Expensas"])
print("\nDescripción:")
print(fila["Descripcion"])

Título: venta PH 2 ambientes terraza privada  cochera
Tipo: departamento_estandar
Precio: 209000.0
Expensas: 262879132.0

Descripción:
DEPARTAMENTO 2 AMBIENTES VENTA PALERMO VIEJO CAPITAL FEDERAL - APTO CRÉDITO

A dos cuadras de Plaza Serrano y toda la movida palermitana, rodeada de variado polo gastronómico, bares, shows , jazz, etc.

Un refugio urbano que respira libertad y estilo se despliega en el corazón de Palermo. Este departamento de 103 m² es una invitación a vivir la ciudad con intensidad, combinando espacios luminosos y funcionales que se adaptan perfectamente a tu ritmo de vida.

Construido en 2006, el inmueble ofrece una distribución inteligente que maximiza cada rincón. Con una orientación noroeste, recibe una luz natural generosa que transforma los ambientes en espacios cálidos y acogedores. El dormitorio principal, equipado con un amplio placard, garantiza confort y organización.

El living y el comedor fluyen naturalmente hacia tu balcón personal sobre la ciudad. Un desayunador integrado completa la zona social, ideal para disfrutar mañanas relajadas o recepciones íntimas.

La cochera incluida añade un valor diferencial, simplificando la logística urbana. El edificio cuenta con  portón automático, ascensor y rampa fija, pensadas para facilitar tu día a día.

Servicios completos como electricidad, gas, internet, televisión por cable y alarma convierten este departamento en una opción integral para quienes buscan comodidad sin renunciar a la ubicación premium de Palermo.

El PH/departamento cuenta con ascensor.

Se encuentra en el 2 piso.

Una inversión inteligente que combina funcionalidad, diseño y potencial de valorización en uno de los barrios más dinámicos de Buenos Aires.

In [ ]:
df_limpio.loc[
    df_limpio["ID"] == 629105,
    "Expensas"
] = np.nan

print("Expensas del registro 629105:",
      df_limpio.loc[df_limpio["ID"] == 629105, "Expensas"].iloc[0])

print("Expensas faltantes totales:",
      df_limpio["Expensas"].isna().sum())

Expensas del registro 629105: nan
Expensas faltantes totales: 1

In [ ]:
mask_expensas_0 = df_limpio["Expensas"] == 0

patron_sin_expensas = r"sin expensas|no paga expensas|no abona expensas"

mask_sin_expensas = (
    df_limpio["Titulo"].str.contains(
        patron_sin_expensas, case=False, na=False
    ) |
    df_limpio["Descripcion"].str.contains(
        patron_sin_expensas, case=False, na=False
    )
)

print("Expensas = 0:", mask_expensas_0.sum())
print(
    "Expensas = 0 y texto indica que no paga:",
    (mask_expensas_0 & mask_sin_expensas).sum()
)
print(
    "Expensas = 0 sin aclaración:",
    (mask_expensas_0 & ~mask_sin_expensas).sum()
)

Expensas = 0: 1310
Expensas = 0 y texto indica que no paga: 46
Expensas = 0 sin aclaración: 1264

In [ ]:
df_limpio.loc[
    mask_expensas_0 & ~mask_sin_expensas,
    ["ID", "Titulo", "Descripcion", "Tipo_Propiedad", "Barrio", "Expensas"]
].sample(15, random_state=42)

,ID,Titulo,Descripcion,Tipo_Propiedad,Barrio,Expensas
16705,308183,DEPARTAMENTO 4 AMBIENTES VENTA FLORES TERRAZA,VENTA DEPARTAMENTO 4 AMBIENTES A ESTRENAR CON ...,departamento_estandar,Flores,0.0
13300,546624,"2 amb a estrenar con balcón Full amenities, Fl...",2 ambientes a estrenar con balcón | Flores\n\n...,departamento_estandar,Flores,0.0
7750,597725,VENTA DPTO 4 AMB EN PARQUE CHACABUCO,Departamento de 4 ambientes en venta\n\n- 85 m...,departamento_estandar,Parque Chacabuco,0.0
5569,611011,Depto 2 ambientes Sta Rita - ENTREGA DICIEMBRE 26,\nOportunidad - Departamento 2 ambientes Villa...,departamento_estandar,Villa Santa Rita,0.0
6151,607417,VENTA DEPARTAMENTO MONOAMBIENTE EN PALERMO SOHO,MONOAMBIENTE EN PISO ALTO CON VISTA ABIERTA – ...,departamento_monoambiente,Palermo Soho,0.0
13137,549096,Venta 3 Ambientes APTO CREDITO San Telmo,En el Edificio Pura Vida San Telmo ubicado sob...,departamento_estandar,San Telmo,0.0
290,638454,Venta Dpto Caballito 3 amb dep frente luz y aire,Luminoso departamento de 3 ambientes con depen...,departamento_estandar,Caballito,0.0
13299,546626,3 amb estrenar con balcón. Cochera Full amenities,3 ambientes a estrenar con balcón\n\nSobre Av...,departamento_estandar,Flores,0.0
437,637808,DEPARTAMENTO 2 AMB VENTA URQUIZA FINANC AMENITIES,Departamento de 2 ambientes en venta en Villa ...,departamento_estandar,Villa Urquiza,0.0
13100,549649,Venta Monoambiente a estrenar full amen Belgrano,"Te presentamos LOT BELGRANO, un proyecto de ca...",departamento_monoambiente,Belgrano,0.0
15573,483757,MilAires Venta Dpto 3 amb V.Devoto Full Amenities,DEPARTAMENTO 3 AMBIENTES EN VENTA- BALCON CON ...,departamento_estandar,Villa Devoto,0.0
5572,611007,Depto Monoambiente Sta Rita - ENTREGA DICIEMBR...,\nOportunidad - Departamento monoambiente Vill...,departamento_monoambiente,Villa Santa Rita,0.0
6944,602879,VENTA HERMOSO PISO DE 3 AMB EN VILLA DEL PARQUE,DEPARTAMENTO 3 AMBIENTES EN VENTA EN VILLA DEL...,departamento_piso,Villa del Parque,0.0
7711,597960,Venta Dpto 2 Amb. Balcón. Palermo Hollywood,Departamento 2 ambientes al frente súper lumin...,departamento_estandar,Palermo Hollywood,0.0
15746,471117,Departamento venta 3 ambientes apto profesional,DEPARTAMENTO 3 AMBIENTES EN VENTA CORDOBA Y CA...,departamento_estandar,Balvanera,0.0

In [ ]:
mask_cero_no_confirmado = (
    (df_limpio["Expensas"] == 0) &
    (~mask_sin_expensas)
)

df_limpio.loc[mask_cero_no_confirmado, "Expensas"] = np.nan

print("Expensas = 0 confirmadas:", (df_limpio["Expensas"] == 0).sum())
print("Expensas faltantes:", df_limpio["Expensas"].isna().sum())

Expensas = 0 confirmadas: 46
Expensas faltantes: 1265

In [ ]:
print("Precio m² cubierto faltante:",
      df_limpio["Precio_m2_Cubierto"].isna().sum())

df_limpio["Precio_m2_Cubierto"].describe(
    percentiles=[0.01, 0.05, 0.50, 0.95, 0.99]
)

Precio m² cubierto faltante: 1

count    10307.000000
mean      2518.779565
std       1022.928632
min        302.080000
1%         877.358600
5%        1250.000000
50%       2357.140000
95%       4333.330000
99%       5888.722600
max      18367.350000
Name: Precio_m2_Cubierto, dtype: float64

In [ ]:
precio_m2_cub_calculado = (
    df_limpio["Precio_Valor"] / df_limpio["Superficie_Cubierta_m2"]
)

diferencia_cub = (
    df_limpio["Precio_m2_Cubierto"] - precio_m2_cub_calculado
).abs()

print("Diferencia máxima:", diferencia_cub.max())
print("Casos con diferencia > 1 USD/m²:", (diferencia_cub > 1).sum())

Diferencia máxima: 0.005000000000109139
Casos con diferencia > 1 USD/m²: 0

In [ ]:
df_limpio[
    ["Ambientes", "Dormitorios", "Baños"]
].describe()

          Ambientes   Dormitorios         Baños
count  10308.000000  10308.000000  10308.000000
mean       2.653376      1.685487      1.270470
std        1.168642      1.050041      0.581725
min        1.000000      0.000000      1.000000
25%        2.000000      1.000000      1.000000
50%        3.000000      2.000000      1.000000
75%        3.000000      2.000000      1.000000
max       12.000000      9.000000      7.000000

In [ ]:
df_limpio.nlargest(15, "Ambientes")[
    [
        "ID", "Titulo", "Barrio",
        "Ambientes", "Dormitorios", "Baños",
        "Superficie_Total_m2", "Precio_Valor"
    ]
]

,ID,Titulo,Barrio,Ambientes,Dormitorios,Baños,Superficie_Total_m2,Precio_Valor
7709,597976,"VENTA Depto. 12 Amb. C/ PISCINA PRIVADA ""RETIRO""",Retiro,12,8,4,592.00,990000.0
10461,578781,"VENTA Depto. 12 Amb. C/ PISCINA PRIVADA ""RETIRO""",Retiro,12,8,4,592.00,990000.0
13980,535724,VENTA DEPTO EN DÚPLEX EN LIBERTADOR 336 DE 58...,Recoleta,12,7,7,587.39,2500000.0
1303,633846,VENTA PISO 10 AMB. BALVANERA. APTO HOSTEL,Balvanera,10,8,4,161.00,145000.0
14982,510214,Piso Premium en Avenida Quintana y Ayacucho.,Recoleta,10,5,4,309.00,1190000.0
14989,510075,VENTA 7 Deptos en Block Congreso Renta 10% Anual,San Nicolás,10,8,7,395.00,360000.0
4985,614451,Venta DUPLEX SIN EXP Cochera CABALLLITO,Caballito,9,6,3,300.00,450000.0
14665,518660,Venta – Exclusivo Departamento Ateneo Splendid,Recoleta,9,6,2,400.00,1100000.0
750,636310,DEPTO 6 AMB VENTA SAN NICOLAS,San Nicolás,8,3,1,211.00,378000.0
1518,632894,VENTA DEPARTAMENTO 6 AMBIENTES BELGRANO,Palermo,8,5,7,512.00,1200000.0
2752,627062,Venta Triplex palermo alto Vista a jardines 7 amb,Palermo,8,4,4,450.00,2700000.0
2773,626991,"Depto.8 Amb.San Nicolas,315 m2,Divisibles,Premium",Centro / Microcentro,8,7,7,315.00,297000.0
4061,619747,DUPLEX APTO VIVIENDA MEJOR VISTA DE CABA 2COCH...,Palermo,8,5,3,246.51,419000.0
5380,612020,DEPARTAMENTO 8 AMBIENTES MONSERRAT APTO CRÉDITO,Monserrat,8,7,5,202.00,310000.0
6521,605231,VENTA DEPTO 8 AMB BALVANERA BALCON CON PARRILLA,Balvanera,8,5,5,421.00,830000.0

In [ ]:
cols_dup = [
    "Titulo",
    "Barrio",
    "Precio_Valor",
    "Superficie_Total_m2",
    "Ambientes",
    "Dormitorios",
    "Baños"
]

duplicados_propiedad = df_limpio[
    df_limpio.duplicated(subset=cols_dup, keep=False)
].sort_values(cols_dup)

print("Registros involucrados en posibles duplicados:",
      len(duplicados_propiedad))

duplicados_propiedad[
    ["ID", "Titulo", "Barrio", "Precio_Valor",
     "Superficie_Total_m2", "Ambientes", "Dormitorios", "Baños"]
].head(30)

Registros involucrados en posibles duplicados: 98

,ID,Titulo,Barrio,Precio_Valor,Superficie_Total_m2,Ambientes,Dormitorios,Baños
16482,383517,-Departamento 2 AMBIENTES EN FLORESTA,Floresta,54000.0,36.00,2,1,1
16612,350785,-Departamento 2 AMBIENTES EN FLORESTA,Floresta,54000.0,36.00,2,1,1
729,636426,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Colegiales,125000.0,71.00,3,2,1
2607,627673,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Colegiales,125000.0,71.00,3,2,1
3789,621481,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Chacarita,171000.0,58.89,3,2,1
14949,511087,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Chacarita,171000.0,58.89,3,2,1
1961,630674,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Belgrano,59000.0,28.00,1,1,1
13198,548224,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Belgrano,59000.0,28.00,1,1,1
15365,495679,DEPARTAMENTO 3 AMBIENTES VENTA PATERNAL PISO ALTO,La Paternal,169900.0,74.20,3,2,1
16580,361997,DEPARTAMENTO 3 AMBIENTES VENTA PATERNAL PISO ALTO,La Paternal,169900.0,74.20,3,2,1
2795,626898,DEPARTAMENTO 3AMB SAN CRISTOBAL TERRAZA Y PARR...,San Cristobal,123000.0,83.25,3,3,2
16436,392883,DEPARTAMENTO 3AMB SAN CRISTOBAL TERRAZA Y PARR...,San Cristobal,123000.0,83.25,3,3,2
5049,614086,DEPARTAMENTO VENTA SAN NICOLAS MONOAMBIENTE,San Nicolás,38000.0,22.00,1,0,1
15597,481924,DEPARTAMENTO VENTA SAN NICOLAS MONOAMBIENTE,San Nicolás,38000.0,22.00,1,0,1
14259,529319,DEPTO 3 AMB VENTA MATADEROS BALCÓN OPC/COCHERA,Mataderos,147900.0,52.39,3,2,1
15653,478496,DEPTO 3 AMB VENTA MATADEROS BALCÓN OPC/COCHERA,Mataderos,147900.0,52.39,3,2,1
3861,620922,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Colegiales,184900.0,71.00,4,3,1
8932,590102,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Colegiales,184900.0,71.00,4,3,1
9300,587805,Departamento en VENTA 2 Ambientes VILLA SANTA ...,Villa Santa Rita,99900.0,51.00,2,1,1
11594,567789,Departamento en VENTA 2 Ambientes VILLA SANTA ...,Villa Santa Rita,99900.0,51.00,2,1,1
13090,549805,Departamento en VENTA 2 Ambientes VILLA SANTA ...,Villa Santa Rita,99900.0,51.00,2,1,1
458,637745,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Flores,70000.0,54.00,3,3,1
5173,613162,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Flores,70000.0,54.00,3,3,1
11107,572502,Dpto semipiso 4 ambientes con financiación FLORES,Flores,237000.0,92.00,4,3,2
11108,572501,Dpto semipiso 4 ambientes con financiación FLORES,Flores,237000.0,92.00,4,3,2
8301,594013,Mono apto prof vivienda Recoleta. Ideal inversion,Recoleta,40000.0,25.00,1,0,1
8303,594009,Mono apto prof vivienda Recoleta. Ideal inversion,Recoleta,40000.0,25.00,1,0,1
15450,491274,Monoambiente con balcón a estrenar,Saavedra,86000.0,36.00,1,1,1
15492,488626,Monoambiente con balcón a estrenar,Saavedra,86000.0,36.00,1,1,1
6483,605603,Monoambiente venta Belgrano,Belgrano,99104.0,30.97,1,0,1

In [ ]:
duplicados_propiedad[
    [
        "ID", "ID_Entidad", "Titulo", "Direccion", "Barrio",
        "Latitud", "Longitud", "Precio_Valor",
        "Superficie_Total_m2", "Ambientes",
        "Dormitorios", "Baños"
    ]
].head(30)

,ID,ID_Entidad,Titulo,Direccion,Barrio,Latitud,Longitud,Precio_Valor,Superficie_Total_m2,Ambientes,Dormitorios,Baños
16482,383517,5e1e88ae-b37a-4897-987b-b7a471327ec3,-Departamento 2 AMBIENTES EN FLORESTA,San Nicolas 400,Floresta,-36.297418,-55.711670,54000.0,36.00,2,1,1
16612,350785,96ce01ed-f96d-4c50-add7-a282ae815495,-Departamento 2 AMBIENTES EN FLORESTA,San Nicolas 400,Floresta,-36.297418,-55.711670,54000.0,36.00,2,1,1
729,636426,57c92253-161b-42d9-ab27-3e79a692eb92,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Delgado 800,Colegiales,-34.578477,-58.453562,125000.0,71.00,3,2,1
2607,627673,8627a3c3-42e8-434c-af55-a380be12a61b,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Delgado 800,Colegiales,-34.578477,-58.453562,125000.0,71.00,3,2,1
3789,621481,9a2809d7-c63c-45f8-8559-80a61ee474ef,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Charlone 900,Chacarita,-34.580805,-58.457542,171000.0,58.89,3,2,1
14949,511087,aee6edbf-671c-491e-938b-2e3f3ad6fde1,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Charlone 900,Chacarita,-34.580805,-58.457542,171000.0,58.89,3,2,1
1961,630674,633ae04c-61d5-47d2-859b-988b77b652d6,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Olleros 1700,Belgrano,-34.566251,-58.440033,59000.0,28.00,1,1,1
13198,548224,d3f4bce9-a8c6-4427-9861-646472cc3336,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Olleros 1700,Belgrano,-34.566251,-58.440033,59000.0,28.00,1,1,1
15365,495679,62653987-d9d8-48ab-a1d0-5ef57213acc9,DEPARTAMENTO 3 AMBIENTES VENTA PATERNAL PISO ALTO,Avenida San Martín 2900,La Paternal,-34.602166,-58.466702,169900.0,74.20,3,2,1
16580,361997,b487d305-0042-468f-8c75-a5710f28e96d,DEPARTAMENTO 3 AMBIENTES VENTA PATERNAL PISO ALTO,Avenida San Martín 2900,La Paternal,-34.602166,-58.466702,169900.0,74.20,3,2,1
2795,626898,a21335b4-9d96-49bd-a7d5-4ac14bc08873,DEPARTAMENTO 3AMB SAN CRISTOBAL TERRAZA Y PARR...,Avenida Independencia 2300,San Cristobal,-34.618406,-58.399118,123000.0,83.25,3,3,2
16436,392883,41178d11-85fd-4235-9aeb-f5cd9050cfab,DEPARTAMENTO 3AMB SAN CRISTOBAL TERRAZA Y PARR...,Avenida Independencia 2300,San Cristobal,-34.618406,-58.399118,123000.0,83.25,3,3,2
5049,614086,771fae7c-c028-4fef-b3f4-34e2b96c9f96,DEPARTAMENTO VENTA SAN NICOLAS MONOAMBIENTE,Sarmiento 1200,San Nicolás,-34.605094,-58.384798,38000.0,22.00,1,0,1
15597,481924,e3397803-1e1d-49a5-8638-a655deb8c490,DEPARTAMENTO VENTA SAN NICOLAS MONOAMBIENTE,Sarmiento 1200,San Nicolás,-34.605094,-58.384798,38000.0,22.00,1,0,1
14259,529319,d306daf0-609f-4e2f-beed-8d0ee0171c1c,DEPTO 3 AMB VENTA MATADEROS BALCÓN OPC/COCHERA,Pola 1100,Mataderos,-34.648818,-58.501548,147900.0,52.39,3,2,1
15653,478496,f9026a26-a5b7-4080-977c-7edf7044a220,DEPTO 3 AMB VENTA MATADEROS BALCÓN OPC/COCHERA,Pola 1100,Mataderos,-34.649069,-58.501630,147900.0,52.39,3,2,1
3861,620922,8fc36f69-fcbe-4d7d-afbb-8e76e0725e52,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Concepción Arenal 3300,Colegiales,-34.581809,-58.446030,184900.0,71.00,4,3,1
8932,590102,7a926ef2-6a14-46d8-b59f-67874b0a01bc,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Concepción Arenal 3300,Colegiales,-34.581809,-58.446030,184900.0,71.00,4,3,1
9300,587805,c3173183-fced-413c-980b-d31e5bbe0e45,Departamento en VENTA 2 Ambientes VILLA SANTA ...,San Blas 3000,Villa Santa Rita,-34.612309,-58.483404,99900.0,51.00,2,1,1
11594,567789,a7bcd3c5-b0c3-4164-a0c7-3b626c8913f9,Departamento en VENTA 2 Ambientes VILLA SANTA ...,San Blas 3000,Villa Santa Rita,-34.612309,-58.483404,99900.0,51.00,2,1,1
13090,549805,d27af71e-0f48-465f-b4f1-68de32d133c0,Departamento en VENTA 2 Ambientes VILLA SANTA ...,San Blas 3000,Villa Santa Rita,-34.612309,-58.483404,99900.0,51.00,2,1,1
458,637745,e4aea895-0b23-4708-acde-f5125abdb05b,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Condarco 1000,Flores,-34.619429,-58.471656,70000.0,54.00,3,3,1
5173,613162,2648caeb-f3d4-461b-9cfd-29a17d196741,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Condarco 1000,Flores,-34.619429,-58.471656,70000.0,54.00,3,3,1
11107,572502,4d36f47b-b285-49c6-8171-bd0050728004,Dpto semipiso 4 ambientes con financiación FLORES,Av San Pedrito 300,Flores,-34.635110,-58.467811,237000.0,92.00,4,3,2
11108,572501,bc8a68b8-3b71-4135-87da-0423de225f2b,Dpto semipiso 4 ambientes con financiación FLORES,Avenida San Pedrito 300,Flores,-34.635078,-58.467856,237000.0,92.00,4,3,2
8301,594013,52d2ab67-0b78-4208-9f76-34dcc7377dec,Mono apto prof vivienda Recoleta. Ideal inversion,Rodríguez Peña 600,Recoleta,-34.601655,-58.391186,40000.0,25.00,1,0,1
8303,594009,6669e16d-992d-47bb-8c62-48893c77aae0,Mono apto prof vivienda Recoleta. Ideal inversion,Rodríguez Peña 600,Recoleta,-34.601655,-58.391186,40000.0,25.00,1,0,1
15450,491274,49319eb1-566a-4408-9404-74de532632b5,Monoambiente con balcón a estrenar,Nuñez 3900,Saavedra,-34.557660,-58.481173,86000.0,36.00,1,1,1
15492,488626,3269454c-c9c3-4277-b3e9-f59f96b225a2,Monoambiente con balcón a estrenar,Nuñez 3900,Saavedra,-34.557660,-58.481173,86000.0,36.00,1,1,1
6483,605603,4f9ac882-7399-4cba-8c5a-0c987758fcb4,Monoambiente venta Belgrano,Mendoza 2100,Belgrano,-34.559634,-58.454925,99104.0,30.97,1,0,1

In [ ]:
cols_dup_estricto = [
    "Titulo",
    "Descripcion",
    "Direccion",
    "Barrio",
    "Precio_Valor",
    "Superficie_Total_m2",
    "Ambientes",
    "Dormitorios",
    "Baños"
]

dup_estrictos = df_limpio.duplicated(
    subset=cols_dup_estricto,
    keep=False
)

print("Registros involucrados en duplicados estrictos:", dup_estrictos.sum())

df_limpio.loc[
    dup_estrictos,
    ["ID", "Titulo", "Direccion", "Barrio", "Precio_Valor", "Superficie_Total_m2"]
].sort_values(["Titulo", "Direccion"]).head(30)

Registros involucrados en duplicados estrictos: 58

,ID,Titulo,Direccion,Barrio,Precio_Valor,Superficie_Total_m2
729,636426,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Delgado 800,Colegiales,125000.0,71.00
2607,627673,3 AMBIENTES CON DEPENDENCIA VENTA COLEGIALES ...,Delgado 800,Colegiales,125000.0,71.00
3789,621481,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Charlone 900,Chacarita,171000.0,58.89
14949,511087,A ESTRENAR DEPARTAMENTO 3 AMBIENTES CON BALCON,Charlone 900,Chacarita,171000.0,58.89
1961,630674,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Olleros 1700,Belgrano,59000.0,28.00
13198,548224,DEPARTAMENTO 2 AMBIENTES A REFACCIONAR OPORTUN...,Olleros 1700,Belgrano,59000.0,28.00
3861,620922,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Concepción Arenal 3300,Colegiales,184900.0,71.00
8932,590102,DEPTO BARRIO COLEGIALES 4 AMBIENTES EN VENTA,Concepción Arenal 3300,Colegiales,184900.0,71.00
9300,587805,Departamento en VENTA 2 Ambientes VILLA SANTA ...,San Blas 3000,Villa Santa Rita,99900.0,51.00
11594,567789,Departamento en VENTA 2 Ambientes VILLA SANTA ...,San Blas 3000,Villa Santa Rita,99900.0,51.00
458,637745,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Condarco 1000,Flores,70000.0,54.00
5173,613162,Depto. 3 ambientes en Villa Santa Rita A REMOD...,Condarco 1000,Flores,70000.0,54.00
8301,594013,Mono apto prof vivienda Recoleta. Ideal inversion,Rodríguez Peña 600,Recoleta,40000.0,25.00
8303,594009,Mono apto prof vivienda Recoleta. Ideal inversion,Rodríguez Peña 600,Recoleta,40000.0,25.00
1962,630673,OPORTUNIDAD HERMOSO 2 AMBIENTES EN SAAVEDRA,Mariano Acha 3800,Saavedra,103000.0,44.13
13842,536869,OPORTUNIDAD HERMOSO 2 AMBIENTES EN SAAVEDRA,Mariano Acha 3800,Saavedra,103000.0,44.13
16481,383520,OPORTUNIDAD UNICA DOS AMB VILLA MITRE LUMINOSO,Avenida Boyacá 1900,Villa General Mitre,57000.0,33.00
16673,324954,OPORTUNIDAD UNICA DOS AMB VILLA MITRE LUMINOSO,Avenida Boyacá 1900,Villa General Mitre,57000.0,33.00
6097,607680,VENTA 5 AMB COCHERA TERRAZA DEPENDENCIA ESCRIT...,Zapata 100,Colegiales,380000.0,173.14
7484,599591,VENTA 5 AMB COCHERA TERRAZA DEPENDENCIA ESCRIT...,Zapata 100,Colegiales,380000.0,173.14
3919,620550,VENTA BELGRANO SEMIP 4 AMB FTE COCH APT CRED/PRO,Aguilar 2500,Colegiales,295000.0,105.00
9349,587453,VENTA BELGRANO SEMIP 4 AMB FTE COCH APT CRED/PRO,Aguilar 2500,Colegiales,295000.0,105.00
3168,624890,VENTA DEPARTAMENTO 3 AMBIENTES CON BALCÓN,Gurruchaga 2100,Palermo,159900.0,74.33
7770,597588,VENTA DEPARTAMENTO 3 AMBIENTES CON BALCÓN,Gurruchaga 2100,Palermo,159900.0,74.33
410,637915,VENTA DEPARTAMENTO 3 AMBIENTES NUÑEZ,Nuñez 2300,Nuñez,194999.0,76.80
7598,598798,VENTA DEPARTAMENTO 3 AMBIENTES NUÑEZ,Nuñez 2300,Nuñez,194999.0,76.80
9107,589073,VENTA DEPTO 3 AMB CON BALC. V. CRESPO APTO CRE...,Avenida Cordoba 4600,Villa Crespo,153000.0,65.00
15846,463805,VENTA DEPTO 3 AMB CON BALC. V. CRESPO APTO CRE...,Avenida Cordoba 4600,Villa Crespo,153000.0,65.00
7959,596211,VENTA DEPTO 3 AMBIENTES + DEPENDENCIA COLEGIALES,Ciudad de la Paz 800,Colegiales,172000.0,80.59
12169,561216,VENTA DEPTO 3 AMBIENTES + DEPENDENCIA COLEGIALES,Ciudad de la Paz 800,Colegiales,172000.0,80.59

In [ ]:
n_antes = len(df_limpio)

df_limpio = df_limpio.drop_duplicates(
    subset=cols_dup_estricto,
    keep="first"
).copy()

print("Registros antes:", n_antes)
print("Registros después:", len(df_limpio))
print("Duplicados eliminados:", n_antes - len(df_limpio))

Registros antes: 10308
Registros después: 10279
Duplicados eliminados: 29

In [ ]:
print("Cantidad de barrios distintos:", df_limpio["Barrio"].nunique())
print("Barrios faltantes:", df_limpio["Barrio"].isna().sum())

df_limpio["Barrio"].value_counts(dropna=False)

Cantidad de barrios distintos: 75
Barrios faltantes: 1

Barrio
Palermo                  861
Caballito                805
Recoleta                 616
Balvanera                594
Almagro                  565
Belgrano                 515
Flores                   452
Villa Urquiza            371
Villa Crespo             345
Nuñez                    329
San Nicolás              276
Monserrat                259
San Cristobal            241
Villa del Parque         233
Villa Devoto             223
Colegiales               206
Saavedra                 186
Retiro                   168
San Telmo                167
Boedo                    146
Parque Chacabuco         145
Villa Ortuzar            122
Barrio Norte             118
Barracas                 118
Floresta                 108
Monte Castro             106
Constitución             105
Villa Lugano              97
Villa Luro                95
Chacarita                 95
Palermo Hollywood         94
Las Cañitas               93
Parque Patricios          87
Liniers                   86
Villa Santa Rita          78
Villa General Mitre       77
Mataderos                 75
Caballito Sur             75
Coghlan                   70
Villa Pueyrredón          68
Parque Chas               64
Belgrano R                62
Palermo Soho              56
Palermo Chico             56
Puerto Madero             56
La Paternal               49
La Boca                   46
Velez Sarsfield           41
Caballito Norte           37
Parque Avellaneda         34
Nueva Pompeya             34
Botánico                  31
Centro / Microcentro      25
Barrancas de Belgrano     23
Congreso                  20
Belgrano C                18
Versalles                 18
Barrio Samore             15
Palermo Nuevo             15
Villa Soldati             14
Agronomía                 13
Bajo Belgrano             11
Plaza San Martín          10
Once                      10
Palermo Viejo              9
Abasto                     7
Parque Centenario          6
Villa Real                 6
Villa Riachuelo            5
Belgrano Chico             4
Barrio River               4
Cid Campeador              3
Naón                       2
Catalinas Norte            2
Barrio Chino               2
NaN                        1
Name: count, dtype: int64

In [ ]:
barrios = (
    df_limpio["Barrio"]
    .value_counts(dropna=False)
    .rename_axis("Barrio")
    .reset_index(name="Cantidad")
)

pd.set_option("display.max_rows", None)
barrios

                   Barrio  Cantidad
0                 Palermo       861
1               Caballito       805
2                Recoleta       616
3               Balvanera       594
4                 Almagro       565
5                Belgrano       515
6                  Flores       452
7           Villa Urquiza       371
8            Villa Crespo       345
9                   Nuñez       329
10            San Nicolás       276
11              Monserrat       259
12          San Cristobal       241
13       Villa del Parque       233
14           Villa Devoto       223
15             Colegiales       206
16               Saavedra       186
17                 Retiro       168
18              San Telmo       167
19                  Boedo       146
20       Parque Chacabuco       145
21          Villa Ortuzar       122
22           Barrio Norte       118
23               Barracas       118
24               Floresta       108
25           Monte Castro       106
26           Constitución       105
27           Villa Lugano        97
28             Villa Luro        95
29              Chacarita        95
30      Palermo Hollywood        94
31            Las Cañitas        93
32       Parque Patricios        87
33                Liniers        86
34       Villa Santa Rita        78
35    Villa General Mitre        77
36              Mataderos        75
37          Caballito Sur        75
38                Coghlan        70
39       Villa Pueyrredón        68
40            Parque Chas        64
41             Belgrano R        62
42           Palermo Soho        56
43          Palermo Chico        56
44          Puerto Madero        56
45            La Paternal        49
46                La Boca        46
47        Velez Sarsfield        41
48        Caballito Norte        37
49      Parque Avellaneda        34
50          Nueva Pompeya        34
51               Botánico        31
52   Centro / Microcentro        25
53  Barrancas de Belgrano        23
54               Congreso        20
55             Belgrano C        18
56              Versalles        18
57          Barrio Samore        15
58          Palermo Nuevo        15
59          Villa Soldati        14
60              Agronomía        13
61          Bajo Belgrano        11
62       Plaza San Martín        10
63                   Once        10
64          Palermo Viejo         9
65                 Abasto         7
66      Parque Centenario         6
67             Villa Real         6
68        Villa Riachuelo         5
69         Belgrano Chico         4
70           Barrio River         4
71          Cid Campeador         3
72                   Naón         2
73        Catalinas Norte         2
74           Barrio Chino         2
75                    NaN         1

In [ ]:
print("Antigüedad faltante:", df_limpio["Antiguedad"].isna().sum())

df_limpio["Antiguedad"].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

Antigüedad faltante: 60

count    10219.000000
mean        35.363636
std         24.458934
min          0.000000
1%           0.000000
5%           1.000000
25%         10.000000
50%         41.000000
75%         55.000000
95%         70.000000
99%         91.000000
max        190.000000
Name: Antiguedad, dtype: float64

In [ ]:
df_limpio.nlargest(15, "Antiguedad")[
    [
        "ID", "Titulo", "Barrio",
        "Antiguedad", "Superficie_Total_m2",
        "Precio_Valor"
    ]
]

,ID,Titulo,Barrio,Antiguedad,Superficie_Total_m2,Precio_Valor
6679,604302,Departamento a refaccionar Microcentro,San Nicolás,190.0,68.90,70000.0
14039,534034,VENTA 2 AMB con OPCIÓN A 3 | 94 m² | CON BALCÓN,Constitución,137.0,94.44,67000.0
13640,540433,Venta excelente Piso 4 amb en Avenida Santa Fe,Recoleta,135.0,89.00,220000.0
1159,634512,Venta 5 ambientes de categoría edificio histórico,Monserrat,131.0,138.00,215000.0
16433,393213,VENTA SAN TELMO 4 amb COCHERA EDIFICIO DODERO,San Telmo,126.0,130.00,297500.0
1357,633592,VENTA DEPTO 3 AMB BARRACAS CON TERRAZA,Barracas,121.0,58.10,50000.0
4131,619332,VENTA DEPARTAMENTO UNICO EN RETIRO,San Nicolás,120.0,120.30,320000.0
14148,531661,Gran Ubicación! Dos Ambientes en Plaza Armenia.,Palermo,120.0,34.30,110000.0
2855,626599,Venta Depto 5 amb Edif Estilo Frances San Telmo,San Telmo,119.0,200.00,230000.0
4577,616552,VENTA DEPTO 150M2 5 AMB- 3 DORM CON DEP - CONG...,Balvanera,117.0,150.04,225000.0
12472,557453,CONGRESO: VENTA DEPTO 5 AMBIENTES+DEP EDIF EMB...,Balvanera,117.0,161.56,220000.0
13646,540366,CONGRESO VENTA DEPTO P.B. 6 AMB+2 PATIOS EDIF ...,Balvanera,117.0,194.65,240000.0
4114,619437,VENTA MONOAMBIENTE MICROCENTRO RECICLADO 31 M,San Nicolás,116.0,30.59,65000.0
7667,598310,VENTA 5 AMB S/PISO EDIFICIO HISTORICO AV DE MAYO,Monserrat,116.0,183.00,239000.0
9105,589087,VENTA DE DEPARTAMENTO 2 AMBIENTES/MONSERRAT,Monserrat,116.0,49.00,69500.0

In [ ]:
fila = df_limpio[df_limpio["ID"] == 604302].iloc[0]

print("Título:", fila["Titulo"])
print("Dirección:", fila["Direccion"])
print("Barrio:", fila["Barrio"])
print("Antigüedad:", fila["Antiguedad"])
print("\nDescripción:")
print(fila["Descripcion"])

Título: Departamento a refaccionar  Microcentro
Dirección: Maipú 300
Barrio: San Nicolás
Antigüedad: 190.0

Descripción:
Excelente oportunidad para reciclar en una de las zonas más representativas del Microcentro porteño: Maipú y Corrientes, dentro de un edificio de valor patrimonial declarado Sitio de Interés Cultural / Patrimonio Histórico.
Se trata de una unidad de 3 ambientes, originalmente ex oficina, actualmente solo eléctrica, con gran potencial para reconversión y puesta en valor. Su distribución, la impronta del edificio y sus elementos originales la convierten en una propuesta ideal para quienes buscan desarrollar un proyecto con identidad propia, ya sea para vivienda, estudio o inversión. Muy luminoso dado que es un piso alto
La propiedad se encuentra a refaccionar. Presenta pisos de pinotea deteriorados,  caños y cables  y carpinterías antiguas sin fallebas, aspectos a considerar dentro de una renovación integral. Justamente allí reside gran parte de su atractivo: la posibilidad de recuperar una propiedad con historia y transformarla en un espacio único, en una ubicación de altísima conectividad y valor urbano. (en las ultimas fotos se sugieren opciones para remodelar algunos espacios)
No apto mascotas

In [ ]:
print("Apto_Credito faltantes:",
      df_limpio["Apto_Credito"].isna().sum())

df_limpio["Apto_Credito"].value_counts(dropna=False)

Apto_Credito faltantes: 59

Apto_Credito
False    5697
True     4523
NaN        59
Name: count, dtype: int64

In [ ]:
df_limpio["Apto_Credito"] = df_limpio["Apto_Credito"].astype("boolean")

print(df_limpio["Apto_Credito"].dtype)
print()
print(df_limpio["Apto_Credito"].value_counts(dropna=False))

boolean

Apto_Credito
False    5697
True     4523
<NA>       59
Name: count, dtype: Int64

In [ ]:
print("Amenities faltantes:", df_limpio["Amenities"].isna().sum())
print("Amenities no faltantes:", df_limpio["Amenities"].notna().sum())

df_limpio.loc[
    df_limpio["Amenities"].notna(),
    ["ID", "Titulo", "Amenities"]
].head(15)

Amenities faltantes: 1860
Amenities no faltantes: 8419

,ID,Titulo,Amenities
1,639767,Venta Depto. 2 Ambientes Balcón en Nuñez,Electricidad | Agua | Internet | Aire Acondici...
2,639766,Venta Depto. 2 Amb. balcón a estrenar en Nuñez,Aire Acondicionado | Seguridad | Pileta | Saló...
15,639702,VENTA DEPTO 2 AMB CON COCHERA CUBIERTA,Dormitorio | Baño | Cocina | Placard | Living/...
17,639699,2 ambientes con patio en Av Cordoba - OPORTUNIDAD,Patio
19,639693,VENTA DEPARTAMENTO 2 AMB A ESTRENAR BALVANERA,Electricidad | Gas | Agua Corriente | Aire Aco...
21,639681,VENTA DEPARTAMENTO 3 AMBIENTES BELGRANO,Electricidad | Agua | Gas | Internet | Desague...
25,639666,Departamento 4 amb en Venta en Villa Urquiza,Electricidad | Gas | Agua Corriente | Aire Aco...
26,639665,VENTA DEPARTAMENTO 3 AMB A ESTRENAR VILLA URQUIZA,Electricidad | Gas | Agua Corriente | Aire Aco...
29,639660,"Venta Monoambiente Loft 62 mts Chacarita, balcón",Electricidad | Agua Corriente | Laundry | Asce...
30,639658,Venta Departamento Monoambiente Villa Urquiza,Electricidad | Agua | Gas | Agua Corriente | A...
32,639655,Departamento en venta Villa del parque 2 ambie...,Dormitorio | Baño | Cocina | Living | Balcón
34,639653,VENTA DEPARTAMENTO 3 AMBIENTES VILLA URQUIZA,Dormitorio | Baño | Cocina | Placard | Living/...
35,639645,DEPARTAMENTO 3 AMBIENTES EN CENTA,Ascensor | Dormitorio | Comedor | Vestidor | B...
36,639641,"Depto de 2 ambientes, depend, baul y balcon vista",Dormitorio | Comedor | Baño | Cocina | Living ...
37,639638,Departamento 3 ambientes Balvanera apto credito,Electricidad | Gas | Internet | Agua Corriente...

In [ ]:
amenities_separados = (
    df_limpio["Amenities"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

frecuencia_amenities = amenities_separados.value_counts()

print("Cantidad de categorías distintas:", amenities_separados.nunique())
frecuencia_amenities.head(30)

Cantidad de categorías distintas: 95

Amenities
Baño                             7219
Dormitorio                       6988
Cocina                           5882
Balcón                           5254
Electricidad                     5115
Living/Comedor                   4725
Placard                          4553
Ascensor                         4180
Living                           4071
Agua                             4047
Gas                              4041
Lavadero                         3438
Comedor                          3169
Aire Acondicionado               3001
Agua Corriente                   2999
Cocina/Comedor                   2801
Disposición Frente               2552
Desague Cloacal                  2524
Toilet                           2278
Pileta                           2034
Permite Mascotas                 1857
Internet                         1507
Terraza                          1447
Disposición Contrafrente         1369
Parrilla                         1256
Salón de usos múltiples - SUM    1249
ComYAmenCalefacción              1239
Habitación de Servicio           1084
Seguridad                        1075
Portón Automático                1072
Name: count, dtype: int64

In [ ]:
pd.set_option("display.max_rows", None)

frecuencia_amenities.reset_index().rename(
    columns={"count": "Cantidad"}
)

                         Amenities  Cantidad
0                             Baño      7219
1                       Dormitorio      6988
2                           Cocina      5882
3                           Balcón      5254
4                     Electricidad      5115
5                   Living/Comedor      4725
6                          Placard      4553
7                         Ascensor      4180
8                           Living      4071
9                             Agua      4047
10                             Gas      4041
11                        Lavadero      3438
12                         Comedor      3169
13              Aire Acondicionado      3001
14                  Agua Corriente      2999
15                  Cocina/Comedor      2801
16              Disposición Frente      2552
17                 Desague Cloacal      2524
18                          Toilet      2278
19                          Pileta      2034
20                Permite Mascotas      1857
21                        Internet      1507
22                         Terraza      1447
23        Disposición Contrafrente      1369
24                        Parrilla      1256
25   Salón de usos múltiples - SUM      1249
26             ComYAmenCalefacción      1239
27          Habitación de Servicio      1084
28                       Seguridad      1075
29               Portón Automático      1072
30                        Vestidor      1068
31                        Solarium      1010
32            Televisión por Cable       997
33                         Baulera       985
34                           Patio       975
35                         Laundry       940
36                     Desayunador       815
37                    Agua Potable       810
38               Orientación Norte       743
39                Orientación Este       733
40                        Gimnasio       722
41                   Losa Radiante       722
42                       Recepción       622
43                        Teléfono       620
44                         Caldera       558
45                            Otro       555
46               Orientación Oeste       516
47                         Estudio       466
48                    Áreas Verdes       453
49                  Apto Turístico       417
50               Sala de reuniones       367
51             Disposición Lateral       359
52             Disposición Interno       357
53   Acceso de cochera, Rampa fija       351
54            Orientación Noroeste       333
55             Orientación Noreste       333
56                          Jardín       319
57            Televisión Satelital       311
58   Acceso de cochera, Horizontal       301
59                         Quincho       279
60                 Orientación Sur       236
61       Área de juegos infantiles       211
62                           Sauna       208
63                           Lobby       206
64                        Playroom       206
65     Acceso de cochera, Ascensor       197
66                 Business Center       191
67            Orientación Suroeste       173
68                     Hidromasaje       160
69                          Alarma       157
70              Pileta Climatizada       157
71             Orientación Sureste       156
72                        Amoblado       148
73    Estacionamiento para visitas       127
74                      Agua Dulce       116
75                 Pileta Cubierta       104
76                            Deck        82
77                         Altillo        57
78                             Bar        49
79              Jardín de Invierno        48
80  Acceso de cochera, Rampa móvil        48
81                    Área de Cine        41
82                          Sótano        39
83                        Chimenea        30
84                        Cisterna        30
85                      Biblioteca        30
86                         Bodegas        18
87                   Valet Parking        17
88                 Cancha de tenis        14
89                Cancha de Paddle        10
90                Cancha de futbol        10
91                  Camino Natural         7
92            Cancha de Basquetbol         6
93                          Galpón         5
94                       Alambrado         4

In [ ]:
print("Moneda_Expensas faltantes:",
      df_limpio["Moneda_Expensas"].isna().sum())

print()
print(df_limpio["Moneda_Expensas"].value_counts(dropna=False))

Moneda_Expensas faltantes: 1

Moneda_Expensas
ARS    10228
USD       50
NaN        1
Name: count, dtype: int64

In [ ]:
df_limpio.loc[
    df_limpio["Moneda_Expensas"] == "USD",
    [
        "ID", "Titulo", "Barrio",
        "Precio_Valor", "Moneda_Expensas", "Expensas"
    ]
].head(20)

,ID,Titulo,Barrio,Precio_Valor,Moneda_Expensas,Expensas
31,639663,Emprendimiento en Lavalle 4018,Almagro,70800.0,USD,NaN
33,639657,EMPRENDIMIENTO EN LAVALLE 4078,Almagro,172640.0,USD,NaN
241,638776,EMPRENDIMIENTO EN ALMAGRO ENTREGA OCTUBRE 2026,Almagro,102840.0,USD,NaN
363,638648,SKY ANCHORENA FINANCIACION AMENITIES PREMIUM,Balvanera,291200.0,USD,NaN
749,636330,DEPTO. DE EPOCA EN MICROCENTRO IDEAL INVERSORE...,Retiro,75000.0,USD,210000.0
840,635959,VENTA DPTO MONOAMBIENTE PARQUE CHAS,Parque Chas,85900.0,USD,150000.0
963,635472,VENTA SEMIPISO 5 AMB C/DEP AV STA FE 2879 B°NORTE,Barrio Norte,260000.0,USD,615.0
1026,635642,Emprendimiento Punto Caballito Avda Directorio...,Caballito,154200.0,USD,NaN
1220,634237,VENTA HERMOSO DOS AMBIENTES EN SAN JUAN 3200.,San Cristobal,143000.0,USD,300000.0
2059,630242,SOLACE ESTOMBA,Coghlan,91500.0,USD,NaN
2956,625979,VENTA DPTOS 2 Y 3 AMBIENTES EN SAAVEDRA! PERMUTA,Saavedra,115000.0,USD,NaN
3279,624240,Emprendimiento Well Thomas,Villa Ortuzar,201440.0,USD,NaN
5900,609062,Departamentos en venta Saavedra,Saavedra,195000.0,USD,NaN
5934,608840,Venta Dpto.3amb+dependencia-Recoleta,Recoleta,190000.0,USD,NaN
6632,604540,Pringles 707 - Mono ambientes,Almagro,96000.0,USD,NaN
6838,603448,VENTA DEPTOS MONOAMBIENTE - 2AMB - 3AMB Y 4 AMB,Villa Urquiza,138502.0,USD,NaN
7398,600233,VENTA EMPRENDIMIENTO BELGRANO,Belgrano,179400.0,USD,NaN
7469,600063,"MONOAMB, 2 Y 3 AMB. FINANCIACION A 5 AÑOS!",Balvanera,92873.0,USD,NaN
7471,600039,"DEPTOS MONOAMBIENTE, 2 AMB Y 3 AMB. FINANCIAC...",Palermo,176160.0,USD,NaN
7703,598022,VENTA 2 AMB EN BARRIO PARQUE CON BALCON TERRAZA,Barrio Norte,290000.0,USD,256.0

In [ ]:
expensas_usd_con_valor = df_limpio[
    (df_limpio["Moneda_Expensas"] == "USD") &
    (df_limpio["Expensas"].notna())
]

print("Casos USD con expensas informadas:", len(expensas_usd_con_valor))

expensas_usd_con_valor[
    ["ID", "Titulo", "Barrio", "Expensas"]
]

Casos USD con expensas informadas: 9

,ID,Titulo,Barrio,Expensas
749,636330,DEPTO. DE EPOCA EN MICROCENTRO IDEAL INVERSORE...,Retiro,210000.0
840,635959,VENTA DPTO MONOAMBIENTE PARQUE CHAS,Parque Chas,150000.0
963,635472,VENTA SEMIPISO 5 AMB C/DEP AV STA FE 2879 B°NORTE,Barrio Norte,615.0
1220,634237,VENTA HERMOSO DOS AMBIENTES EN SAN JUAN 3200.,San Cristobal,300000.0
7703,598022,VENTA 2 AMB EN BARRIO PARQUE CON BALCON TERRAZA,Barrio Norte,256.0
11946,563780,Venta departamento L'avenue Zaha Hadid en Palermo,Palermo,1500.0
12706,554586,Depto 3 amb Amenities Cochera Puerto Madero Venta,Puerto Madero,804500.0
12897,552264,Depto Venta 4 amb con balcon Palermo,Palermo,300000.0
13906,536162,Venta departamento con Terraza propia,Saavedra,1200.0

In [ ]:
import re

for _, fila in expensas_usd_con_valor.iterrows():
    descripcion = str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,80}expensas.{0,100}",
        descripcion,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Expensas:", fila["Expensas"], fila["Moneda_Expensas"])

    if fragmentos:
        for fragmento in fragmentos:
            print("...", fragmento, "...")
    else:
        print("No se encontró 'expensas' en la descripción.")

================================================================================
ID: 636330
Expensas: 210000.0 USD
... $150mil pesos de expensas. ...

================================================================================
ID: 635959
Expensas: 150000.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 635472
Expensas: 615.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 634237
Expensas: 300000.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 598022
Expensas: 256.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 563780
Expensas: 1500.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 554586
Expensas: 804500.0 USD
... Las expensas $804.000, incluyen Agip. Edenor Aysa ...

================================================================================
ID: 552264
Expensas: 300000.0 USD
No se encontró 'expensas' en la descripción.

================================================================================
ID: 536162
Expensas: 1200.0 USD
No se encontró 'expensas' en la descripción.

In [ ]:
ids_moneda_expensas_ars = [636330, 554586]

df_limpio.loc[
    df_limpio["ID"].isin(ids_moneda_expensas_ars),
    "Moneda_Expensas"
] = "ARS"

df_limpio["Moneda_Expensas"].value_counts(dropna=False)

Moneda_Expensas
ARS    10230
USD       48
NaN        1
Name: count, dtype: int64

In [ ]:
df_limpio.loc[
    df_limpio["Moneda_Expensas"].isna(),
    ["ID", "Titulo", "Barrio", "Expensas", "Moneda_Expensas", "Descripcion"]
]

,ID,Titulo,Barrio,Expensas,Moneda_Expensas,Descripcion
16968,40000,"Venta,4 amb,caballito,C/cochera y parrilla",Caballito,NaN,NaN,dhttps://my.matterport.com/show/?m=FWkAvsbqo...

In [ ]:
df_limpio["Estado"].value_counts(dropna=False)

Estado
active         7921
reserved       1659
negotiation     699
Name: count, dtype: int64

In [ ]:
df_limpio.loc[
    df_limpio["Barrio"].isna() | df_limpio["Ubicacion"].isna(),
    ["ID", "Titulo", "Direccion", "Barrio", "Ubicacion", "Latitud", "Longitud"]
]

,ID,Titulo,Direccion,Barrio,Ubicacion,Latitud,Longitud
13286,546897,DEPARTAMENTO 2 AMBIENTES VENTA VILLA URQUIZA,Olazabal 5000,NaN,NaN,-34.575949,-58.485503

In [ ]:
df_limpio.loc[
    df_limpio["Barrio"] == "Villa Urquiza",
    ["Barrio", "Ubicacion"]
].value_counts().head(10)

Barrio         Ubicacion
Villa Urquiza  Villa Urquiza, Capital Federal    371
Name: count, dtype: int64

In [ ]:
df_limpio.loc[df_limpio["ID"] == 546897, "Barrio"] = "Villa Urquiza"
df_limpio.loc[df_limpio["ID"] == 546897, "Ubicacion"] = "Villa Urquiza, Capital Federal"

print("Barrio faltantes:", df_limpio["Barrio"].isna().sum())
print("Ubicacion faltantes:", df_limpio["Ubicacion"].isna().sum())

Barrio faltantes: 0
Ubicacion faltantes: 0

In [ ]:
print("Descripcion faltantes:",
      df_limpio["Descripcion"].isna().sum())

df_limpio.loc[
    df_limpio["Descripcion"].isna(),
    ["ID", "Titulo", "Barrio", "Tipo_Propiedad", "Precio_Valor"]
].head(20)

Descripcion faltantes: 59

,ID,Titulo,Barrio,Tipo_Propiedad,Precio_Valor
10,639751,VENTA MIDOKI ARGERICH 2783 VILLA DEL PARQUE,Villa del Parque,departamento_estandar,139135.0
31,639663,Emprendimiento en Lavalle 4018,Almagro,departamento_monoambiente,70800.0
33,639657,EMPRENDIMIENTO EN LAVALLE 4078,Almagro,departamento_estandar,172640.0
114,639331,VENTA DPTOS DE 1 Y 2 AMB-AMENITIES DESDE 95.92...,Belgrano,departamento_estandar,83080.0
241,638776,EMPRENDIMIENTO EN ALMAGRO ENTREGA OCTUBRE 2026,Almagro,departamento_monoambiente,102840.0
363,638648,SKY ANCHORENA FINANCIACION AMENITIES PREMIUM,Balvanera,departamento_semipiso,291200.0
1026,635642,Emprendimiento Punto Caballito Avda Directorio...,Caballito,departamento_estandar,154200.0
2059,630242,SOLACE ESTOMBA,Coghlan,departamento_monoambiente,91500.0
2818,626767,Residencias de Villa del Parque,Villa del Parque,departamento_semipiso,140000.0
2956,625979,VENTA DPTOS 2 Y 3 AMBIENTES EN SAAVEDRA! PERMUTA,Saavedra,departamento_estandar,115000.0
3279,624240,Emprendimiento Well Thomas,Villa Ortuzar,departamento_estandar,201440.0
5059,613996,"VENTA EMPRENDIMIENTO YRIGOYEN MONSERRAT, AMENI...",Monserrat,departamento_monoambiente,123424.0
5061,614035,VENTA EMPRENDIMIENTO -SANTA FE- PALERMO AMENITIES,Palermo,departamento_estandar,287560.0
5900,609062,Departamentos en venta Saavedra,Saavedra,departamento_estandar,195000.0
6632,604540,Pringles 707 - Mono ambientes,Almagro,departamento_monoambiente,96000.0
6838,603448,VENTA DEPTOS MONOAMBIENTE - 2AMB - 3AMB Y 4 AMB,Villa Urquiza,departamento_monoambiente,138502.0
6924,602990,VENTA DEPARTAMENTO 3 AMB SAAVEDRA PISO COMPLETO,Saavedra,departamento_estandar,287500.0
7008,602551,Departamentos 1 2 3 y 4 ambientes en Caballito...,Caballito Sur,departamento_estandar,121000.0
7398,600233,VENTA EMPRENDIMIENTO BELGRANO,Belgrano,departamento_estandar,179400.0
7452,609026,Venta departamentos en Colegiales,Colegiales,departamento_monoambiente,112000.0

In [ ]:
patron_nuevo_titulo = (
    r"emprendimiento|pozo|a estrenar|estrenar|"
    r"en construcci[oó]n|pre[\s-]?venta|entrega"
)

mask_desc_na = df_limpio["Descripcion"].isna()

mask_nuevo_titulo_desc_na = (
    mask_desc_na &
    df_limpio["Titulo"].str.contains(
        patron_nuevo_titulo,
        case=False,
        na=False
    )
)

print("Sin descripción:", mask_desc_na.sum())
print(
    "Sin descripción + indicios de nuevo/emprendimiento en título:",
    mask_nuevo_titulo_desc_na.sum()
)

df_limpio.loc[
    mask_nuevo_titulo_desc_na,
    ["ID", "Titulo", "Antiguedad", "Barrio", "Precio_Valor"]
]

Sin descripción: 59
Sin descripción + indicios de nuevo/emprendimiento en título: 16

,ID,Titulo,Antiguedad,Barrio,Precio_Valor
31,639663,Emprendimiento en Lavalle 4018,NaN,Almagro,70800.0
33,639657,EMPRENDIMIENTO EN LAVALLE 4078,NaN,Almagro,172640.0
241,638776,EMPRENDIMIENTO EN ALMAGRO ENTREGA OCTUBRE 2026,NaN,Almagro,102840.0
1026,635642,Emprendimiento Punto Caballito Avda Directorio...,NaN,Caballito,154200.0
3279,624240,Emprendimiento Well Thomas,NaN,Villa Ortuzar,201440.0
5059,613996,"VENTA EMPRENDIMIENTO YRIGOYEN MONSERRAT, AMENI...",NaN,Monserrat,123424.0
5061,614035,VENTA EMPRENDIMIENTO -SANTA FE- PALERMO AMENITIES,NaN,Palermo,287560.0
7398,600233,VENTA EMPRENDIMIENTO BELGRANO,NaN,Belgrano,179400.0
8069,596371,Emprendimiento en Palermo - Entrega Inmediata,NaN,Palermo Soho,126000.0
8939,590334,Emprendimiento en Yerbal 1510 Caballito 1-2-3-...,NaN,Caballito Norte,63609.0
9753,585238,VENTA NUEVO EMPRENDIMIENTO EN NUÑEZ,NaN,Saavedra,112661.0
9817,583898,MONTE CASTRO - EMPRENDIMIENTO BERNALDES 1871,NaN,Monte Castro,56700.0
10077,628152,NUEVO EMPRENDIMIENTO EN SAAVEDRA FINANCIACIÓN,NaN,Saavedra,179630.0
10653,577132,Venta CHIVILCOY 2300 - Entrega Febrero 2026,NaN,Monte Castro,145000.0
14154,531627,"Venta emprendimiento , Belgrano. 1 , 2 y 3 amb",NaN,Belgrano,187340.0
15414,542099,VENTA MONOAM Y 2 AMB SAN TELMO ENTREGA SEPT 2026,NaN,San Telmo,121598.0

In [ ]:
ids_nuevos_sin_descripcion = df_limpio.loc[
    mask_nuevo_titulo_desc_na,
    "ID"
].tolist()

n_antes = len(df_limpio)

df_limpio = df_limpio.loc[
    ~df_limpio["ID"].isin(ids_nuevos_sin_descripcion)
].copy()

print("Registros antes:", n_antes)
print("Registros después:", len(df_limpio))
print("Eliminados:", n_antes - len(df_limpio))
print("Descripciones faltantes:", df_limpio["Descripcion"].isna().sum())

Registros antes: 10279
Registros después: 10263
Eliminados: 16
Descripciones faltantes: 43

In [ ]:
df_limpio.loc[
    df_limpio["Descripcion"].isna(),
    ["ID", "Titulo", "Antiguedad", "Barrio", "Tipo_Propiedad", "Precio_Valor"]
]

,ID,Titulo,Antiguedad,Barrio,Tipo_Propiedad,Precio_Valor
10,639751,VENTA MIDOKI ARGERICH 2783 VILLA DEL PARQUE,NaN,Villa del Parque,departamento_estandar,139135.0
114,639331,VENTA DPTOS DE 1 Y 2 AMB-AMENITIES DESDE 95.92...,NaN,Belgrano,departamento_estandar,83080.0
363,638648,SKY ANCHORENA FINANCIACION AMENITIES PREMIUM,NaN,Balvanera,departamento_semipiso,291200.0
2059,630242,SOLACE ESTOMBA,NaN,Coghlan,departamento_monoambiente,91500.0
2818,626767,Residencias de Villa del Parque,NaN,Villa del Parque,departamento_semipiso,140000.0
2956,625979,VENTA DPTOS 2 Y 3 AMBIENTES EN SAAVEDRA! PERMUTA,NaN,Saavedra,departamento_estandar,115000.0
5900,609062,Departamentos en venta Saavedra,NaN,Saavedra,departamento_estandar,195000.0
6632,604540,Pringles 707 - Mono ambientes,NaN,Almagro,departamento_monoambiente,96000.0
6838,603448,VENTA DEPTOS MONOAMBIENTE - 2AMB - 3AMB Y 4 AMB,NaN,Villa Urquiza,departamento_monoambiente,138502.0
6924,602990,VENTA DEPARTAMENTO 3 AMB SAAVEDRA PISO COMPLETO,NaN,Saavedra,departamento_estandar,287500.0
7008,602551,Departamentos 1 2 3 y 4 ambientes en Caballito...,NaN,Caballito Sur,departamento_estandar,121000.0
7452,609026,Venta departamentos en Colegiales,NaN,Colegiales,departamento_monoambiente,112000.0
7469,600063,"MONOAMB, 2 Y 3 AMB. FINANCIACION A 5 AÑOS!",NaN,Balvanera,departamento_monoambiente,92873.0
7471,600039,"DEPTOS MONOAMBIENTE, 2 AMB Y 3 AMB. FINANCIAC...",NaN,Palermo,departamento_estandar,176160.0
7698,598090,"VIEL II - FUNCIONALIDAD, DISEÑO Y UBICACIÓN",NaN,Caballito Sur,departamento_estandar,209762.0
7788,627277,Departamentos Venta 1 y 2 Ambientes Almagro,NaN,Almagro,departamento_estandar,101010.0
8071,596370,VENTA DEPTOS 2 AMBIENTES EN NUÑEZ,NaN,Nuñez,departamento_estandar,215468.0
8072,595505,"Venta departamentos 2, 3 y 4 AMB EN Colegiales",NaN,Colegiales,departamento_estandar,710325.0
8139,595372,"VENTA EMPREND. NOV 26 - 1,2 Y 3 AMB. - ALMAGRO",NaN,Almagro,departamento_monoambiente,81500.0
8940,590332,Venta Departamentos Rojas 372 en Caballito,NaN,Caballito Sur,departamento_monoambiente,122541.0
9375,587215,Venta departamentos en Colegiales,NaN,Colegiales,departamento_estandar,186036.0
9780,584265,"DEPARTAMENTO 1, 2, 3 AMB. LOCAL EN VENTA ALMAGRO",NaN,Almagro,departamento_semipiso,144186.0
9781,584260,"DPTOS 1, 2, 3 AMB. EN VENTA AMENITIES VILLA CR...",NaN,Villa Crespo,departamento_estandar,135016.0
9915,583198,2 Y 3 AMB C/BCON Y/O TERRAZA. MEDIADOS 2028. N...,NaN,Nuñez,departamento_estandar,164905.0
10466,579332,VENTA 3 AMBIENTES Y COCHERAS - DEVOTO,NaN,Villa Devoto,departamento_estandar,180000.0
10769,585277,venta departamento 2 y 3 ambiente Belgrano coc...,NaN,Belgrano,departamento_semipiso,238651.0
10924,574857,VENTA 4 Y 5 AMB JARDIN+PILRTA+QUINCHO,NaN,Colegiales,departamento_estandar,815000.0
11032,573214,"Gam Loyola, futuro urbano en Villa Crespo",NaN,Villa Crespo,departamento_estandar,255000.0
12040,562772,Venta desarrollo Belgrano,NaN,Barrancas de Belgrano,departamento_monoambiente,122000.0
12541,556802,VENTA PALERMO 1 A 4 AMB FULL AMENITIES COCH A ...,NaN,Palermo Hollywood,departamento_estandar,186000.0
13455,544253,DEPARTAMENTOS FLORESTA AVANT UNO DOS Y TRES AM...,NaN,Floresta,departamento_monoambiente,72000.0
13607,542051,LIV Guatemala | Exclusivos 2 ambientes,NaN,Palermo,departamento_estandar,225000.0
14178,535052,CHIVILCOY 2171,NaN,Monte Castro,departamento_estandar,99600.0
14212,530592,ESPACIO BESARES | SAAVEDRA,NaN,Saavedra,departamento_estandar,153400.0
14584,521590,BONI - JOSÉ BONIFACIO 3961,NaN,Parque Avellaneda,departamento_estandar,108000.0
14680,519391,VENTA 2 y 4 AMB PALERMO AMENITIES,NaN,Palermo,departamento_estandar,134287.0
15146,504788,DEPTO 1 A 5 AMB JARDIN TERRAZA PARRILLA COLEGI...,NaN,Colegiales,departamento_estandar,564000.0
16021,579355,VENTA DEPARTAMENTOS EN BAJO BELGRANO,NaN,Belgrano,departamento_estandar,235705.0
16180,590340,LOT HELGUERA DEPTOS 1 A 4 AMB VILLA DEL PARQUE,NaN,Villa del Parque,departamento_monoambiente,119000.0
16340,453887,"DESARROLLO 2, 3 Y 4 AMB JARDINES Y TERRAZAS N...",NaN,Nuñez,departamento_estandar,303800.0
16602,639418,GARCIA DEL RIO 3760.,NaN,Saavedra,departamento_estandar,319800.0
16926,549373,VENTA 1 Y 2 AMB APTO CREDITO PALERMO AMENITIES,NaN,Palermo,departamento_estandar,157431.0
16927,541479,VENTA 1 Y 2 AMB SAN TELMO EN CONTRUCCION AMENI...,NaN,San Telmo,departamento_monoambiente,95246.0

In [ ]:
patron_nuevo_titulo_ampliado = (
    r"emprend|desarrollo|en construcci[oó]n|en contruccion|"
    r"pozo|a estrenar|estrenar|pre[\s-]?venta|"
    r"entrega|mediados 20\d{2}|futuro urbano"
)

mask_nuevo_sin_desc_2 = (
    df_limpio["Descripcion"].isna() &
    df_limpio["Titulo"].str.contains(
        patron_nuevo_titulo_ampliado,
        case=False,
        na=False
    )
)

print("Casos detectados:", mask_nuevo_sin_desc_2.sum())

df_limpio.loc[
    mask_nuevo_sin_desc_2,
    ["ID", "Titulo", "Antiguedad", "Barrio", "Precio_Valor"]
]

Casos detectados: 6

,ID,Titulo,Antiguedad,Barrio,Precio_Valor
8139,595372,"VENTA EMPREND. NOV 26 - 1,2 Y 3 AMB. - ALMAGRO",NaN,Almagro,81500.0
9915,583198,2 Y 3 AMB C/BCON Y/O TERRAZA. MEDIADOS 2028. N...,NaN,Nuñez,164905.0
11032,573214,"Gam Loyola, futuro urbano en Villa Crespo",NaN,Villa Crespo,255000.0
12040,562772,Venta desarrollo Belgrano,NaN,Barrancas de Belgrano,122000.0
16340,453887,"DESARROLLO 2, 3 Y 4 AMB JARDINES Y TERRAZAS N...",NaN,Nuñez,303800.0
16927,541479,VENTA 1 Y 2 AMB SAN TELMO EN CONTRUCCION AMENI...,NaN,San Telmo,95246.0

In [ ]:
n_antes = len(df_limpio)

df_limpio = df_limpio.loc[
    ~mask_nuevo_sin_desc_2
].copy()

print("Registros antes:", n_antes)
print("Registros después:", len(df_limpio))
print("Eliminados:", n_antes - len(df_limpio))
print("Descripciones faltantes:", df_limpio["Descripcion"].isna().sum())
print("Antigüedad faltante:", df_limpio["Antiguedad"].isna().sum())

Registros antes: 10263
Registros después: 10257
Eliminados: 6
Descripciones faltantes: 37
Antigüedad faltante: 38

In [ ]:
patron_nuevo_titulo_final = (
    r"emprend|desarrollo|pozo|a estrenar|"
    r"en construcci[oó]n|en contruccion|pre[\s-]?venta"
)

mask_nuevo_titulo_final = df_limpio["Titulo"].str.contains(
    patron_nuevo_titulo_final,
    case=False,
    na=False
)

print("Casos con indicios de propiedad nueva en el título:",
      mask_nuevo_titulo_final.sum())

df_limpio.loc[
    mask_nuevo_titulo_final,
    ["ID", "Titulo", "Antiguedad", "Barrio", "Precio_Valor"]
].head(50)

Casos con indicios de propiedad nueva en el título: 523

,ID,Titulo,Antiguedad,Barrio,Precio_Valor
2,639766,Venta Depto. 2 Amb. balcón a estrenar en Nuñez,1.0,Nuñez,196860.0
19,639693,VENTA DEPARTAMENTO 2 AMB A ESTRENAR BALVANERA,1.0,Balvanera,123000.0
26,639665,VENTA DEPARTAMENTO 3 AMB A ESTRENAR VILLA URQUIZA,1.0,Villa Urquiza,230000.0
44,639619,VENTA Dpto 3 amb-Balcon-A Estrenar-V.Gral Mitre,1.0,Villa General Mitre,140970.0
127,639282,VENTA MONOAMBIENTE ALMAGRO A ESTRENAR,1.0,Almagro,98000.0
160,639064,VENTA -MONOAMBIENTE -PALERMO - A ESTRENAR,1.0,Palermo,83000.0
185,638972,Venta Monoambiente a estrenar en Villa Devoto,1.0,Villa Devoto,87000.0
195,638924,MONOAMBIENTE A ESTRENAR EN VENTA NÚÑEZ SOBRE A...,1.0,Nuñez,124260.0
204,638905,CAÑITAS:4 AMB. A ESTRENAR. SE ESCUCHAN OFERTAS,4.0,Palermo,461874.0
205,638901,PALERMO SOHO: MONO A ESTRENAR CATEGORÍA DISEÑO,6.0,Palermo,179000.0
233,638804,SE VENDE 2 AMB A ESTRENAR TERRRAZA PROPIA PALERMO,4.0,Palermo,248000.0
250,638674,AMPLIO MONOAMBIENTE A ESTRENAR CON FINANCIACION,1.0,Balvanera,95000.0
257,638627,VENTA MONOAMBIENTE A ESTRENAR EN BOEDO,1.0,Boedo,84500.0
310,638362,Venta Depto 3 amb balcón a estrenar Villa Urquiza,2.0,Villa Urquiza,218000.0
311,638360,Venta Depto 2 amb balcón a estrenar Villa Urquiza,2.0,Villa Urquiza,165000.0
379,638071,Departamento A Estrenar Loft,2.0,Almagro,139500.0
419,637883,VENTA DEPARTAMENTO 2 AMBIENTES A ESTRENAR RECO...,1.0,Barrio Norte,215000.0
434,637812,VENTA DEPARTAMENTO 2 AMBIENTES A ESTRENAR ORTUZAR,1.0,Villa Ortuzar,230188.0
452,637782,MONOAMBIENTE A ESTRENAR CON BALCON SAN CRISTÓBAL,1.0,San Cristobal,89000.0
514,637362,DEPTO 2 AMB EN SAAVEDRA A ESTRENAR CON BALCÓN,1.0,Saavedra,142200.0
516,637360,VENTA DEPTO MONOAMB DIVISIBLE A ESTRENAR BALVA...,1.0,Balvanera,88000.0
533,637252,3 ambientes a estrenar en Depampa c/cohera fija,1.0,Bajo Belgrano,500000.0
543,637203,DEPARTAMENTO 3 AMB CON COCHERA LINIERS A ESTRENAR,1.0,Liniers,210000.0
574,637109,MONOAMBIENTE VENTA VILLA LURO BOLUEVAR A ESTR...,16.0,Villa Luro,94900.0
718,636446,SEMIPISO 4 AMB. A ESTRENAR - POSESION INMEDIATA,1.0,Villa Devoto,595000.0
751,636304,"Monoambiente de pozo, contrafrente ,Villa Ortuzar",1.0,Villa Ortuzar,82000.0
752,636303,"Monoambiente a estrenar, contrafrente ,V. Ortuzar",1.0,Villa Ortuzar,74940.0
891,635772,DEPTO MONOAMBIENTE EN VENTA A ESTRENAR-FINANCIA,1.0,Barracas,53000.0
893,635766,"VENTA 3 AMB. BELGRANO- A ESTRENAR, CON TERRAZA",1.0,Belgrano,299000.0
897,635754,VENTA DEPARTAMENTO 2 AMB A ESTRENAR V.URQUIZA,1.0,Villa Urquiza,134900.0
995,635356,VENTA DEPARTAMENTO 3 AMB A ESTRENAR APTO CREDITO,1.0,Almagro,159900.0
1057,635009,Monoambiente a estrenar con cochera Villa Ortuzar,3.0,Villa Ortuzar,86000.0
1075,634909,VENTA MONOAMBIENTE EN POZO CON BALCON EN BELGRANO,1.0,Belgrano,78000.0
1183,634388,VENTA 4 AMB AGRONOMIA AMENITIES PILETA ESTRENA...,2.0,Villa del Parque,370000.0
1202,634302,DEPTO MONO DIVISIBLE GRAN BALCÓN EN POZO PALERMO,1.0,Palermo,153092.0
1246,634145,VENTA 2 AMBIENTES A ESTRENAR CON PATIO ALMAGRO,2.0,Almagro,129000.0
1267,634051,"Venta 3 AMB Patio, Amenities a Estrenar Caballito",3.0,Caballito,273389.0
1385,633465,VENTA MONOAMBIENTE CON JARDÍN NUÑEZ A ESTRENAR,6.0,Nuñez,140000.0
1670,632099,Monoambiente a estrenar con pileta full amenitis,1.0,Monserrat,67000.0
1700,631935,DEPARTAMENTO 3 AMBIENTES EN DEVOTO POZO,1.0,Villa Devoto,153000.0
1727,631777,Monoambiente en Venta Monserrat- A estrenar -,1.0,Monserrat,79000.0
1853,631159,Departamento 3 ambientes venta Palermo a estrenar,1.0,Palermo Chico,425000.0
1854,631153,Departamento 3 ambientes venta Palermo a estrenar,1.0,Palermo Chico,617000.0
1893,630981,VENTA DEPARTAMENTO 2 AMBIENTES NUÑEZ BALCON POZO,1.0,Nuñez,136500.0
1894,630980,VENTA DEPARTAMENTO 3 AMBIENTES NUÑEZ BALCON POZO,1.0,Nuñez,198000.0
1902,630899,Venta monoabiente en Torre a estrenar en Barracas,2.0,Barracas,82500.0
1903,630898,Venta 1 ambiente en Torre a estrenar en Barracas,2.0,Barracas,67500.0
1905,630894,Venta 3 ambiente en Torre a estrenar en Barracas,2.0,Barracas,190000.0
2058,630179,VENTA DEPTO 3 AMB FULL AMEN. A ESTRENAR NUÑEZ,2.0,Nuñez,246843.0
2078,630114,VENTA 3 AMBIENTES COCHERA A ESTRENAR PALERMO,1.0,Palermo Hollywood,220000.0

In [ ]:
terminos_nuevos = {
    "a_estrenar": r"a estrenar",
    "pozo": r"\bpozo\b",
    "construccion": r"en construcci[oó]n|en contruccion",
    "preventa": r"pre[\s-]?venta",
    "emprendimiento": r"emprend",
    "desarrollo": r"desarrollo"
}

for nombre, patron in terminos_nuevos.items():
    cantidad = df_limpio["Titulo"].str.contains(
        patron, case=False, na=False, regex=True
    ).sum()
    print(f"{nombre}: {cantidad}")

a_estrenar: 437
pozo: 55
construccion: 9
preventa: 1
emprendimiento: 13
desarrollo: 11

In [ ]:
mask_emprend_desarrollo = df_limpio["Titulo"].str.contains(
    r"emprend|desarrollo",
    case=False,
    na=False,
    regex=True
)

df_limpio.loc[
    mask_emprend_desarrollo,
    ["ID", "Titulo", "Antiguedad", "Barrio", "Precio_Valor"]
]

,ID,Titulo,Antiguedad,Barrio,Precio_Valor
2638,627565,2 Amb. Emprendimiento al costo! Oport. Inversión,0.0,Villa Crespo,93000.0
5565,611025,Lindisimo emprendimiento en Villa Crespo,0.0,Villa Crespo,125000.0
10650,577137,Preventa Emprendimiento Aviles 3863 Villa Ort...,1.0,Villa Ortuzar,155000.0
12099,561959,VENTA 3 AMBIENTES EN DESARROLLO PALERMO HOLLYWOOD,0.0,Palermo Hollywood,325000.0
13050,550455,VENTA MONOAMBIENTE POZO DESARROLLO FINANCIACION,12.0,Villa Crespo,97500.0
13051,550453,VENTA MONOAMBIENTE POZO DESARROLLO FINANCIACION,21.0,Villa Crespo,156000.0
13197,548248,Venta Departamento 2 Amb Desarrollo Villa Urquiza,1.0,Villa Urquiza,159000.0
15803,466940,VENTA DPTO. PALERMO HOLLYWOOD . EMPRENDIMIENTO!,2.0,Palermo Hollywood,156870.0
15804,466939,DESARROLLO. MONOAMBIENTE EN PALERMO HOLLYWOOD,2.0,Palermo Hollywood,138941.0
15805,466924,EMPRENDIEMIENTO. VENTA 3 AMB. EN BELGRANO,2.0,Belgrano,304351.0
15806,466921,EMPRENDIMIENTO. VENTA MONOAMBIENTE,2.0,Belgrano,116097.0
15807,466919,EMPRENDIMIENTO! 2 AMB. EN BELGRANO,2.0,Belgrano,208547.0
15908,458872,Desarrollo A+!! Imperdible MonoAmb. Inv p/Temp...,1.0,Palermo,136055.0
15909,458871,Excelente Desarrollo Categoría. 3 amb. Coch Di...,1.0,Chacarita,257362.0
15910,458870,Desarrollo Único!!2 amb Coch/Opc. Edif Sustent...,1.0,Chacarita,184405.0
15911,458868,Desarrollo A+!! Imperdible MonoAmb. Inv p/Temp...,1.0,Chacarita,136055.0
16111,438291,Venta Departamento 4 Amb Desarrollo Villa Urquiza,1.0,Villa Urquiza,330000.0
16288,417601,Venta Departamento 2 Amb Desarrollo Villa Urquiza,1.0,Villa Urquiza,155000.0
16741,290350,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,178000.0
16742,290348,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,197500.0
16743,290347,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,194200.0
16744,290344,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,195000.0
16745,290343,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,187300.0
16746,290342,Venta Emprendimiento Aviles 3863 Villa Ortuzar,1.0,Villa Ortuzar,175000.0

In [ ]:
patron_nuevo_titulo_final = (
    r"a estrenar|"
    r"\bpozo\b|"
    r"en construcci[oó]n|"
    r"en contruccion|"
    r"pre[\s-]?venta|"
    r"emprend|"
    r"desarrollo"
)

mask_nuevo_titulo_final = df_limpio["Titulo"].str.contains(
    patron_nuevo_titulo_final,
    case=False,
    na=False,
    regex=True
)

n_antes = len(df_limpio)
n_eliminar = mask_nuevo_titulo_final.sum()

df_limpio = df_limpio.loc[~mask_nuevo_titulo_final].copy()

print("Registros antes:", n_antes)
print("Propiedades nuevas eliminadas:", n_eliminar)
print("Registros después:", len(df_limpio))

Registros antes: 10257
Propiedades nuevas eliminadas: 523
Registros después: 9734

In [ ]:
faltantes_final = pd.DataFrame({
    "Faltantes": df_limpio.isna().sum(),
    "Porcentaje": (df_limpio.isna().mean() * 100).round(2)
})

faltantes_final[
    faltantes_final["Faltantes"] > 0
].sort_values("Porcentaje", ascending=False)

                        Faltantes  Porcentaje
Fecha_Publicacion            9734      100.00
Amenities                    1767       18.15
Expensas                     1013       10.41
Antiguedad                     38        0.39
Descripcion                    37        0.38
Apto_Credito                   37        0.38
Moneda_Expensas                 1        0.01
Precio_m2_Cubierto              1        0.01
Superficie_Cubierta_m2          1        0.01

In [ ]:
patron_alquiler = r"se alquila|en alquiler|requisitos de alquiler|contrato de alquiler"

mask_posible_alquiler = df_limpio["Descripcion"].str.contains(
    patron_alquiler,
    case=False,
    na=False,
    regex=True
)

print("Posibles alquileres detectados:", mask_posible_alquiler.sum())

df_limpio.loc[
    mask_posible_alquiler,
    ["ID", "Titulo", "Descripcion", "Precio_Valor", "Barrio"]
].head(20)

Posibles alquileres detectados: 169

,ID,Titulo,Descripcion,Precio_Valor,Barrio
35,639645,DEPARTAMENTO 3 AMBIENTES EN CENTA,DEPARTAMENTO 3 AMBIENTES EN ALQUILER VILLA SAN...,85000.0,Villa Santa Rita
74,639521,Depto en Venta 3 Amb - Plaza Irlanda - Caballito,Departamento en Venta de 3 ambientes zona de P...,125000.0,Flores
99,639381,VENTA DEPTO/4 AMBIENTES-C/BALCON/EXCELENTE EST...,VENTA DEPARTAMENTO DE 4 AMBIENTES CON BALCON E...,194500.0,Saavedra
234,638799,Oportunidad 4 ambientes refaccionado a nuevo,OPORTUNIDAD ÚNICA EN EL CORAZÓN DE LA CIUDAD –...,114000.0,San Nicolás
247,638679,DEPARTAMENTO 2 AMB CON BALCON Y TOILETTE - ALM...,VENTA DEPARTAMENTO DE 2 AMBIENTES - ALMAGRO - ...,95000.0,Almagro
508,637392,DEPARTAMENTO 2 AMBIENTES EN VENTA MONSERRAT,DEPARTAMENTO 2 AMBIENTES EN VENTA MONSERRAT CA...,65000.0,Monserrat
527,637281,VENTA PISO 3 AMB EN UBICACION ESTRATEGICA DE R...,PRESENTAMOS UN PISO EXCLUSIVO DE 3 AMBIENTES C...,310000.0,Retiro
580,637083,VENTA DEPTO 4 AMBIENTES DEPENDENCIA VILLA CRESPO,EL EQUIPO DE REMAX VENDE DEPARTAMENTO 4 AMBIEN...,185000.0,Villa Crespo
775,636200,Monoambiente en venta en Boedo,DEPARTAMENTO MONOAMBIENTE EN VENTA BOEDO A EST...,82000.0,Boedo
804,636077,VENTA 4 AMBIENTES NUÑEZ SUM PISCINA PARRILLA 7...,4 AMBIENTES | NÚÑEZ | BALCÓN ATERRAZADO | PISC...,215000.0,Nuñez
805,636075,Depto 3 Ambientes Apto Profesional con Balcón,Ubicado sobre la emblemática Avenida Rivadavia...,105000.0,San Nicolás
851,635906,Departamento 3 ambientes reciclado Belgrano fi...,Departamento 3 ambientes reciclado a nuevo en ...,186000.0,Belgrano
884,635820,Venta Depto 3 amb con balcon al frente Caballito,Departamento 3 ambientes con balcón y amenitie...,95000.0,Caballito
967,635457,VENTA DTO 3 AMB+ PLAYROOM MONTECASTRO JARDN QU...,DPTO TIPO PH 3 AMBIENTES + PLAYROOM O 3 ER HAB...,165000.0,Monte Castro
1112,634739,VENTA MONOAMBIENTE RENTA BALCÓN PARRILLA TERRAZA,VENTA | Monoambiente con Balcón en Palermo | ...,89000.0,Palermo
1244,634153,DEPARTAMENTO BALCON GRANDE -FRENTE- TODO LUZ 3...,DEPARTAMENTO 3 AMBIENTES VENTA FLORES CAPITAL ...,112000.0,Flores
1333,633693,MONOAMBIENETE C/BALCON/EXCELENTE ESTADO/UBICAC...,INMEJORABLE MONO-AMBIENTE EN EXCELENTE ESTADO ...,56400.0,Mataderos
1351,633611,VENTA Departamento 2 ambientes Palermo Colegiales,\nMuy luminoso!!!!!\nAPTO CREDITO\n-\nOrientac...,78000.0,Palermo
1368,633542,DEPARTAMENTO MONOAMBIENTE VENTA RECOLETA.USO PROF,VENTA MONOAMBIENTE AMOBLADO EN AV. DEL LIBERTA...,79900.0,Recoleta
1507,632965,Depto 4 amb en venta Caballito c/balcón al frente,**4 AMBIENTES CON DEPENDENCIA Y GRAN BALCÓN AL...,160000.0,Caballito

In [ ]:
mask_alquiler_fuerte = (
    df_limpio["Descripcion"].str.contains(
        r"departamento.{0,40}en alquiler|se alquila",
        case=False,
        na=False,
        regex=True
    )
    &
    ~df_limpio["Titulo"].str.contains(
        r"venta|vende",
        case=False,
        na=False,
        regex=True
    )
)

print("Casos sospechosos fuertes:", mask_alquiler_fuerte.sum())

df_limpio.loc[
    mask_alquiler_fuerte,
    ["ID", "Titulo", "Descripcion", "Precio_Valor", "Barrio"]
]

Casos sospechosos fuertes: 5

,ID,Titulo,Descripcion,Precio_Valor,Barrio
35,639645,DEPARTAMENTO 3 AMBIENTES EN CENTA,DEPARTAMENTO 3 AMBIENTES EN ALQUILER VILLA SAN...,85000.0,Villa Santa Rita
805,636075,Depto 3 Ambientes Apto Profesional con Balcón,Ubicado sobre la emblemática Avenida Rivadavia...,105000.0,San Nicolás
3701,621944,Monoambiente Recoleta,DEPARTAMENTO 1 AMBIENTE EN VENTA EN RECOLETA ....,53000.0,Recoleta
7546,599109,Departamento 3 amb. con cochera APTO CREDITO,"Semipiso al Frente / Piso 6 / Caballito, CABA ...",223000.0,Caballito
14151,531634,"Tres Ambientes en French y Araoz, Parque Las H...",Venta - 3 Ambientes con Gran Baulera en Recole...,169000.0,Palermo

In [ ]:
for _, fila in df_limpio.loc[mask_alquiler_fuerte].iterrows():
    descripcion = str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,120}alquiler.{0,150}",
        descripcion,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])
    print("Precio:", fila["Precio_Valor"])

    for fragmento in fragmentos:
        print("...", fragmento, "...")

================================================================================
ID: 639645
Título: DEPARTAMENTO 3 AMBIENTES EN CENTA
Precio: 85000.0
... DEPARTAMENTO 3 AMBIENTES EN ALQUILER VILLA SANTA RITA CAPITAL FEDERAL ...

================================================================================
ID: 636075
Título: Depto 3 Ambientes Apto Profesional con Balcón
Precio: 105000.0

================================================================================
ID: 621944
Título: Monoambiente Recoleta
Precio: 53000.0

================================================================================
ID: 599109
Título: Departamento 3 amb. con cochera APTO CREDITO
Precio: 223000.0

================================================================================
ID: 531634
Título: Tres Ambientes en French y Araoz, Parque Las Heras
Precio: 169000.0

In [ ]:
n_antes = len(df_limpio)

df_limpio = df_limpio.loc[
    df_limpio["ID"] != 639645
].copy()

print("Registros antes:", n_antes)
print("Registros después:", len(df_limpio))
print("Eliminados:", n_antes - len(df_limpio))

Registros antes: 9734
Registros después: 9733
Eliminados: 1

In [ ]:
df_limpio["Operacion"].value_counts(dropna=False)

Operacion
sale    9733
Name: count, dtype: int64

In [ ]:
df_limpio["Tipo_Propiedad"].value_counts(dropna=False)

Tipo_Propiedad
departamento_estandar        7501
departamento_monoambiente    1026
departamento_semipiso         519
departamento_piso             286
departamento_duplex           282
departamento_loft              55
departamento_triplex           39
departamento_penthouse         25
Name: count, dtype: int64

In [ ]:
df_limpio["Moneda"].value_counts(dropna=False)

Moneda
USD    9733
Name: count, dtype: int64

In [ ]:
print("Shape final:", df_limpio.shape)
print()
df_limpio.info()

Shape final: (9733, 29)

<class 'pandas.core.frame.DataFrame'>
Index: 9733 entries, 1 to 16992
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      9733 non-null   int64
 1   ID_Entidad              9733 non-null   object
 2   Operacion               9733 non-null   object
 3   Tipo_Propiedad          9733 non-null   object
 4   Titulo                  9733 non-null   object
 5   Descripcion             9696 non-null   object
 6   Fecha_Publicacion       0 non-null      float64
 7   Antiguedad              9695 non-null   float64
 8   Apto_Credito            9696 non-null   boolean
 9   Amenities               7966 non-null   object
 10  Moneda                  9733 non-null   object
 11  Precio_Valor            9733 non-null   float64
 12  Moneda_Expensas         9732 non-null   object
 13  Expensas                8720 non-null   float64
 14  Precio_m2_Total         9733 non-null   float64
 15  Precio_m2_Cubierto      9732 non-null   float64
 16  Ambientes               9733 non-null   int64
 17  Dormitorios             9733 non-null   int64
 18  Baños                   9733 non-null   int64
 19  Superficie_Total_m2     9733 non-null   float64
 20  Superficie_Cubierta_m2  9732 non-null   float64
 21  Direccion               9733 non-null   object
 22  Barrio                  9733 non-null   object
 23  Ubicacion               9733 non-null   object
 24  Latitud                 9733 non-null   float64
 25  Longitud                9733 non-null   float64
 26  Estado                  9733 non-null   object
 27  ID_Interno              9733 non-null   object
 28  Link                    9733 non-null   object
dtypes: boolean(1), float64(10), int64(4), object(14)
memory usage: 2.2+ MB

In [ ]:
df_limpio = df_limpio.reset_index(drop=True)

print("Shape:", df_limpio.shape)
print("Índice inicial:", df_limpio.index.min())
print("Índice final:", df_limpio.index.max())

Shape: (9733, 29)
Índice inicial: 0
Índice final: 9732

In [ ]:
terminos_estado = {
    "a_refaccionar": r"a refaccionar|para refaccionar",
    "a_reciclar": r"a reciclar|para reciclar",
    "reciclado": r"reciclad[oa]",
    "refaccionado": r"refaccionad[oa]",
    "excelente_estado": r"excelente estado",
    "muy_buen_estado": r"muy buen estado",
    "buen_estado": r"buen estado"
}

texto_propiedad = (
    df_limpio["Titulo"].fillna("") + " " +
    df_limpio["Descripcion"].fillna("")
)

for estado, patron in terminos_estado.items():
    cantidad = texto_propiedad.str.contains(
        patron,
        case=False,
        regex=True
    ).sum()

    print(f"{estado}: {cantidad}")

a_refaccionar: 195
a_reciclar: 170
reciclado: 713
refaccionado: 454
excelente_estado: 1350
muy_buen_estado: 777
buen_estado: 1163

In [ ]:
mask_necesita_obra = texto_propiedad.str.contains(
    r"a refaccionar|para refaccionar|a reciclar|para reciclar",
    case=False,
    na=False,
    regex=True
)

mask_ya_mejorada = texto_propiedad.str.contains(
    r"reciclad[oa]|refaccionad[oa]",
    case=False,
    na=False,
    regex=True
)

print("Necesita obra:", mask_necesita_obra.sum())
print("Ya reciclada/refaccionada:", mask_ya_mejorada.sum())
print(
    "Aparecen en ambos grupos:",
    (mask_necesita_obra & mask_ya_mejorada).sum()
)

Necesita obra: 335
Ya reciclada/refaccionada: 1104
Aparecen en ambos grupos: 18

In [ ]:
import re

casos_ambiguos = df_limpio[
    mask_necesita_obra & mask_ya_mejorada
]

for _, fila in casos_ambiguos.iterrows():
    texto = str(fila["Titulo"]) + " " + str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,100}(?:refaccion|recicla).{0,120}",
        texto,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])

    for fragmento in fragmentos:
        print("...", fragmento, "...")

================================================================================
ID: 634324
Título: VENTA MONOAMBIENTE A REFACCIONAR EN CABALLITO
... VENTA MONOAMBIENTE A REFACCIONAR EN CABALLITO OPORTUNIDAD INVERSORES | Monoambiente a Reciclar en Caballito  ...
... orización en una de las zonas de mayor demanda de CABA. Ideal para proyecto de Fix & Flip (comprar, refaccionar y revender) o para destinar al mercado de alquiler tradicional o temporario con excelente rentabilidad. ...
... Alta demanda de inquilinos: Los monoambientes refaccionados a nuevo en esta franja de Caballito registran vacancia casi nula. ...

================================================================================
ID: 632258
Título: VENTA 3 AMBIENTES RETIRO
... VENTA 3 AMBIENTES RETIRO DEPARTAMENTO DE 3 AMBIENTES EN VENTA EN RETIRO A RECICLAR, CAPITAL FEDERAL ...
... ctico toilette. Construido en 1970, el inmueble se encuentra en buen estado general, listo para ser refaccionado y adaptado a los gustos y necesidades del nuevo propietario. ...

================================================================================
ID: 631286
Título: VENTA DEPARTAMENTO 3 AMB. CABALLITO CON DEPENDENC
... La cocina y los baños necesitan reciclado, el resto de la unidad está en condiciones aceptables para habitar o iniciar la puesta a punto general. ...
... Ideal para quien busca un buen metraje, muy buena luz y vista, en una unidad con potencial para reciclar a gusto. ...

================================================================================
ID: 628538
Título: Dpto venta 2 amb, balcón. Zona Fac. Medicina.
... ndo Hechas: Cañerías, tendido eléctrico, aberturas con DVH (Doble Vidrio Hermético) y baño completo reciclados a nuevo hace 5 años. ...
... - Cocina Independiente: Con ventana al exterior y espacio para lavarropas (a refaccionar/actualizar en cosmética). ...
... - Baño Completo: Reciclado a nuevo, con acceso exclusivo en suite desde el dormitorio. ...
... iedad con las reformas estructurales caras ya ejecutadas (cañerías, electricidad y DVH), ideal para refaccionar la cosmética a gusto e incorporarla al mercado de renta inmediatamente. ...

================================================================================
ID: 624929
Título: VENTA, DEPTO 3 AMBIENTES A RECICLAR, MONSERRAT
... VENTA, DEPTO 3 AMBIENTES A RECICLAR, MONSERRAT  VENTA DEPARTAMENTO 3 AMBIENTES A RECICLAR, MONSERRAT ...
... DEPARTAMENTO DE 3 AMBIENTES A RECICLAR!!!!! ...
... Oportunidad de Inversión y Reciclado: Depto 3 Ambientes Muy Luminoso ...
... La propiedad requiere un reciclado total, incluyendo la reconexión e instalación completa de los servicios, ya que actualmente no cuenta con suministro  ...

================================================================================
ID: 621640
Título: VENTA DEPARTAMENTO 4 AMBIENTES  NUÑEZ LUMINOSO
... Originalmente de 4 ambientes , fue reciclado y convertido en 3 ambientes con un cómodo family room, generando mayor amplitud y funcionalidad. ...
... Cocina independiente , a refaccionar , equipada con muebles bajo mesada y alacenas. ...

================================================================================
ID: 617484
Título: DEPARTAMENTO VENTA 2 AMBIENTES  VENTA VILLA CRESPO
... Living y dormitorio  amplios con pisos a refaccionar; ...
... Cocina refaccionada a nuevo; ...
... Una propiedad con una base sólida, ideal para quienes buscan invertir, refaccionar y darle valor agregado en una de las zonas más buscadas de la ciudad. ...

================================================================================
ID: 615214
Título: VENTA DPTO 2 AMB AMPLIOS CON VISTA ABIERTA
... Salida directa a balcón interno (a refaccionar) ...
... Cocina independiente reciclada ...

================================================================================
ID: 601316
Título: Semipiso 4 amb c/dep Apto Crédito en Caballito
... El baño principal, el toilette y la cocina fueron reciclados hace aproximadamente 15 años, manteniendo una base funcional y sólida. ...
... Se complementa con lavadero independiente y dependencia de servicio con baño propio, actualmente a refaccionar. ...

================================================================================
ID: 592702
Título: VENTA DPTO 3 AMB VISTA ABIERTA PALERMO OPORTUNIDAD
... OPORTUNIDAD!!! Departamento de 3 ambientes a refaccionar  ...
...  Baño Completo refaccionado con ventilación al exterior. ...
... La propiedad es para actualizar, ideal para quienes buscan refaccionar y darle su estilo propio, aprovechando el gran potencial, la luminosidad y la excelente ubicación. ...

================================================================================
ID: 575594
Título: Venta depto 2 amb Recoleta apto crédito
... Ubicado en un edificio sólido de 1955, esta unidad de 32 m² es una joya a refaccionar. Su disposición de contrafrente te garantiza algo difícil de encontrar en esta zona: paz absoluta y silencio total, l ...
... Inversión inteligente: Comprás a valor de "estado original" en una zona donde el metro cuadrado reciclado se defiende solo. Apto Crédito. ...

================================================================================
ID: 568906
Título: VENTA 2 AMB BALVANERA
... Cocina y baños refaccionados ...
... Piso de madera a refaccionar ...

================================================================================
ID: 568075
Título: VENTA 3 AMBIENTES-BALVANERA -GRAN BALCON
... de 3 Ambientes con GRAN BALCON Corrido al Contrafrente – Muy Luminoso y Silencioso – Baño y Cocina  reciclados - Balvanera ...
...  en un 2° piso contrafrente, este departamento de 3 ambientes ofrece una excelente oportunidad para refaccionar y personalizar a tu gusto. ...

================================================================================
ID: 560918
Título: Departamento 2 Ambientes en Venta San Cristobal
... La propiedad se encuentra a reciclar, requiriendo refacciones generales, especialmente en baños, cocina y actualización estética. Justamente por este motivo, se ofrece a valor de  ...
... 	Gran potencial de valorización post-reciclado ...

================================================================================
ID: 541156
Título: VENTA SEMIPISO A REFACCIONAR BELGRANO CON COCHERA
... VENTA SEMIPISO A REFACCIONAR BELGRANO CON COCHERA VENTA SEMIPISO DE 4 DORMITORIOS A REFACCIONAR EN PISO 14 CON COCHERA FIJA Y AMENITIES. ...
... upo electrógeno y excelentes amenities que incluyen piscina y salón de usos múltiples recientemente refaccionado a nuevo. ...
... - Amenities: Pileta, parrilla y salón de usos múltiples muy amplio y recientemente refaccionado. ...

================================================================================
ID: 524675
Título: DEPTO A RECICLAR VENTA 2AMB RECOLETA BALCON
... DEPTO A RECICLAR VENTA 2AMB RECOLETA BALCON Departamento 2 ambientes al frente con balcón – Recoleta ...
... or. Se ingresa por un amplio hall distribuidor que da acceso a la cocina separada, al baño completo reciclado, y a el ambiente principal que posee generosas dimensiones (6 x 3,50 m), con salida a balcón al frente de 3,5 x 0,90  ...
... El departamento es todo eléctrico y se encuentra semireciclado. ...

================================================================================
ID: 460569
Título: VENTA DEPTO DOS AMB. A REFACCIONAR EN CABALLITO
... VENTA DEPTO DOS AMB. A REFACCIONAR EN CABALLITO 2 Ambientes a Refaccionar con Balcón y Baulera | Ideal Inversión | Caballito / Parque Chacabuco ...
... Departamento de 2 ambientes a refaccionar, ubicado sobre Avenida Directorio, en el límite entre Caballito y Parque Chacabuco, una de las zonas con mayor demand ...
... ión, lo que representa una oportunidad concreta de valorización en una zona donde los departamentos reciclados tienen alta absorción de mercado. Por ubicación y características, resulta apto para reventa post obra, renta tradic ...
... - A refaccionar: margen de mejora y revalorización ...

================================================================================
ID: 427238
Título: VENTA 2 AMB  CABA APT CREDITO
... Necesita reciclado, y modernización, ideal inversor . ...
... Un living comedor que da a un balcón, muy luminoso, y una cocina muy pequeña para reciclar o bien conectar a futuro con el living comedor . ...

In [ ]:
df_limpio["Estado_Propiedad"] = "Sin_clasificar"

df_limpio.loc[
    mask_ya_mejorada,
    "Estado_Propiedad"
] = "Reciclada_refaccionada"

# Necesita obra tiene prioridad si aparecen ambos indicadores
df_limpio.loc[
    mask_necesita_obra,
    "Estado_Propiedad"
] = "Necesita_obra"

df_limpio["Estado_Propiedad"].value_counts()

Estado_Propiedad
Sin_clasificar            8312
Reciclada_refaccionada    1086
Necesita_obra              335
Name: count, dtype: int64

In [ ]:
mask_buen_estado = texto_propiedad.str.contains(
    r"excelente estado|muy buen estado|buen estado",
    case=False,
    na=False,
    regex=True
)

print(
    "Sin clasificar actualmente:",
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar").sum()
)

print(
    "Sin clasificar con indicios de buen estado:",
    (
        (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
        mask_buen_estado
    ).sum()
)

Sin clasificar actualmente: 8312
Sin clasificar con indicios de buen estado: 2008

In [ ]:
mask_asignar_buen_estado = (
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
    mask_buen_estado
)

df_limpio.loc[
    mask_asignar_buen_estado,
    "Estado_Propiedad"
] = "Buen_estado"

df_limpio["Estado_Propiedad"].value_counts()

Estado_Propiedad
Sin_clasificar            6304
Buen_estado               2008
Reciclada_refaccionada    1086
Necesita_obra              335
Name: count, dtype: int64

In [ ]:
terminos_obra_extra = {
    "para_actualizar": r"para actualizar|a actualizar",
    "a_modernizar": r"a modernizar|para modernizar",
    "estado_original": r"estado original",
    "requiere_refaccion": r"requiere refacci[oó]n|requiere refacciones",
    "necesita_refaccion": r"necesita refacci[oó]n|necesita refacciones",
    "para_reformar": r"para reformar|a reformar"
}

mask_sin_clasificar = df_limpio["Estado_Propiedad"] == "Sin_clasificar"

for nombre, patron in terminos_obra_extra.items():
    cantidad = (
        mask_sin_clasificar &
        texto_propiedad.str.contains(
            patron,
            case=False,
            na=False,
            regex=True
        )
    ).sum()

    print(f"{nombre}: {cantidad}")

para_actualizar: 38
a_modernizar: 28
estado_original: 18
requiere_refaccion: 12
necesita_refaccion: 3
para_reformar: 5

In [ ]:
patron_obra_extra = (
    r"para actualizar|a actualizar|"
    r"a modernizar|para modernizar|"
    r"requiere refacci[oó]n|requiere refacciones|"
    r"necesita refacci[oó]n|necesita refacciones|"
    r"para reformar|a reformar"
)

mask_obra_extra = (
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
    texto_propiedad.str.contains(
        patron_obra_extra,
        case=False,
        na=False,
        regex=True
    )
)

print("Nuevas propiedades detectadas como posibles Necesita_obra:",
      mask_obra_extra.sum())

Nuevas propiedades detectadas como posibles Necesita_obra: 83

In [ ]:
import re

muestra_obra_extra = df_limpio.loc[mask_obra_extra].sample(
    min(20, mask_obra_extra.sum()),
    random_state=42
)

for _, fila in muestra_obra_extra.iterrows():
    texto = str(fila["Titulo"]) + " " + str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,100}(?:actualizar|modernizar|refacci[oó]n|refacciones|reformar).{0,120}",
        texto,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])

    for fragmento in fragmentos:
        print("...", fragmento, "...")

================================================================================
ID: 610503
Título: DEPARTAMENTO 5 AMB 2 DORMITORIO Y HAB SERVICIO
... Estado: Excelente potencial para modernizar y jerarquizar en una zona de constante revalorización. ...

================================================================================
ID: 636542
Título: VENTA 3 AMBIENTES VILLA URQUIZA CON PATIO LAVADERO
...  - Baño completo: 1.99 x 1.53 (diseño original, excelente oportunidad para modernizar a gusto). ...

================================================================================
ID: 622998
Título: DEPARTAMENTO 3 AMBIENTES - VENTA - FLORES
... dos gabinetes, otorgando amplia disponibilidad para su uso apto profesional. Como vivienda requiere refacción. La cocina cuenta con doble circulación y eso le da mayor dinamica a los espacio.  ...

================================================================================
ID: 610149
Título: VENTA DEPTO 2 AMB OPORTUNIDAD APTO CRÉDITO PALERMO
... El departamento ofrece una excelente base para actualizar y personalizar a gusto. La cocina requieren refacción, representando una gran oportunidad para poner en valor y adaptar ...

================================================================================
ID: 624590
Título: VENTA PISO 9 /  5 AMB FRENTE A PARQUE RIVADAVIA
... IVADAVIA a  solo dos cuadras del SUBTE LINEA A ESTACION ACOYTE. Una unidad para exigentes. Necesita refacciones para hacerlo una vivienda soñada !!!. ...

================================================================================
ID: 612566
Título: DEPARTAMENTO AL FRENTE. PISO ALTO
... Departamento de 34 metros cuadrados cubiertos y totales a actualizar. ...

================================================================================
ID: 632527
Título: Venta Depto 2 amb San Nicolás a modernizar
... Venta Depto 2 amb San Nicolás a modernizar Departamento en venta de 2 ambientes emplazado en un piso 7, interno, y ubicado en el barrio de San Nicolás sobre la ca ...

================================================================================
ID: 583587
Título: DEPARTAMENTO  4 AMBIENTES C/DEP VENTA BALVANERA
... Para actualizar. gran potencial, muy amplio y luminoso. gran balcón corrido sobre calle Castelli y otro balcón por calle Perón. ...
... ESTADO DE LA UNIDAD: Necesita  mejoras en baños, cocina y dependencias. (actualizar, esta de epoca) ...

================================================================================
ID: 634220
Título: VENTA DEPART 3 AMB C/COCHERA Y BAULERA V.SARSFIELD
... o presenta algunos detalles estéticos y de mantenimiento, ofreciendo una excelente oportunidad para actualizar y personalizar con gran potencial de revalorización. ...

================================================================================
ID: 630185
Título: VENTA-2 AMB.-C/BALCÓN-52m2 -LAS CAÑITAS-PALERMO
... •Cocina independiente: Espacio cómodo y funcional para actualizar según tus necesidades de diseño. ...
... •Baño: Completo, ideal para modernizar. ...

================================================================================
ID: 587155
Título: VENTA DEPARTAMENTO MONOAMBIENTE MONSERRAT
... •	Cocina: Cómoda y funcional, ideal para actualizarla con un diseño minimalista (¡mirá el cambio proyectado en las imágenes!). ...

================================================================================
ID: 607345
Título: VENTA DEPTO 4 AMBIENTES BALCÓN APTO PROF
... NECESITA REFACCIONES ...

================================================================================
ID: 553928
Título: VENTA DEPARTAMENTO 4 AMBIENTES VILLA URQUIZA
... Unidad de cuatro ambientes con tres dormitorios amplios, baño completo, toilette y balcón. Requiere refacciones integrales, ideal para invertir o reformar a gusto y aumentar su valor. ...

================================================================================
ID: 606938
Título: VENTA DEPARTAMENTO TRES AMBIENTES EN BELGRANO
... La cocina integrada, separada por una barra desayunadora (ideal para modernizar y hacer un concepto abierto) y con ventilación natural. ...

================================================================================
ID: 552542
Título: Departamento en venta Balvanera  - Semipiso
... taca por su distribución funcional, ambientes bien definidos y una estructura sólida, perfecta para modernizar y adaptar a tu estilo. ...

================================================================================
ID: 593140
Título: Venta Balvanera 4 Amb de estilo balcón al frente
... La planta es funcional y versátil, ideal para modernizar respetando el estilo original o realizar una actualización integral que revalorice la propiedad. ...

================================================================================
ID: 511218
Título: Semipiso Venta 152m²  Belgrano Gran Balcón Terraza
...  sólida y ambientes bien definidos, brindando una excelente base para una modernización que permita actualizarla y personalizarla, potenciando aún más sus cualidades. Cocina independiente con lavadero separado, pisos de madera y c ...

================================================================================
ID: 559609
Título: VENTA DEPARTAMENTO 4 AMBIENTES FLORESTA
... Esta propiedad ofrece un excelente potencial para modernizarla a tu gusto, creando un espacio cómodo y acogedor donde puedas disfrutar en familia. ...

================================================================================
ID: 580738
Título: VENTA DEPARTAMENTO 3 AMB. DEPEN Y BAULERA RECOLETA
... ca – Av. Santa Fe al 1400 -3 AMBIENTES C / DEPENDENCIA Y BAULERA - PISO 11 AL FRENTE - LUMINOSO - A MODERNIZAR. ...
... Dependencia de servicio con baño completo en suite, de epoca a modernizar. ...
... Dos baños completos amplios de epoca a modernizar. ...

================================================================================
ID: 599980
Título: DPTO VENTA 3 AMB + DEP BALVANERA APTO CRÉDITO.
... mbientes amplios, excelente luminosidad y una ubicación estratégica. Una muy buena oportunidad para actualizar sus espacios y adaptarlos a tu estilo, aprovechando al máximo cada uno de sus metros. ...
... scás una oportunidad con metros reales, excelente distribución, mucha luz natural y el potencial de actualizarla a tu gusto, este departamento merece una visita. ...

In [ ]:
df_limpio.loc[
    mask_obra_extra,
    "Estado_Propiedad"
] = "Necesita_obra"

df_limpio["Estado_Propiedad"].value_counts()

Estado_Propiedad
Sin_clasificar            6221
Buen_estado               2008
Reciclada_refaccionada    1086
Necesita_obra              418
Name: count, dtype: int64

In [ ]:
mask_estado_original = (
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
    texto_propiedad.str.contains(
        r"estado original",
        case=False,
        na=False,
        regex=True
    )
)

print("Casos en estado original:", mask_estado_original.sum())

df_limpio.loc[
    mask_estado_original,
    ["ID", "Titulo", "Antiguedad", "Barrio", "Precio_Valor"]
]

Casos en estado original: 15

,ID,Titulo,Antiguedad,Barrio,Precio_Valor
754,633630,VENTA 3 AMBIENTES C/DEP - ALMAGRO,66.0,Almagro,119900.0
1075,630796,VENTA PISO COMPLETO 4 AMB C/GUARDACOCHE ALMAGRO,44.0,Almagro,224000.0
2253,620386,Caballito Residencial Venta - Piso 5 amb c/coch,19.0,Caballito,462000.0
3169,611305,Departamento ideal para empezar a ser propiet...,59.0,Parque Chacabuco,59000.0
3445,608510,4 AMBIENTES MAS DEPENDENCIA Y GUARDACOCHE ALMAGRO,44.0,Almagro,224000.0
4229,600764,DEPARTAMENTO VENTA 2 AMBIENTES TERRAZA AGRONOMIA,51.0,Agronomía,75000.0
4755,594463,Venta Depto 2 Amb Balcón Excelente Zona Barracas,26.0,Barracas,55000.0
5392,587604,VENTA 2 AMB PLAZA FLORES SUBTE TREN BALCÓN,61.0,Flores,59900.0
5907,581223,VENTA DEPARTAMENTO 2 AMB. PB A/CRÉDITO VILLA M...,66.0,Villa General Mitre,68000.0
6131,577816,Venta Depto 3 Amb Piso alto Apto Crédito,66.0,Villa del Parque,89000.0
6771,566698,Venta Departamento 3 ambientes C/Balcon al frente,56.0,Caballito Sur,130000.0
7072,560753,Dpto 3 amb en VENTA en VILLA DEVOTO Bajas expe...,76.0,Villa Devoto,79000.0
7310,555881,Departamento en Venta Retiro,47.0,Retiro,62000.0
8052,536371,VENTA 4 AMBIENTES RECOLETA RENOVADO SOL BALCON,63.0,Recoleta,530000.0
9079,475521,DEPTO 3 AMB + ESCRITORIO - APTO CRÉDITO,50.0,Villa General Mitre,79000.0

In [ ]:
import re

for _, fila in df_limpio.loc[mask_estado_original].iterrows():
    texto = str(fila["Titulo"]) + " " + str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,120}estado original.{0,150}",
        texto,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])

    for fragmento in fragmentos:
        print("...", fragmento, "...")

================================================================================
ID: 633630
Título: VENTA 3 AMBIENTES C/DEP - ALMAGRO
... El departamento se encuentra en estado original, tiene mucho potencial realizando una actualizacion,  distribuye de la siguiente manera: ...

================================================================================
ID: 630796
Título: VENTA PISO COMPLETO 4 AMB C/GUARDACOCHE ALMAGRO
... El departamento se encuentra en estado original, construido en 1982 con materiales de excelente calidad, destacándose por su estructura sólida y ambientes amplios, difíciles de encontrar en desarro ...

================================================================================
ID: 620386
Título: Caballito Residencial Venta - Piso 5 amb c/coch
... Edificio de 1995 – Estado original conservado ...
... El edificio fue construido en 1995 y se encuentra en estado original, conservado. Tiene un departamento por piso y un total de siete plantas. La unidad se complementa con cochera cubierta y baulera en el subsuelo. ...

================================================================================
ID: 611305
Título: Departamento ideal para empezar  a ser propietario
... r un  durlock  lo que genera un tercer dormitorio, lo ofrece un espacio más, que puede ser utilizado o bien volverlo al estado original y convertirlo en 2 dormitorios. ...

================================================================================
ID: 608510
Título: 4 AMBIENTES MAS DEPENDENCIA Y GUARDACOCHE ALMAGRO
... El departamento se encuentra en estado original, construido en 1982 con materiales de excelente calidad, destacándose por su estructura sólida y ambientes amplios, difíciles de encontrar en desarro ...

================================================================================
ID: 600764
Título: DEPARTAMENTO VENTA 2 AMBIENTES TERRAZA AGRONOMIA
... El baño completo, en estado original y muy cuidado, incluye bañera y brinda funcionalidad y confort. La habitación posee un amplio placard de guardado, optimizando el espacio y la organi ...

================================================================================
ID: 594463
Título: Venta Depto 2 Amb Balcón Excelente Zona Barracas
... El departamento se encuentra en estado original y ofrece una excelente oportunidad para renovarlo y adaptarlo a tu gusto. Con una actualización de pintura y del mobiliario de cocina, posee un gran  ...

================================================================================
ID: 587604
Título: VENTA 2 AMB PLAZA FLORES SUBTE TREN BALCÓN
... Departamento 2 ambientes, LATERAL/CONTRAFRENTE. Se encuentra en estado original. ...

================================================================================
ID: 581223
Título: VENTA DEPARTAMENTO 2 AMB. PB A/CRÉDITO VILLA MITRE
... Su ubicación en Villa General Mitre y estado original representan una oportunidad de valorización. Perfecto para: ...

================================================================================
ID: 577816
Título: Venta Depto 3 Amb Piso alto Apto Crédito
... Cocina y Baño: Ambos sectores se encuentran en su estado original, pero conservados en impecables condiciones de mantenimiento, higiene y prolijidad.  ...

================================================================================
ID: 566698
Título: Venta Departamento 3 ambientes C/Balcon al frente
... partamento de 3 ambientes al frente con orientación norte sobre Avenida Rivadavia al 4600. La propiedad se encuentra en estado original y cuenta con doble entrada, principal y de servicio. ...

================================================================================
ID: 560753
Título: Dpto 3 amb en VENTA en VILLA DEVOTO Bajas expensas
...  combina lo residencial del barrio con el confort de una propiedad remodelada. La unidad fue actualizada respecto de su estado original, destacándose especialmente su cocina renovada con un estilo moderno y funcional. A pocas cuadras de la emblemática Plaza Arenales y rodeado de una c ...

================================================================================
ID: 555881
Título: Departamento en Venta Retiro
... La unidad se encuentra en estado original, con posibilidad de actualización. ...

================================================================================
ID: 536371
Título: VENTA 4 AMBIENTES RECOLETA RENOVADO SOL BALCON
... * 3 baños completos: uno renovado, otro en estado original y luego el baño de servicio. ...

================================================================================
ID: 475521
Título: DEPTO 3 AMB + ESCRITORIO - APTO CRÉDITO
... El depto se encuentra en estado original con cocina y baño de época. Edificio de 1976. ...

In [ ]:
df_limpio.loc[
    df_limpio["Estado_Propiedad"] != "Sin_clasificar"
].groupby("Estado_Propiedad")["Precio_m2_Total"].agg(
    ["count", "mean", "median", "std"]
).round(2)

                        count     mean   median     std
Estado_Propiedad
Buen_estado              2008  2006.21  1946.96  632.03
Necesita_obra             418  1595.78  1546.54  572.13
Reciclada_refaccionada   1086  2192.77  2122.35  687.55

In [ ]:
amenities_interes = [
    "Balcón",
    "Ascensor",
    "Pileta",
    "Terraza",
    "Parrilla",
    "SUM",
    "Seguridad",
    "Gimnasio",
    "Baulera",
    "Patio",
    "Laundry",
    "Aire Acondicionado"
]

for amenity in amenities_interes:
    cantidad = df_limpio["Amenities"].fillna("").str.contains(
        amenity,
        case=False,
        regex=False
    ).sum()

    print(f"{amenity}: {cantidad}")

Balcón: 4896
Ascensor: 3963
Pileta: 1246
Terraza: 1332
Parrilla: 1112
SUM: 1085
Seguridad: 1017
Gimnasio: 648
Baulera: 956
Patio: 929
Laundry: 831
Aire Acondicionado: 2854

In [ ]:
amenities_freq = (
    df_limpio["Amenities"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
    .value_counts()
)

amenities_freq.head(30)

Amenities
Baño                             6841
Dormitorio                       6676
Cocina                           5617
Balcón                           4896
Electricidad                     4843
Living/Comedor                   4497
Placard                          4338
Ascensor                         3923
Gas                              3900
Living                           3891
Agua                             3829
Lavadero                         3318
Comedor                          3031
Aire Acondicionado               2854
Agua Corriente                   2839
Cocina/Comedor                   2623
Disposición Frente               2398
Desague Cloacal                  2357
Toilet                           2158
Pileta                           1786
Permite Mascotas                 1778
Internet                         1451
Terraza                          1332
Disposición Contrafrente         1291
ComYAmenCalefacción              1153
Parrilla                         1112
Salón de usos múltiples - SUM    1085
Habitación de Servicio           1060
Seguridad                        1017
Portón Automático                 972
Name: count, dtype: int64

In [ ]:
amenities_freq.iloc[30:]

Amenities
Vestidor                          970
Televisión por Cable              957
Baulera                           956
Patio                             929
Solarium                          862
Laundry                           831
Agua Potable                      779
Desayunador                       756
Orientación Norte                 705
Orientación Este                  700
Losa Radiante                     671
Gimnasio                          648
Teléfono                          603
Recepción                         576
Otro                              536
Caldera                           498
Orientación Oeste                 492
Estudio                           453
Áreas Verdes                      415
Apto Turístico                    383
Disposición Interno               352
Disposición Lateral               352
Sala de reuniones                 326
Orientación Noreste               326
Acceso de cochera, Rampa fija     321
Orientación Noroeste              319
Televisión Satelital              297
Jardín                            289
Acceso de cochera, Horizontal     288
Quincho                           246
Orientación Sur                   215
Área de juegos infantiles         203
Sauna                             196
Lobby                             187
Playroom                          178
Acceso de cochera, Ascensor       178
Business Center                   160
Alarma                            150
Hidromasaje                       150
Orientación Suroeste              150
Orientación Sureste               149
Amoblado                          147
Pileta Climatizada                143
Estacionamiento para visitas      124
Agua Dulce                        112
Pileta Cubierta                   100
Deck                               74
Altillo                            51
Jardín de Invierno                 45
Bar                                43
Acceso de cochera, Rampa móvil     41
Área de Cine                       39
Sótano                             39
Chimenea                           30
Biblioteca                         30
Cisterna                           27
Valet Parking                      16
Cancha de tenis                    14
Cancha de Paddle                   10
Cancha de futbol                   10
Camino Natural                      7
Cancha de Basquetbol                6
Galpón                              5
Alambrado                           4
Bodegas                             4
Name: count, dtype: int64

In [ ]:
texto_propiedad.str.contains(
    r"\bcochera\b|\bgarage\b|\bgaraje\b",
    case=False,
    na=False,
    regex=True
).sum()

np.int64(2087)

In [ ]:
mask_cochera = texto_propiedad.str.contains(
    r"\bcochera\b|\bgarage\b|\bgaraje\b",
    case=False,
    na=False,
    regex=True
)

muestra_cochera = df_limpio.loc[
    mask_cochera,
    ["ID", "Titulo", "Descripcion"]
].sample(20, random_state=42)

for _, fila in muestra_cochera.iterrows():
    texto = str(fila["Titulo"]) + " " + str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,100}(?:cochera|garage|garaje).{0,120}",
        texto,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])

    for fragmento in fragmentos[:3]:
        print("...", fragmento, "...")

================================================================================
ID: 577599
Título: VENTA DEPARTAMENTO 4 AMBIENTES BELGRANO COCHERA
... VENTA DEPARTAMENTO 4 AMBIENTES BELGRANO COCHERA Excelente semipiso de cuatro ambientes con dependencia y cochera fija, en torre de categoría – Belgrano ...
... Completa la propiedad una baulera y una cochera fija, muy amplia, palier privado y hall de entrada. ...

================================================================================
ID: 532780
Título: VENTA DEPTO 3 AMBIENTES VILLA DEL PARQUE C/COCHERA
... VENTA DEPTO 3 AMBIENTES VILLA DEL PARQUE C/COCHERA DEPARTAMENTO 3 AMBIENTES VILLA DEL PARQUE CAPITAL FEDERAL - APTO CRÉDITO ...
... encuentran: balcón corrido, radiadores con caldera dual individual, aire acondicionado frío-calor y cochera fija con portón eléctrico. El edificio, construido en 2008, dispone de sector de parrilla en terraza y amenities como a ...

================================================================================
ID: 625109
Título: VENTA 3 AMB. CON COCHERA Y BAULERA ALMAGRO
... VENTA 3 AMB. CON COCHERA Y BAULERA ALMAGRO VENTA DE DEPARTAMENTO DE CATEGORIA UBICADO EN LA TORRE PLAZA LEZICA ...
... COCHERA CUBIERTA AMPLIA DE 18M2 ...

================================================================================
ID: 616294
Título: Venta depto 4 amb  Flores cochera baulera  pileta
... Venta depto 4 amb  Flores cochera baulera  pileta Estilo, amplitud, luminoso y confort, semipiso de 116mt2  con cochera, baulera, pileta una propiedad pe ...

================================================================================
ID: 536047
Título: Venta depto 3 amb en Palermo jardín full amenities
... • Cochera no incluida. ...

================================================================================
ID: 602030
Título: VENTA BELGRANO DÚPLEX 5 AMBIENTES COCHERA y PILETA
... VENTA BELGRANO DÚPLEX 5 AMBIENTES COCHERA y PILETA Venta Dúplex 5 Ambientes con Cochera y Pileta | 123 m² | Belgrano  ...
... Cuenta con 4 dormitorios, cochera fija cubierta, pileta de uso común del edificio y una distribución tipo casa que permite disfrutar cómodamente cada amb ...
... • Cochera fija cubierta ...

================================================================================
ID: 630151
Título: VENTA 2 AMBIENTES AL FRENTE CON AMENITIES
... • Cochera incluida, resolviendo la necesidad de estacionamiento ...

================================================================================
ID: 513225
Título: VENTA 3 AMBIENTES CON COCHERA Y BAULERA BALVANERA
... VENTA 3 AMBIENTES CON COCHERA Y BAULERA BALVANERA Esta unidad es, lo que nosotros llamamos, una "joya estructural". Te cuento por qué: ...
...  * Cochera propia: Unidad complementaria de aprox. 12 m² en el 1er subsuelo. ¡Llegar y estacionar es calidad de vida! ...
...  * Expensas: $210.000 (Incluyen el departamento, la cochera y la baulera). Un valor muy competitivo considerando los servicios centrales y el personal del edificio. ...

================================================================================
ID: 614873
Título: VENTA PALERMO CHICO PISO DOS SUITES COCHERA BALCON
... VENTA PALERMO CHICO PISO DOS SUITES COCHERA BALCON VENTA PALERMO CHICO PISO DOS SUITES COCHERA BALCON ...
... Departamento de alto diseño en Palermo Chico con cochera, palier privado y dependencia ...
... El edificio cuenta con encargado con vivienda, ascensor, portón automático y cochera fija incluida, con cómodo acceso por rampa. ...

================================================================================
ID: 637006
Título: VENTA DEPTO 4 AMBIENTES CON COCHERA BALCON ALMAGRO
... VENTA DEPTO 4 AMBIENTES CON COCHERA BALCON ALMAGRO DEPARTAMENTO 4 AMBIENTES CON COCHERA Y BALCON EN ALMAGRO en el LIMITE CON VILLA CRESPO.  ...
... Cochera fija y cubierta en PB. incluida en el precio ...

================================================================================
ID: 541156
Título: VENTA SEMIPISO A REFACCIONAR BELGRANO CON COCHERA
... VENTA SEMIPISO A REFACCIONAR BELGRANO CON COCHERA VENTA SEMIPISO DE 4 DORMITORIOS A REFACCIONAR EN PISO 14 CON COCHERA FIJA Y AMENITIES. ...
... Semipiso de 5 ambientes super luminoso, con cochera FIJA, baulera y amenities. ...
... Cochera fija con muy buen acceso!! , baulera adicional y parrilla comunitaria. ...

================================================================================
ID: 563951
Título: VENTA PISO DÚPLEX 4 AMB TERRAZA COCHERA BELGRANO
... VENTA PISO DÚPLEX 4 AMB TERRAZA COCHERA BELGRANO VENTA DUPLEX 4 AMBIENTES CON TERRAZA Y PARRILLA - PISO EXCLUSIVO - BELGRANO  ...
... Si bien el edificio no posee cocheras, la venta incluye una cochera propia ubicada en las inmediaciones, lo que brinda una solución práctica para estacionamiento en la zona. ...

================================================================================
ID: 511377
Título: VENTA DEPARTAMENTO SEIS AMBIENTES FLORES  COCHERA
... VENTA DEPARTAMENTO SEIS AMBIENTES FLORES  COCHERA DEPARTAMENTO 4 AMBIENTES FLORES CARACAS CAPITAL FEDERAL - APTO CRÉDITO ...
... El inmueble incluye dos cocheras, elemento diferencial en zonas céntricas. Edificio con amenities que agregan valor, entre ellos SUM en último piso con ...

================================================================================
ID: 635444
Título: VENTA DEPTO 2 AMBIENTES PALERMO BALCON COCHERA
... VENTA DEPTO 2 AMBIENTES PALERMO BALCON COCHERA VENTA DEPARTAMENTO 2 AMBIENTES CON COCHERA Y AMPLIO BALCÓN CON PARRILLA – PALERMO ...
... Excelente departamento de 2 ambientes con cochera, amplio balcón y parrilla, ubicado en una de las zonas residenciales más buscadas de Palermo, sobre Bondpland al 1800. ...
... Cochera, un diferencial muy importante en esta ubicación. ...

================================================================================
ID: 595910
Título: venta BALVANERA 2 ambientes APTO CREDITO estrenar
... Posibilidad de comprar cochera en el mismo edificio. ...

================================================================================
ID: 604179
Título: Dpto a reciclar de 3 ambientes en Parque Patricios
... El edificio, construido en 1970, cuenta con 15 pisos, tótem de seguridad en la entrada y cochera (opción de alquiler). . La ubicación sobre Avenida Vélez Sarsfield ofrece excelente accesibilidad a transporte público, ...

================================================================================
ID: 603204
Título: Departamento 4 Ambientes VENTA Palermo Cochera
... Departamento 4 Ambientes VENTA Palermo Cochera Departamento de 4 Ambientes con Dependencia de Servicio - 2 Cocheras - Baulera ...
... - 2 Cocheras Fijas ...

================================================================================
ID: 549244
Título: 3 ambientes con cochera en Monte Castro
... 3 ambientes con cochera en Monte Castro  Hermoso 3 ambientes con cochera en Monte Castro ...

================================================================================
ID: 587335
Título: VENTA DE DEPARTAMENTO EN DEVOTO COCHERA CUBIERTA
... VENTA DE DEPARTAMENTO EN DEVOTO COCHERA CUBIERTA DEPARTAMENTO 3 AMBIENTES EN VENTA EN VILLA DEVOTO, CAPITAL FEDERAL, COCHERA FIJA Y CUBIERTA ...
... avehiculo, y servicio de agua en caso de corte de energía, una persona de limpieza sin vivienda. La cochera incluida suma valor a la propiedad. ...
... - Ascensor, cochera en 1 subsuelo por montavehiculo, generador eléctrico ...

================================================================================
ID: 601541
Título: DEPARTAMENTO 6 AMB VENTA PALERMO BALCONES COCHERA
... DEPARTAMENTO 6 AMB VENTA PALERMO BALCONES COCHERA DEPARTAMENTO 6 AMBIENTES EN VENTA PALERMO AVENIDA CABILDO CAPITAL FEDERAL ...
... • Cochera guardacoches fijo incluido ...

In [ ]:
patron_cochera_no_incluida = (
    r"cochera[s]?\s+no\s+incluida[s]?|"
    r"cochera[s]?\s+opcional(?:es)?|"
    r"posibilidad\s+de\s+(?:comprar|adquirir|alquilar)\s+(?:una\s+)?cochera|"
    r"cochera[s]?\s*\(opci[oó]n\s+de\s+alquiler\)"
)

mask_cochera_no_incluida = (
    mask_cochera &
    texto_propiedad.str.contains(
        patron_cochera_no_incluida,
        case=False,
        na=False,
        regex=True
    )
)

print("Menciones totales de cochera:", mask_cochera.sum())
print("Cochera no incluida / opcional:", mask_cochera_no_incluida.sum())
print("Posibles cocheras incluidas:", (mask_cochera & ~mask_cochera_no_incluida).sum())

Menciones totales de cochera: 2087
Cochera no incluida / opcional: 154
Posibles cocheras incluidas: 1933

In [ ]:
muestra_cochera_excluida = df_limpio.loc[
    mask_cochera_no_incluida,
    ["ID", "Titulo", "Descripcion"]
].sample(20, random_state=42)

for _, fila in muestra_cochera_excluida.iterrows():
    texto = str(fila["Titulo"]) + " " + str(fila["Descripcion"])

    fragmentos = re.findall(
        r".{0,100}(?:cochera|garage|garaje).{0,130}",
        texto,
        flags=re.IGNORECASE
    )

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])

    for fragmento in fragmentos[:4]:
        print("...", fragmento, "...")

================================================================================
ID: 628432
Título: Venta depto 3 amb estrenar San Cristobal amenities
... Cochera opcional no incluida en el valor de publicación.  ...

================================================================================
ID: 567068
Título: VENTA DTO 4AMB PATIO-BALCON-JACUZZI. COCHERA
... VENTA DTO 4AMB PATIO-BALCON-JACUZZI. COCHERA DEPARTAMENTO 4 AMBIENTES EN VENTA VILLA DEVOTO CON BALCÓN, PATIO Y JACUZZI.  ...
... EDIFICIO CON COCHERA ...
... e calefacción por losa radiante con caldera Peisa asegura confort durante todo el año. El acceso de cochera facilita la circulación vehicular, y la cochera opcional suma practicidad a la vida cotidiana. ...

================================================================================
ID: 130467
Título: VENTA DEPTO 2 AMB FULL AMENITIES EN VILLA URQUIZA
... - Cochera opcional (no incluido en el valor) ...
... -Cocheras de cortesía ...
... - Cocheras: Acceso por rampa. Ubicadas en subsuelos ...

================================================================================
ID: 545832
Título: Venta depto 4 amb en San Cristobal full amenities
... Cochera opcional no incluida en el valor de publicación.  ...

================================================================================
ID: 536668
Título: DEPARTAMENTO 4 AMBIENTES VENTA EN CABALLITO
... Cuenta con cochera opcional.  ...

================================================================================
ID: 597743
Título: Venta departamento dos ambientes caballito
... es y remotos. Terminaciones de calidad.. Anafes, hornos, griferías de primera marca.  Posibiliad de cochera fija y cubierta. Para vivir la vida como vos queres. Pedí una visita. Te esperamos. ...
... COCHERA OPCIONAL  USD 25.000.- ...

================================================================================
ID: 626626
Título: DPTO EN VENTA 3 AMB Y MEDIO EN ALMAGRO IMPECABLE!
... La propiedad no cuenta con cochera propia, pero existe la posibilidad de alquilar cochera en garages ubicados sobre Pasaje Rauch y también sobre calle Lavalle. ...

================================================================================
ID: 603047
Título: VENTA SEMIPISO 3 AMB C/FRENTE VILLA DEL PARQUE
... COCHERA OPCIONAL  ...

================================================================================
ID: 611102
Título: Venta depto 3 amb estrenar San Cristóbal amenities
... Cochera opcional no incluida en el valor de publicación.  ...

================================================================================
ID: 601314
Título: Venta Monoambiente Palermo amoblado balcón 37 m2
... Ascensor, terraza, piscina, parrilla, y posibilidad de adquirir una cochera en el mismo edificio. Solo 2 Unidades Funcionales (Dptos. por piso) ...

================================================================================
ID: 583471
Título: VENTA DEPARTAMENTO 2 AMB VILLA SANTA RITA CREDITO
... + POSIBILIDAD DE ALQUILAR COCHERAS EN EL EDIFICIO. ...
... do frío/calor, cerradura electrónica para mayor comodidad y seguridad, y la posibilidad de alquilar cochera dentro del edificio. ...

================================================================================
ID: 463036
Título: VENTA 2 AMB VILLA DEVOTO CON DISEÑO ENTREGA 2028
... • Cochera opcional: USD 28.000 ...

================================================================================
ID: 625453
Título: VENTA DEPARTAMENTO PALERMO CHICO 3 AMBIENTES
... Posibilidad de alquilar cochera en la cuadra. ...

================================================================================
ID: 377936
Título: Venta Depto 2 amb balcón y terraza Montecastro
... - Posibilidad de comprar con cochera (a partir de U$S 18.000) - ...
... - Cochera opcional (no incluido en el valor) ...

================================================================================
ID: 580918
Título: DEPTO 2 AMB  ESTRENAR NUÑEZ  PILETA  GYM Y SUM
... POSIBILIDAD DE COMPRAR COCHERA. ...

================================================================================
ID: 574420
Título: VENTA MONOAMB TIPO 2 AMB COMPLEJO DEVOTO AMENITIES
... Existe la posibilidad de adquirir cochera y baulera dentro del complejo de manera opcional (no incluidas en  ...

================================================================================
ID: 520865
Título: Venta Depto 2 amb balcón y terraza Montecastro
... - Posibilidad de comprar con cochera (a partir de U$S 18.000) - ...
... - Cochera opcional (no incluido en el valor) ...

================================================================================
ID: 631565
Título: Venta departamento,4 ambientes,Caballito, A/Credit
... Posibilidad de alquilar cochera en el edificio ...

================================================================================
ID: 634389
Título: VENTA 3 AMBIENTES piso 7VILLA DEL PARQUE AMENITIES
... Existe la posibilidad de adquirir cochera en el subsuelo. ...

================================================================================
ID: 536041
Título: Venta depto 4 amb en Palermo full amenities
... • Cochera no incluida. ...

In [ ]:
df_limpio["Tiene_Cochera"] = 0

df_limpio.loc[
    mask_cochera & ~mask_cochera_no_incluida,
    "Tiene_Cochera"
] = 1

df_limpio["Tiene_Cochera"].value_counts()

Tiene_Cochera
0    7800
1    1933
Name: count, dtype: int64

In [ ]:
amenities_binarias = {
    "Tiene_Balcon": "Balcón",
    "Tiene_Ascensor": "Ascensor",
    "Tiene_Terraza": "Terraza",
    "Tiene_Parrilla": "Parrilla",
    "Tiene_SUM": "Salón de usos múltiples - SUM",
    "Tiene_Seguridad": "Seguridad",
    "Tiene_Aire_Acondicionado": "Aire Acondicionado",
    "Tiene_Baulera": "Baulera",
    "Tiene_Patio": "Patio",
    "Tiene_Laundry": "Laundry",
    "Tiene_Gimnasio": "Gimnasio",
    "Tiene_Solarium": "Solarium"
}

amenities_lista = df_limpio["Amenities"].fillna("").str.split("|")

for nueva_columna, amenity in amenities_binarias.items():
    df_limpio[nueva_columna] = amenities_lista.apply(
        lambda x: int(amenity in [a.strip() for a in x])
    )

df_limpio[list(amenities_binarias.keys())].sum().sort_values(ascending=False)

Tiene_Balcon                4896
Tiene_Ascensor              3923
Tiene_Aire_Acondicionado    2854
Tiene_Terraza               1332
Tiene_Parrilla              1112
Tiene_SUM                   1085
Tiene_Seguridad             1017
Tiene_Baulera                956
Tiene_Patio                  929
Tiene_Solarium               862
Tiene_Laundry                831
Tiene_Gimnasio               648
dtype: int64

In [ ]:
tipos_pileta = [
    "Pileta",
    "Pileta Climatizada",
    "Pileta Cubierta"
]

df_limpio["Tiene_Pileta"] = amenities_lista.apply(
    lambda x: int(
        any(
            amenity.strip() in tipos_pileta
            for amenity in x
        )
    )
)

df_limpio["Tiene_Pileta"].value_counts()

Tiene_Pileta
0    8487
1    1246
Name: count, dtype: int64

In [ ]:
columnas_binarias = [
    "Tiene_Cochera",
    "Tiene_Balcon",
    "Tiene_Ascensor",
    "Tiene_Aire_Acondicionado",
    "Tiene_Terraza",
    "Tiene_Parrilla",
    "Tiene_SUM",
    "Tiene_Seguridad",
    "Tiene_Baulera",
    "Tiene_Patio",
    "Tiene_Solarium",
    "Tiene_Laundry",
    "Tiene_Gimnasio",
    "Tiene_Pileta"
]

for col in columnas_binarias:
    print(
        col,
        "| valores:", sorted(df_limpio[col].unique()),
        "| nulos:", df_limpio[col].isna().sum(),
        "| con amenity:", df_limpio[col].sum()
    )

Tiene_Cochera | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1933
Tiene_Balcon | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 4896
Tiene_Ascensor | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 3923
Tiene_Aire_Acondicionado | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 2854
Tiene_Terraza | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1332
Tiene_Parrilla | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1112
Tiene_SUM | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1085
Tiene_Seguridad | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1017
Tiene_Baulera | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 956
Tiene_Patio | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 929
Tiene_Solarium | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 862
Tiene_Laundry | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 831
Tiene_Gimnasio | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 648
Tiene_Pileta | valores: [np.int64(0), np.int64(1)] | nulos: 0 | con amenity: 1246

In [ ]:
df_limpio[["Latitud", "Longitud"]].describe()

           Latitud     Longitud
count  9733.000000  9733.000000
mean    -34.603160   -58.436807
std       0.160141     0.119463
min     -49.993622   -68.921819
25%     -34.620000   -58.464293
50%     -34.602754   -58.435593
75%     -34.583935   -58.405415
max     -33.897777   -55.711670

In [ ]:
mask_coord_fuera_caba = ~(
    df_limpio["Latitud"].between(-34.75, -34.50) &
    df_limpio["Longitud"].between(-58.55, -58.30)
)

print("Coordenadas fuera del rango de CABA:", mask_coord_fuera_caba.sum())

df_limpio.loc[
    mask_coord_fuera_caba,
    ["ID", "Titulo", "Barrio", "Ubicacion", "Latitud", "Longitud"]
]

Coordenadas fuera del rango de CABA: 5

,ID,Titulo,Barrio,Ubicacion,Latitud,Longitud
7702,546854,DEPARTAMENTO VENTA CABALLITO GOYENA PISO 260M2,Caballito,"Caballito, Capital Federal",-34.582786,-58.564961
9310,436947,venta 2 ambientes en Piedrabuena,Villa Lugano,"Villa Lugano, Capital Federal",-49.993622,-68.921819
9462,383517,-Departamento 2 AMBIENTES EN FLORESTA,Floresta,"Floresta, Capital Federal",-36.297418,-55.711670
9533,350785,-Departamento 2 AMBIENTES EN FLORESTA,Floresta,"Floresta, Capital Federal",-36.297418,-55.711670
9661,200500,3 Ambientes con Dependencia Gran Jardín Caballito,Caballito,"Caballito, Capital Federal",-33.897777,-58.161621

In [ ]:
df_limpio.loc[
    mask_coord_fuera_caba,
    ["ID", "Titulo", "Direccion", "Barrio", "Ubicacion", "Latitud", "Longitud"]
]

,ID,Titulo,Direccion,Barrio,Ubicacion,Latitud,Longitud
7702,546854,DEPARTAMENTO VENTA CABALLITO GOYENA PISO 260M2,Avenida Pedro Goyena 1500,Caballito,"Caballito, Capital Federal",-34.582786,-58.564961
9310,436947,venta 2 ambientes en Piedrabuena,Pasaje Goleta Santa Cruz 6500,Villa Lugano,"Villa Lugano, Capital Federal",-49.993622,-68.921819
9462,383517,-Departamento 2 AMBIENTES EN FLORESTA,San Nicolas 400,Floresta,"Floresta, Capital Federal",-36.297418,-55.711670
9533,350785,-Departamento 2 AMBIENTES EN FLORESTA,San Nicolas 400,Floresta,"Floresta, Capital Federal",-36.297418,-55.711670
9661,200500,3 Ambientes con Dependencia Gran Jardín Caballito,Rivadavia 5900,Caballito,"Caballito, Capital Federal",-33.897777,-58.161621

In [ ]:
import numpy as np

# Coordenadas detectadas como incorrectas para propiedades ubicadas en CABA.
# Se conservan las propiedades y se dejan las coordenadas como NaN
# para corregirlas posteriormente mediante geocodificación.

df_limpio.loc[
    mask_coord_fuera_caba,
    ["Latitud", "Longitud"]
] = np.nan

print("Latitudes faltantes:", df_limpio["Latitud"].isna().sum())
print("Longitudes faltantes:", df_limpio["Longitud"].isna().sum())

Latitudes faltantes: 5
Longitudes faltantes: 5

In [ ]:
print("Shape actual:", df_limpio.shape)

print("\nColumnas nuevas:")
print([
    col for col in df_limpio.columns
    if col.startswith("Tiene_") or col == "Estado_Propiedad"
])

print("\nFaltantes actuales:")
print(
    df_limpio.isna()
    .sum()
    .sort_values(ascending=False)
    .head(15)
)

Shape actual: (9733, 44)

Columnas nuevas:
['Estado_Propiedad', 'Tiene_Cochera', 'Tiene_Balcon', 'Tiene_Ascensor', 'Tiene_Terraza', 'Tiene_Parrilla', 'Tiene_SUM', 'Tiene_Seguridad', 'Tiene_Aire_Acondicionado', 'Tiene_Baulera', 'Tiene_Patio', 'Tiene_Laundry', 'Tiene_Gimnasio', 'Tiene_Solarium', 'Tiene_Pileta']

Faltantes actuales:
Fecha_Publicacion         9733
Amenities                 1767
Expensas                  1013
Antiguedad                  38
Apto_Credito                37
Descripcion                 37
Longitud                     5
Latitud                      5
Moneda_Expensas              1
Precio_m2_Cubierto           1
Superficie_Cubierta_m2       1
Operacion                    0
Precio_Valor                 0
Moneda                       0
Titulo                       0
dtype: int64

In [ ]:
mask_posible_ph = df_limpio["Titulo"].str.contains(
    r"\bPH\b",
    case=False,
    na=False,
    regex=True
)

print("Títulos que mencionan PH:", mask_posible_ph.sum())

df_limpio.loc[
    mask_posible_ph,
    ["ID", "Tipo_Propiedad", "Titulo", "Barrio", "Precio_Valor"]
]

Títulos que mencionan PH: 64

,ID,Tipo_Propiedad,Titulo,Barrio,Precio_Valor
11,639695,departamento_estandar,Venta PH 5 ambientes- Parque Chacabuco,Parque Chacabuco,176000.0
649,634483,departamento_loft,PH 2 AMBIENTES EN COLEGIALES RECICLADO A NUEVO,Colegiales,175000.0
785,633418,departamento_estandar,PH REFACCIONADO 2do ESCALERA LUMINOSO TECHOS A...,Almagro,70000.0
1268,629405,departamento_estandar,Venta PH 2/3 ambientes terraza Villa Urquiza,Villa Urquiza,180000.0
1309,629105,departamento_estandar,venta PH 2 ambientes terraza privada cochera,Palermo,209000.0
1586,626993,departamento_estandar,DEPTO TIPO PH EN PB VENTA 2 AMB V GRAL MITRE P...,Villa General Mitre,99900.0
1637,626552,departamento_duplex,DUPLEX 3 AMB PH VENTA -BAJAS EXPENSAS - BALVANERA,Balvanera,132500.0
1686,626043,departamento_estandar,VENTA BALVANERA 2 AMBIENTES PATIO A REFACCIONA...,Balvanera,49500.0
2113,621810,departamento_estandar,DEPARTAMENTO EN PB CON PATIO ESTILO PH EN BELG...,Belgrano,150000.0
2318,619767,departamento_estandar,VENTA PH 3 AMBIENTES C/DEP CABALLITO,Almagro,155000.0
2510,617871,departamento_estandar,Venta Belgrano 3 ambientes al frente tipo PH,Belgrano,115000.0
2517,617806,departamento_estandar,PH 3 AMBIENTES DEVOTO PLANTA BAJA CON PATIO,Villa Devoto,128000.0
2530,617693,departamento_duplex,VENTA DUPLEX PH 3 AMB + ESCR BELGRANO R COCHERA,Belgrano R,371000.0
2566,617312,departamento_duplex,VENTA DEPARTAMENTO- PH BELGRANO TERRAZA Y PARR...,Belgrano,235000.0
2592,617102,departamento_estandar,"Venta PH 3 ambientes, villa del parque con patio",Villa del Parque,158000.0
2872,614596,departamento_estandar,VENTA PH 5 AMBIENTES CONSTITUCION SIN EXPENSAS,Constitución,130000.0
3196,611030,departamento_duplex,"Venta PH 2 Ambientes, con terraza - APTO CRÉDITO",Flores,65000.0
3209,610972,departamento_semipiso,VENTA DEPARTAMENTO TIPO PH 4 AMB VILLA URQUIZA,Villa Urquiza,149900.0
3546,607357,departamento_estandar,VENTA PH 3 AMB 49M2 LUMINOSO B° DORREGO MATADEROS,Mataderos,34900.0
3714,605871,departamento_estandar,PH 3 ambientes balcón cfrte Mataderos A/CREDITO,Mataderos,57000.0
3803,604836,departamento_estandar,Venta departamento 6 ambientes tipo PH Francés,Balvanera,148000.0
4062,602532,departamento_estandar,2 AMBIENTES TIPO PH AL FRENTE APTO CRÉDITO,Balvanera,69900.0
4112,602026,departamento_estandar,Venta Ph Dos ambientes con entrepiso Constitu...,Constitución,36000.0
4221,600818,departamento_estandar,Venta PH 3 Amb c/Patio Planta Baja ideal Flipping,Balvanera,95000.0
4222,600816,departamento_estandar,Depto PH Primer piso entrada propia y terraza ...,Almagro,154900.0
4627,596021,departamento_estandar,Departamento 3 amb tipo ph venta Monserrat,Monserrat,73000.0
4876,593280,departamento_monoambiente,PH monoambiente VENTA Balcon APTO CREDITO La Boca,La Boca,59000.0
4991,592004,departamento_estandar,CHACARITA: VENTA PH DE 2 AMBIENTES CON BALCON,Chacarita,72000.0
5023,591573,departamento_estandar,Venta PH Parque Chas 4 Amb Quincho Terraza Par...,Parque Chas,217000.0
5147,590239,departamento_estandar,VENTA PH DEPTO 3 AMBIENTES EN PARQUE CHACABUCO,Parque Chacabuco,79900.0
5154,590147,departamento_estandar,VENTA Dto. 5 Amb.Tipo PH /A.CTO.-CHACARITA-PER...,Chacarita,255000.0
5185,589806,departamento_estandar,Venta Depto Ph De 4 Amb e/piso Congreso,San Nicolás,115000.0
5270,588891,departamento_estandar,Venta Ph 2 amb. Barrio Velez Sarfield.,Velez Sarsfield,62000.0
5284,588814,departamento_estandar,VENTA PH 4 AMBIENTES VILLA CRESPO CON PATIO,Villa Crespo,139000.0
5459,586883,departamento_estandar,VENTA MONOAMBIENTE TIPO PH APTO CREDITO,Monte Castro,65000.0
5624,584908,departamento_estandar,VENTA DEPTO TIPO PH 2 AMB CON PATIO -APTO CREDITO,Villa Urquiza,90000.0
5759,582902,departamento_estandar,"VENTA 4 AMB, DEPARTAMENTO TIPO PH , SAN CRITOBAL",San Cristobal,109900.0
5766,582754,departamento_triplex,Venta PH 4 amb quincho terraza Villa Urquiza,Villa Urquiza,250000.0
6011,579660,departamento_estandar,"Depto tipo PH, 3 amb c/dep, 2ºx Esca, Bajas E...",Almagro,150000.0
6104,578130,departamento_estandar,Oportunidad Venta Depto. tipo PH 4 amb. en Pal...,Palermo,165000.0
6176,577251,departamento_estandar,Departamento PB PH venta 3 Dormitorios Patio,Parque Avellaneda,99000.0
6279,575240,departamento_estandar,VENTA DEPARTAMENTO 2 AMBIENTES TIPO PH MATADEROS,Naón,117000.0
6468,571861,departamento_estandar,Departamento 2 ambientes PH escritorio Caballito,Caballito,70000.0
6638,568973,departamento_estandar,Venta PH 2 amb. Agronomia Planta baja y Patio,Agronomía,85000.0
6856,565079,departamento_estandar,VENTA PH 2 AMB 42M2 SUBTE D UGARTE 2300 y CAB...,Belgrano,85000.0
7093,560373,departamento_estandar,PH PB con 2 patios y COCHERA! APTO CREDITO!,Agronomía,94900.0
7106,560054,departamento_estandar,Impecable PH 3 Amb c/Balcón en Villa Urquiza.,Villa Urquiza,125000.0
7198,558221,departamento_estandar,PH 3 AMBIENTES VENTA CONSTITUCION A REFACCIONAR,Constitución,45000.0
7247,557028,departamento_estandar,VENTA PH 2 AMB. SAN TELMO SIN EXPENSAS!,San Telmo,60000.0
7274,556598,departamento_estandar,VENTA PH/CASA 4 AMB SIN EXPENSAS P.CHACABUCO,Parque Chacabuco,167000.0
7287,556322,departamento_estandar,VENTA AMPLIO PH 4 AMB. EXC ESTADO CABALLITO,Caballito,144000.0
7349,554839,departamento_estandar,Venta PH 3 amb en P. Baja APTO CREDITO- Flores,Flores,75000.0
7385,553870,departamento_duplex,VENTA DEPARTAMENTO / PH DUPLEX - PATERNAL,La Paternal,270000.0
7414,553313,departamento_estandar,Venta 3 amb. tipo PH c/jardin/cochera en Flores,Flores,45000.0
8429,523481,departamento_estandar,PH EN VENTA 3 AMBIENTES VILLA RIACHUELO,Villa Lugano,50000.0
8479,521339,departamento_estandar,"Departamento de 3 amb, tipo PH, 2do por escalera.",Nuñez,115000.0
8591,515741,departamento_estandar,DEPTO TIPO PH 3 AMB.AL FRENTE PALERMO APTO CRE...,Palermo Nuevo,170000.0
8932,492788,departamento_duplex,VENTA PH DE DOS AMBIENTES Y MEDIO EN PALERMO,Recoleta,250000.0
9162,463577,departamento_monoambiente,Venta Monoambiente Tipo PH Almagro Expensas bajas,Almagro,39000.0
9277,442390,departamento_estandar,DEPTO tipo PH 2 Amb/Planta Baja c/2 Patios. Fl...,Flores,73000.0
9333,429510,departamento_estandar,VENTA TIPO PH 3 AMB VILLA CRESPO-A REFACCIONAR,Villa Crespo,60000.0
9344,427332,departamento_estandar,VENTA DPTO PH 4 AMB PATIO PARRILLA ANUEVO BARR...,Barracas,189000.0
9415,404794,departamento_estandar,VENTA PH 2 AMBIENTES 1 PISO POR ESCALERA ALMAGRO,Almagro,55000.0
9697,12803,departamento_estandar,PH VENTA COGHLAN 2 AMBIENTES,Coghlan,68000.0

In [ ]:
patron_ph_fuerte = (
    r"\bventa\s+(?:de\s+)?ph\b|"
    r"\bph\s+(?:de\s+)?\d|\bph\s+\d|"
    r"\btipo\s+ph\b|"
    r"\bdepto\.?\s*(?:tipo\s+)?ph\b|"
    r"\bdepartamento\s*(?:-|/)?\s*ph\b"
)

mask_ph_fuerte = (
    mask_posible_ph &
    texto_propiedad.str.contains(
        patron_ph_fuerte,
        case=False,
        na=False,
        regex=True
    )
)

print("Títulos con PH:", mask_posible_ph.sum())
print("PH identificados con señal fuerte:", mask_ph_fuerte.sum())
print("Casos con PH todavía dudosos:", (mask_posible_ph & ~mask_ph_fuerte).sum())

Títulos con PH: 64
PH identificados con señal fuerte: 56
Casos con PH todavía dudosos: 8

In [ ]:
casos_ph_dudosos = df_limpio.loc[
    mask_posible_ph & ~mask_ph_fuerte,
    ["ID", "Tipo_Propiedad", "Titulo", "Descripcion"]
]

for _, fila in casos_ph_dudosos.iterrows():
    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Tipo:", fila["Tipo_Propiedad"])
    print("Título:", fila["Titulo"])
    print("Descripción:", fila["Descripcion"])

================================================================================
ID: 626552
Tipo: departamento_duplex
Título: DUPLEX 3 AMB PH VENTA -BAJAS EXPENSAS - BALVANERA
Descripción: DEPARTAMENTO DÚPLEX 3 AMBIENTES EN VENTA BALVANERA CAPITAL FEDERAL
BAJAS EXPENSAS

Primer Piso por escalera.

Muy Luminoso con ventanales en todos los ambientes, aprovechando la ubicación en esquina de esta propiedad.

Se encuentra en un complejo donde hay 7 locales en Planta Baja y 5 unidades de vivienda en primer piso.

Bajo mantenimiento mensual. Expensas estimadas en Marzo 2026 de $60.000 (Incluye Agua)


DISTRIBUCIÓN INTELIGENTE

El departamento de 82 m² despliega un diseño pensado para maximizar cada espacio, ofreciendo:

PLANTA BAJA
• Living/comedor luminoso con salida a balcón
• Cocina funcional integrada
• Baño con ducha

PLANTA ALTA
• Dormitorio principal con amplio placard
• Segundo dormitorio versátil
• Lavadero independiente
• Baño completo


CARACTERÍSTICAS DESTACADAS

• Estado general muy bueno
• Disposición en esquina con óptima iluminación natural
• Servicios completos: electricidad, agua y gas

INVERSIÓN INTELIGENTE

Un inmueble que combina la practicidad de un dúplex con la comodidad de un departamento tradicional. Ideal para profesionales, parejas jóvenes o inversores que buscan un espacio con potencial de valorización.

Oportunidad única de habitar un departamento que trasciende lo convencional, donde cada metro cuadrado cuenta una historia de confort urbano.


UBICACIÓN ESTRATÉGICA

• Emplazado sobre la vibrante calle Pasco, en pleno corazón de Balvanera
• Conexión inmediata con transporte público
• Entorno dinámico y multicultural
• Fácil acceso a comercios, restaurantes y servicios


Colectivos: 2, 12, 23, 37, 56, 57, 84, 86, 90, 95, 96, 98, 103, 129, 151, 168

Subtes : PICHINCA (Línea E) a 600 mts
                PASCO (Linea A) a 700mts


POSIBILIDAD DE FINANCIAR HASTA EL 30% DEL VALOR DE LA PROPIEDAD (*)

Las medidas son estimativas y pueden sufrir modificaciones. Los datos definitivos son los que surgirán del título de la propiedad, planos y/o comprobantes respaldatorios

COMUNICATE CONMIGO POR WHATSAPP Y NO DEJES DE VISITARLO!

#SI TIENES QUE VENDER PARA COMPRAR, PODEMOS AYUDARTE Y REALIZAR LA OPERACIÓN SIMULTANEA

(*) BENEFICIO PARA CLIENTES Si te falta hasta un 30% del valor de esta propiedad, te ofrecemos solicitar un préstamo a través de Lendar, servicio exclusivo para clientes RE/MAX.

ALCANZÁ LO QUE SOÑÁS!
MUDATE A LA VIDA QUE QUERÉS!

================================================================================
ID: 626043
Tipo: departamento_estandar
Título: VENTA BALVANERA 2 AMBIENTES PATIO A REFACCIONAR PH
Descripción: VENTA BALVANERA 2 AMBIENTES PATIO A REFACCIONAR PH

AMBIIENTES ESPACIOSOS Y LUMINOSO CONTRAFRENTE. EXCELENTE UBICACIÓN A UNA CUADRA DEL SUBTE LINEA A (EST. PLAZA MISERERE) Y A MEDIA CUADRA DE AV. RIVADAVIA CON UNA GRAN CANTIDAD DE COLECTIVOS Y CONECTIVIDAD HACIA TODA LA CIUDAD.
EL PATIO ES SUPERFICIE COMÚN DE USO EXCLUSIVO DE ESTA UNIDAD FUNCIONAL, SEGÚN CONSTA EN EL REGLAMENTO DE COPROPIEDAD.

- LIVING COMEDOR AMPLIO, CON SALIDA AL PATIO,  DONDE SE ENCUENTRA EL LAVADERO
- COCINA SEPARADA
- PLACARD EN HALL DISTRIBUIDOR
- DORMITORIO, CON MUCHO CONPLACARD.
- BAÑO COMPLETO

TODA LA PROPIEDAD SE PRESENTA EN PISOS DE PARQUET EN MUY BUEN ESTADO EN GENERAL.
SERVICIOS:
- AGUA CALIENTE INDIVIDUAL POR TERMOTANQUE
- CALEFACCION NO TIENE





================================================================================
ID: 621810
Tipo: departamento_estandar
Título: DEPARTAMENTO EN PB CON PATIO ESTILO PH EN BELGRANO
Descripción: Precioso departamento de 3 amplios y luminosos ambientes con patio, ubicado en planta baja, en el exclusivo barrio de Belgrano R.

Situado sobre la calle Zapiola, la unidad forma parte de un edificio de dos pisos, en muy buen estado, que mantiene el encanto de su estilo original combinado con un funcionamiento óptimo.

DISTRIBUCION
Ingreso a hall recibidor que conduce a un amplio living-comedor al frente, con gran ventanal, excelente iluminación natural, hogar apto para estufa a gas y detalles en madera que aportan calidez.
La propiedad cuenta con dos cómodos dormitorios, uno de ellos al frente, ambos con generosos espacios de guardado y pisos de parquet.
El baño completo, de amplias dimensiones, dispone de bañera, ventilación e iluminación natural, además de espacios de guardado.
La cocina, de doble circulación, ofrece gran capacidad de almacenamiento con muebles bajo y sobre mesada, cocina a gas y mesada de granito. Se integra a un comedor diario muy luminoso, con vista al patio.
Desde allí se accede al patio, que puede funcionar como jardín de invierno, un espacio íntimo, luminoso y muy disfrutable.
Lavadero independiente, con dimensiones que permiten su uso como área de servicio.

Vivienda ideal para quienes buscan UN HOGAR ESPACIOSO, TRANQUILO y con una excelente ubicación

UBICACION
Excelente accesibilidad
Muy bien comunicado, a metros de Av. Cramer y Av. de los Incas, con amplia variedad de locales comerciales, de esparcimiento (museos, espacios verdes, clubes) y gastronomía
Líneas de transporte cercanas  19, 44, 65, 67, 80, 113, 133, 151, 168, 184
Estación de Ferrocarril Belgrano R (Mitre)
Educación: Escuela de comercio N° 7 Manuel Belgrano, Colegio N°8 DE 10, y diferentes establecimientos de educación privada
Comuna 13 - Hospital Gral. Ignacio Pirovano
A metros de Plaza Castelli y Plaza Los Olmos

LOS METROS CUADRADOS EXACTOS SALDRÁN DE LA ESCRITURA TRASLATIVA DE DOMINIO
SE DEJA CONSTANCIA QUE LOS METROS REALES DIFIEREN DE LOS ESCRITURADOS.

¿Buscás un lugar donde el corazón se sienta en casa?
Tenemos la llave que abre la puerta de tu nuevo hogar
Contáctate para concertar una visita personalizada a la propiedad


LA OFICINA ES DE OPERACIÓN Y GESTIÓN INDEPENDIENTE.
LA PRESENTE PUBLICACIÓN DESCRIBE LAS CARACTERÍSTICAS ESENCIALES DEL INMUEBLE, DEBIÉNDOSE CONSULTAR AL CORREDOR PÚBLICO INMOBILIARIO RESPONSABLE DE LA OPERACIÓN POR LA EVENTUAL ACTUALIZACIÓN DE LAS MEDIDAS, DESCRIPCIONES ARQUITECTÓNICAS Y FUNCIONALES, VALORES DE EXPENSAS, SERVICIOS, IMPUESTOS, PRECIOS Y DEMÁS INFORMACIÓN, CUYOS VALORES SON APROXIMADOS. LOS AGENTES/GESTORES NO EJERCEN EL CORRETAJE INMOBILIARIO. TODAS LAS OPERACIONES INMOBILIARIAS SON OBJETO DE INTERMEDIACIÓN Y CONCLUSIÓN POR PARTE DEL CORREDOR PÚBLICO INMOBILIARIO RESPONSABLE DE LA PRESENTE PUBLICACIÓN.








================================================================================
ID: 593280
Tipo: departamento_monoambiente
Título: PH monoambiente VENTA Balcon APTO CREDITO La Boca
Descripción: PH MONOAMBIENTE CON BALCÓN - EN VENTA EN LA BOCA

Anteriormente un 2 ambientes, hoy remodelado como Monoambiente / Loft

Una joya histórica en el corazón de La Boca: Un hogar con alma de 1930

Este departamento de 2 ambientes fue remodelado hace unos años como un departamento tipo loft, se encuentra ubicado sobre Martín Rodríguez en el barrio de La Boca, Ciudad de Buenos Aires. Situado en el piso 1° de un edificio de 2 pisos en total, se accede al mismo por escalera.

Cuenta con una superficie construida de 47 m² (46 m² cubiertos, 1 m² semicubiertos).

Tiene sus pisos de PINOTEA y, puertas y ventanas de madera originales de su construcción!

Se ingresa a la propiedad por escalera al primer piso, donde encontramos un hall de recepción y estudio super luminoso, con acceso al baño completo refaccionado a nuevo, luego ingresamos al ambiente principal, que por sus medidas generosas podemos crear diversos espacios, como el del comedor, el del living, el del dormitorio, etc., con su cocina también hecha a nuevo, con extractor de aire de acero inoxidable, cocina con horno y termotanque electrico nuevo, espacio para lavarropas. Ambientes con estufas.

CARACTERÍSTICAS
• Estado: muy bueno
• Antigüedad: 87 años
• Orientación: Este
• Disposición: Frente
• Permite mascotas

MEDIDAS APROXIMADAS
• Hall de ingreso (estudio): 1,75cm. x 3,42cm.
• Living - comedor - dormitorio: 4,05cm. x 8,02cm.
• Cocina: 1,86cm. x 2,83cm.
• Baño: 1,50cm. x 2,47cm.
• Balcón: 1m2

_______________________________________

Descubre la oportunidad de vivir en una propiedad con historia, un verdadero tesoro arquitectónico que fusiona la esencia de la Buenos Aires de 1930 con la vibrante energía del presente. Esta vivienda, con sus sólidas características de construcción de la época, ofrece espacios llenos de carácter, techos altos, amplias habitaciones y un diseño que prioriza la solidez y la luminosidad. Es más que una casa; es un pedazo de la rica historia del barrio.

¡Un barrio con historia, arte y pasión futbolera!

Esta propiedad se encuentra en una ubicación inigualable, en el corazón del icónico barrio de La Boca, una zona que respira cultura e historia en cada rincón. Sus alrededores están plagados de sitios de interés que atraen a turistas de todo el mundo y ofrecen un estilo de vida único:

- Caminito: A solo unos pasos, te encontrarás con la famosa calle museo Caminito, un museo al aire libre que deslumbra con sus conventillos de chapa pintados de vivos colores. Es un lugar donde el arte, el tango y la historia de los inmigrantes genoveses cobran vida, ideal para pasear, disfrutar de exposiciones de arte y sumergirte en la esencia porteña.

- Fundación Proa y Usina del Arte: Para los amantes de la cultura, la proximidad a la Fundación Proa (un centro de arte contemporáneo de renombre internacional) y la Usina del Arte (un majestuoso centro cultural en una antigua central eléctrica) es un verdadero privilegio.

- El Puente Transbordador Nicolás Avellaneda: Esta impresionante estructura de hierro es un Monumento Histórico Nacional y un símbolo del patrimonio industrial de La Boca, ofreciendo una vista panorámica única.

_______________________________________

¡Pasión y verde a tu alcance!

Para los amantes del deporte, la ubicación es sencillamente perfecta. La propiedad se encuentra a muy poca distancia del emblemático estadio La Bombonera, el hogar del legendario Club Atlético Boca Juniors. Vivir tan cerca de este coloso del fútbol es sentir la pasión boquense en su máxima expresión.

Además, el barrio te conecta fácilmente con espacios verdes y áreas de esparcimiento. Puedes disfrutar de caminatas por la Vuelta de Rocha, a orillas del Riachuelo, o desplazarte con facilidad hacia la Costanera Sur, una reserva ecológica ideal para desconectarte y disfrutar de la naturaleza en plena ciudad.

En resumen, esta es una oportunidad única de adquirir una propiedad con un carácter arquitectónico inigualable en un barrio que combina de manera magistral la historia, el arte, la cultura y la pasión del fútbol.

Algunas de las imágenes fueron decoradas con inteligencia artificial, para mostrar posibles opciones de cambio.

_______________________________________

Si necesitas o estás pensando en vender tu propiedad para dar el próximo paso y comprar tu nuevo hogar, estamos para ayudarte. Nuestro equipo te brinda asesoramiento integral y un acompañamiento cercano durante todo el proceso, garantizando transparencia y confianza en cada decisión.

_______________________________________

Si te falta hasta el 35% del valor de tu propiedad, LENDAR, te brinda el crédito que necesitas!
LENDAR es una empresa que trabaja para clientes de REMAX. Simula tu crédito y conseguí mas información en www.lendar.com.ar

================================================================================
ID: 577251
Tipo: departamento_estandar
Título: Departamento PB PH venta 3 Dormitorios Patio
Descripción:
¿Querés la comodidad de una casa con la seguridad de un departamento?
Esta unidad en Planta Baja destaca por su versatilidad, su gran espacio al aire libre y el acceso a espacios comunes que completan tu calidad de vida.
Distribución y Ambientes:
Living-Comedor: Espacio amplio con pisos de madera hidrolaqueada y excelente luminosidad.
Cocina Integrada: Diseño moderno con barra desayunadora, ideal para integrar el área social.
Dormitorio Principal: Habitación confortable con gran frente de placard.
Segundo Dormitorio: Habitación funcional con vista y luz natural.
Tercer Ambiente / Escritorio: Espacio independiente que podés usar como oficina, estudio o un tercer dormitorio pequeño.
Patio Privado: Excepcional pulmón de 25 m² para disfrutar del aire libre con total privacidad.
Terraza Común: El edificio cuenta con una terraza para disfrutar de vistas abiertas.
Baño Completo: Reciclado a nuevo con terminaciones de categoría.
Características Destacadas: Ubicación: Calle Laguna al 700, en una zona residencial estratégica.  Superficie: 82 m² totales que garantizan amplitud en cada ambiente.
Seguridad: Puerta blindada en la unidad y sistema de cámaras en el edificio.
Servicios Exclusivos RE/MAX: Financiación LENDAR: Accedé a un préstamo de hasta el 30% del valor de la propiedad de forma ágil y con mínimos requisitos a través de Lendar.
Análisis de Mercado: Si querés conocer el valor real de comercialización de tu propiedad hoy, contactame para realizar un análisis comparativo de mercado exhaustivo y profesional.
¡Mudarte a la vida que querés es posible! Contactame hoy mismo y coordinamos tu visita.

"Las imágenes de la propiedad incluyen amoblamiento virtual, diseñado exclusivamente para ilustrar las múltiples posibilidades de uso y decoración de cada ambiente sin haber alterado sus medidas reales. Esta herramienta permite visualizar cómo aprovechar al máximo los 82 m² de la unidad, ya sea configurándola con tres dormitorios o integrando un moderno estudio para trabajar desde casa."

================================================================================
ID: 571861
Tipo: departamento_estandar
Título: Departamento 2 ambientes PH  escritorio Caballito
Descripción: DEPARTAMENTO DE 2 AMBIENTES CON ESCRITORIO EN AV. PEDRO GOYENA Y PUAN

Presentamos esta unidad funcional ubicada en la cuadra más cotizada del barrio de Caballito. Destaca por su excelente estado de conservación, luminosidad y una distribución optimizada que aprovecha al máximo cada metro cuadrado.

Ubicación: Tercer piso por escalera. Esta característica se traduce en expensas notablemente más bajas y una mayor tranquilidad estructural.

Superficie total: 38 m2.

CARACTERÍSTICAS PRINCIPALES:

Living-Comedor: Espacioso, con muy buena entrada de luz natural y distribución funcional.

Escritorio / Espacio de Home Office: Ambiente independiente logrado mediante el cerramiento del balcón original. Ideal para trabajar o estudiar desde casa con luz propia y aislamiento acústico.

Dormitorio: Orientado hacia el contrafrente, lo que garantiza absoluto silencio para el descanso. Cuenta con placard empotrado de piso a techo con interiores completos.

Cocina Independiente: Totalmente equipada con amoblamiento bajo mesada. Posee una ventana con vista  lateral hacia Avenida Pedro Goyena que asegura ventilación cruzada y luminosidad.

Baño Completo: Cómodo, revestido y en perfectas condiciones de mantenimiento sanitario.

Por su tipología con espacio de escritorio propio y su ubicación estratégica en lo mejor de Caballito, representa una opción sumamente competitiva tanto para vivienda joven como para inversión de renta inmediata.

Las visitas ya se encuentran abiertas. Para coordinar un ingreso o solicitar más información, comuníquese directo por mensaje privado o vía WhatsApp.

Contacto comercial:
Noelia Tosto
WhatsApp: 15 6506 0380
Instagram: @noetosto.remax

¿Necesitás vender para comprar? Contamos con un método de trabajo especializado para coordinar ambas operaciones en simultáneo, brindándote la seguridad y tranquilidad que necesitás en este proceso.

Financiación exclusiva para clientes RE/MAX: Si te falta hasta un 35% del valor de la propiedad, podés acceder a un préstamo a través de Lendar de forma rápida y con mínimos requisitos. Hacé realidad tu mudanza hoy mismo.

Todas las operaciones inmobiliarias son concluidas exclusivamente por el corredor matriculado responsable Martín Macagno (CUCICBA 6267 / CMCPDJLM 821). Oficinas de gestión independiente.

Las imágenes amobladas han sido ambientadas virtualmente para demostrar el potencial de distribución y dimensiones de los espacios, manteniendo la escala real del departamento.



================================================================================
ID: 560373
Tipo: departamento_estandar
Título: PH PB con 2 patios y COCHERA! APTO CREDITO!
Descripción: 2 AMBIENTES Y MEDIO EN PLANTA BAJA CON DOS PATIOS Y COCHERA – AGRONOMÍA

APTO CREDITO!!!!

BAJAS EXPENSAS!!!

Ubicado sobre Pedro Morán al 2100, en pleno barrio de Agronomía, una zona residencial, tranquila y con excelente conectividad, cercano a Parque Chas, Villa Pueyrredón y Villa Urquiza, avenidas principales, comercios, espacios verdes y múltiples medios de transporte.

La propiedad se desarrolla en planta baja y se destaca por su funcionalidad, comodidad y muy buen aprovechamiento de los espacios.

Cuenta con una superficie de 44.01 m² cubiertos y 3,48 m² descubiertos, lo que conforma un total de 47,49 m², con una distribución pensada para optimizar cada ambiente.

Se trata de un 2 ambientes y medio, ya que además del dormitorio principal y el living comedor, ofrece un espacio adicional ideal para escritorio, home office o ambiente de uso flexible según necesidad.

Uno de sus grandes diferenciales son sus dos patios propios. Uno de ellos se encuentra techado, lo que permite ampliar el espacio de uso diario durante todo el año, manteniendo una correcta ventilación.

Todos los ambientes cuentan con muy buena ventilación natural, generando una excelente circulación de aire y un entorno cómodo y agradable.

Edificio eléctrico y suma un valor clave: la instalación eléctrica de esta unidad fue completamente renovada desde la línea municipal hasta la unidad hace dos años.

Incluye cochera descubierta por escritura, un diferencial muy valorado en la zona.

Expensas: 150.000 pesos.
Terraza de uso común.

Una propiedad práctica y versátil, con características que la destacan: planta baja, doble patio, espacio extra y cochera, en una ubicación estratégica dentro de Agronomía.

HACÉ TU OFERTA Y MUDATE A LA VIDA QUE SOÑÁS!

================================================================================
ID: 523481
Tipo: departamento_estandar
Título: PH EN VENTA 3 AMBIENTES VILLA RIACHUELO
Descripción: PH en venta 3 AMBIENTES
Planta Baja (Área de Servicios y Exterior): Al ingresar, encontramos una cochera propia de gran comodidad y un patio íntimo, ideal para mascotas, plantas o un rincón de relax al aire libre.

​Planta Alta (Área Social y Privada): Subiendo las escaleras, se desarrolla el corazón del hogar. Cuenta con un living-comedor luminoso, cocina con buen espacio de guardado y dormitorio/habitaciones que reciben excelente ventilación natural.
​Extras: La unidad incluye terraza, sumando funcionalidad y espacio de colgado o recreación.

Comedor
Cocina
2 habitaciones
1 baño
Terraza
1 cochera
Espacio de guardado
 El PH se encuentra dentro de un condominio y es el segundo por la entrada principal.




¡Si desea visitar la propiedad, no dudes en contactarme!

"En cumplimiento de las normas legales aplicables informamos que los agentes NO ejercen Corretaje Inmobiliario. Todas las operaciones inmobiliarias son concluidas por el Corredor Inmobiliario y Martillero Publico Roque Ciampa CUCICBA 5946

Las medidas, superficies y detalles consignados en el presente son aproximados y al solo efecto orientativo. Las medidas originales surgirán del título de propiedad.

Inmueble no accesible para personas con discapacidad física (Ley 5115)

In [ ]:
ids_ph_adicionales = [
    626043,
    593280,
    560373,
    523481
]

mask_ph_final = (
    mask_ph_fuerte |
    df_limpio["ID"].isin(ids_ph_adicionales)
)

print("PH identificados para excluir:", mask_ph_final.sum())

df_limpio.loc[
    mask_ph_final,
    ["ID", "Tipo_Propiedad", "Titulo"]
].head(10)

PH identificados para excluir: 60

,ID,Tipo_Propiedad,Titulo
11,639695,departamento_estandar,Venta PH 5 ambientes- Parque Chacabuco
649,634483,departamento_loft,PH 2 AMBIENTES EN COLEGIALES RECICLADO A NUEVO
785,633418,departamento_estandar,PH REFACCIONADO 2do ESCALERA LUMINOSO TECHOS A...
1268,629405,departamento_estandar,Venta PH 2/3 ambientes terraza Villa Urquiza
1309,629105,departamento_estandar,venta PH 2 ambientes terraza privada cochera
1586,626993,departamento_estandar,DEPTO TIPO PH EN PB VENTA 2 AMB V GRAL MITRE P...
1686,626043,departamento_estandar,VENTA BALVANERA 2 AMBIENTES PATIO A REFACCIONA...
2318,619767,departamento_estandar,VENTA PH 3 AMBIENTES C/DEP CABALLITO
2510,617871,departamento_estandar,Venta Belgrano 3 ambientes al frente tipo PH
2517,617806,departamento_estandar,PH 3 AMBIENTES DEVOTO PLANTA BAJA CON PATIO

In [ ]:
print("Antes de eliminar PH:", df_limpio.shape)

df_limpio = df_limpio.loc[~mask_ph_final].copy()
df_limpio.reset_index(drop=True, inplace=True)

print("Después de eliminar PH:", df_limpio.shape)

Antes de eliminar PH: (9733, 44)
Después de eliminar PH: (9673, 44)

In [ ]:
texto_propiedad = (
    df_limpio["Titulo"].fillna("") + " " +
    df_limpio["Descripcion"].fillna("")
)

print("Filas df_limpio:", len(df_limpio))
print("Filas texto_propiedad:", len(texto_propiedad))

Filas df_limpio: 9673
Filas texto_propiedad: 9673

In [ ]:
df_limpio["Estado_Propiedad"].value_counts()

Estado_Propiedad
Sin_clasificar            6181
Buen_estado               2000
Reciclada_refaccionada    1079
Necesita_obra              413
Name: count, dtype: int64

In [ ]:
df_limpio.loc[
    df_limpio["Estado_Propiedad"] != "Sin_clasificar"
].groupby("Estado_Propiedad")["Precio_m2_Total"].agg(
    ["count", "mean", "median", "std"]
).round(2)

                        count     mean   median     std
Estado_Propiedad
Buen_estado              2000  2008.99  1948.60  631.33
Necesita_obra             413  1604.85  1566.67  569.18
Reciclada_refaccionada   1079  2195.64  2125.00  688.62

In [ ]:
df_limpio["Precio_m2_Total"].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
).round(2)

count     9673.00
mean      2182.12
std        820.32
min        292.93
1%         789.11
5%        1132.02
25%       1640.62
50%       2070.91
75%       2567.57
95%       3621.23
99%       4801.33
max      15403.42
Name: Precio_m2_Total, dtype: float64

In [ ]:
columnas_ver = [
    "ID", "Titulo", "Barrio",
    "Precio_Valor", "Superficie_Total_m2",
    "Precio_m2_Total", "Estado_Propiedad"
]

print("=== 10 PRECIOS/M² MÁS BAJOS ===")
display(
    df_limpio
    .nsmallest(10, "Precio_m2_Total")[columnas_ver]
)

print("\n=== 10 PRECIOS/M² MÁS ALTOS ===")
display(
    df_limpio
    .nlargest(10, "Precio_m2_Total")[columnas_ver]
)

=== 10 PRECIOS/M² MÁS BAJOS ===

,ID,Titulo,Barrio,Precio_Valor,Superficie_Total_m2,Precio_m2_Total,Estado_Propiedad
2294,619962,VENTA DEPARTAMENTO 5 AMB VILLA SOLDATI A RECICLAR,Villa Soldati,29000.0,99.00,292.93,Necesita_obra
9096,465887,VENTA DEPARTAMENTO 3 AMB + CONSTRUCCION MIXTA ...,La Boca,70000.0,186.00,376.34,Sin_clasificar
5071,590743,VENTA DEPARTAMENTO 5 AMBIENTES VILLA SOLDATI,Villa Soldati,30000.0,77.80,385.60,Sin_clasificar
5978,579629,Venta 5 ambientes Villa Soldati,Villa Soldati,32500.0,83.00,391.57,Necesita_obra
4780,594028,VENTA NUDA PROPIEDAD DPTO 2 AMB SAN CRISTOBAL,San Cristobal,30000.0,68.90,435.41,Sin_clasificar
8168,531879,"VENTA DEPTO 4 AMB LUGANO +PATIO TECH, LUMINOSO",Villa Lugano,31000.0,69.81,444.06,Sin_clasificar
6169,576765,Departamento en Venta Tribunales Terraza,Barrio Norte,49900.0,111.66,446.89,Sin_clasificar
5923,580438,Departamento 5 ambientes en el Barrio Piedrabuena,Villa Lugano,44000.0,95.00,463.16,Buen_estado
4898,592645,"DEPARTAMENTO 5 AMB, APTO CREDIT0",Villa Soldati,48000.0,101.57,472.58,Sin_clasificar
3056,612297,DEPARTAMENTO EN VENTA - 4 AMBIENTES - LUGANO 1...,Villa Lugano,32000.0,65.00,492.31,Necesita_obra

=== 10 PRECIOS/M² MÁS ALTOS ===

,ID,Titulo,Barrio,Precio_Valor,Superficie_Total_m2,Precio_m2_Total,Estado_Propiedad
7939,537642,PISO 34 -TERMINADO con materiales premium unicos,Palermo,6300000.0,409.00,15403.42,Sin_clasificar
3766,605137,EXCLUSIVO PISO ALTO EN TORRES DECO POLO,Las Cañitas,1450000.0,156.00,9294.87,Sin_clasificar
9215,444264,VENTA DEPARTAMENTO 5 AMB + DEP TORRE BELLINI N...,Nuñez,2900000.0,334.62,8666.55,Sin_clasificar
440,636067,VENTA ESPECTACULAR PISO ALTO CHATEAU LIBERTADOR,Nuñez,4400000.0,511.04,8609.89,Sin_clasificar
8161,532144,VENTA DEPTO 2AMB C/ COCHERA BAULERA FULL AMENI...,Belgrano,495000.0,60.23,8218.50,Sin_clasificar
276,637447,Piso muy alto en Le Parc Puerto Madero Vista 360°,Puerto Madero,1450000.0,178.47,8124.61,Sin_clasificar
7109,559265,VENTA DEPARTAMENTO NUÑEZ CUATRO AMBIENTES EN T...,Nuñez,1790000.0,225.00,7955.56,Sin_clasificar
5853,581379,Departamento 4 Amb. C/Cochera Torre Decó - Pis...,Recoleta,1200000.0,156.27,7679.02,Sin_clasificar
9132,460558,"Departamento sempiso P 11, 3 suite 2 coch amen...",Palermo Chico,1300000.0,172.50,7536.23,Sin_clasificar
149,638556,Departamento de 3 ambientes en Venta en Palermo,Palermo,560000.0,74.76,7490.64,Sin_clasificar

In [ ]:
ids_revisar = [594028, 576765]

for _, fila in df_limpio[
    df_limpio["ID"].isin(ids_revisar)
].iterrows():

    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])
    print("Barrio:", fila["Barrio"])
    print("Precio:", fila["Precio_Valor"])
    print("Superficie:", fila["Superficie_Total_m2"])
    print("Descripción:")
    print(fila["Descripcion"])

================================================================================
ID: 594028
Título: VENTA NUDA PROPIEDAD DPTO 2 AMB SAN CRISTOBAL
Barrio: San Cristobal
Precio: 30000.0
Superficie: 68.9
Descripción:
La propiedad corresponde a un departamento de 2 ambientes ubicado en segundo piso por escalera, al contrafrente, con una superficie aproximada de  69m² y cocina independiente, brindando una distribución funcional y cómoda.

La operación se realiza bajo la modalidad de venta de nuda propiedad con usufructo vitalicio, una alternativa cada vez más elegida por inversores y compradores con visión patrimonial de largo plazo.

Las medidas, superficies y datos consignados son aproximados y al solo efecto orientativo. Los datos definitivos surgirán del título de propiedad y documentación correspondiente.

ASPECTOS CLAVE PARA EL COMPRADOR DE NUDA PROPIEDAD CON USUFRUCTO VITALICIO

¿Qué se vende?

La operación consiste en la venta de la nuda propiedad del inmueble, conservando el vendedor el usufructo vitalicio.

Esto implica que el comprador adquiere la titularidad dominial del inmueble mediante escritura, mientras que el usufructuario mantiene el derecho de uso y goce durante toda su vida.

Aspectos importantes a considerar

1. No existe posesión inmediata
El comprador no podrá:
Habitar el inmueble.
Alquilarlo.
Percibir renta.
Disponer materialmente de la propiedad.
El usufructuario conservará el derecho a:
Habitar el inmueble.
Alquilarlo y percibir ingresos.
Utilizar y disfrutar del bien durante toda su vida.

2. El usufructo es vitalicio
El usufructo permanecerá vigente hasta el fallecimiento del usufructuario.
Una vez producido ese hecho:
El usufructo se extingue automáticamente.
El comprador consolida el dominio pleno.
Obtiene el uso y disposición total del inmueble.

3. El comprador adquiere un derecho real y escritura a su nombre
La compra no constituye una reserva ni una promesa futura.
El comprador:
Escritura el inmueble.
Figura como titular registral de la nuda propiedad.
Adquiere un derecho real inscripto.

4. Valor de compra por debajo del mercado tradicional
Debido a que el inmueble no puede utilizarse inmediatamente, el valor se comercializa por debajo del valor pleno de mercado.

5. Es una inversión patrimonial de largo plazo
Esta modalidad suele estar orientada a:
Inversores.
Compradores patrimoniales.
Personas que buscan preservar capital.
Compradores que priorizan adquirir inmuebles a valores diferenciales.
No esta orientada a compradores que buscan vivienda inmediata o renta inmediata.

Observación importante
La duración del usufructo vitalicio no puede determinarse ni estimarse, dado que depende exclusivamente de la vida del usufructuario.
La operación debe analizarse desde un enfoque patrimonial y jurídico previo a la compra.

The property consists of a one-bedroom apartment located on the second floor, accessible by staircase, at the rear of the building. It offers an approximate surface area of 69 m² and features an independent kitchen, providing a comfortable and functional layout.

The transaction is structured as a sale of bare ownership (nuda propiedad) with a lifetime usufruct, an increasingly popular option among investors and buyers seeking long-term wealth preservation and estate planning opportunities.

All measurements, surface areas, and information provided are approximate and for guidance purposes only. Final and legally binding details will arise from the property's title deed and the corresponding legal documentation.

KEY ASPECTS FOR THE PURCHASER OF BARE OWNERSHIP WITH A LIFETIME USUFRUCT

What is being sold?

This transaction involves the sale of the property's bare ownership, while the seller retains a lifetime usufruct.

This means that the buyer acquires legal title to the property through a deed transfer, while the usufructuary retains the right to use and enjoy the property for the remainder of their lifetime.

Important considerations

1. No immediate possession

The buyer will not be entitled to:

• Occupy the property.
• Lease the property.
• Collect rental income.
• Exercise physical possession or use of the property.

The usufructuary will retain the right to:

• Reside in the property.
• Lease the property and collect rental income.
• Use and enjoy the property throughout their lifetime.

2. The usufruct is for life

The usufruct remains in effect until the usufructuary's death.

Upon that event:

• The usufruct automatically terminates.
• The buyer acquires full ownership rights.
• The buyer gains complete use, enjoyment, and disposition of the property.

3. The buyer acquires a real property right and title in their name

This purchase is not a reservation, option, or future promise to transfer ownership.

The buyer:

• Receives title to the property.
• Is registered as the owner of the bare ownership interest.
• Acquires a legally recognized and registered real property right.

4. Purchase price below traditional market value

Since the property cannot be immediately occupied or utilized, it is generally marketed at a price below its full market value.

5. Long-term asset investment

This type of transaction is generally intended for:

• Investors.
• Asset-oriented buyers.
• Individuals seeking capital preservation.
• Buyers interested in acquiring real estate at a discounted value.

It is not intended for purchasers seeking immediate occupancy or immediate rental income.

Important note

The duration of a lifetime usufruct cannot be determined or estimated, as it depends exclusively on the lifespan of the usufructuary.

Prospective purchasers should evaluate this transaction from both a legal and long-term investment perspective before proceeding with the acquisition.


================================================================================
ID: 576765
Título: Departamento en Venta Tribunales  Terraza
Barrio: Barrio Norte
Precio: 49900.0
Superficie: 111.66
Descripción:
VENTA DEPARTAMENTO 112 M² BARRIO NORTE CAPITAL FEDERAL

OPORTUNIDAD!
APTO VIVIENDA, APTO PROFESIONAL, APTO COMERCIAL
EXPENSAS actuales, JUNIO 26 $ 693.518

Propiedad originalmente destinada a oficina profesional ubicada en una zona estratégica de Barrio Norte, sobre la calle Uruguay, con una superficie total de 112 m².

Metros cubiertos 87
Terraza, descubiertos 25, propios y por escritura

Ubicado en primer piso contrafrente

Ideal para inversores que refaccionen para vivienda o profesionales independientes o empresas que busquen una ubicación premium en pleno centro corporativo de Buenos Aires.


1 Toilette
1 Baño con ducha
 Kitchenette
 Puerta Blindada.
Edificio 100 % electrico

El espacio cuenta con distribución racional, luminosidad natural y detalles arquitectónicos que lo distinguen de propiedades similares. Su estado impecable garantiza una inversión segura sin necesidad de realizar reformas inmediatas. La ubicación permite acceso inmediato a servicios, transporte público y principales arterias de la ciudad.

Zona con alta plusvalía y demanda constante de espacios corporativos, lo que convierte esta propiedad en una inversión estratégica con proyección de revalorización. Oportunidad para profesionales y empresas que valoran ubicación, calidad constructiva y potencial de crecimiento.

Por ubicación y características:
Excelente zona de oficinas del microcentro / tribunales.
Cercanía a Av. Córdoba y Av. 9 de Julio.
Ideal para:
inversión refacción para vivienda (aprobado x reglamento copropiedad)
estudio jurídico
consultorios
coworking
showroom
oficinas administrativas

In [ ]:
ids_excluir = [594028, 576765]

print("Antes:", df_limpio.shape)

df_limpio = df_limpio.loc[
    ~df_limpio["ID"].isin(ids_excluir)
].copy()

df_limpio.reset_index(drop=True, inplace=True)

# Reconstruimos el texto después del cambio de índice
texto_propiedad = (
    df_limpio["Titulo"].fillna("") + " " +
    df_limpio["Descripcion"].fillna("")
)

print("Después:", df_limpio.shape)

Antes: (9673, 44)
Después: (9671, 44)

In [ ]:
fila = df_limpio.loc[df_limpio["ID"] == 465887].iloc[0]

print("ID:", fila["ID"])
print("Tipo:", fila["Tipo_Propiedad"])
print("Título:", fila["Titulo"])
print("Barrio:", fila["Barrio"])
print("Precio:", fila["Precio_Valor"])
print("Superficie total:", fila["Superficie_Total_m2"])
print("Superficie cubierta:", fila["Superficie_Cubierta_m2"])
print("Precio/m²:", fila["Precio_m2_Total"])
print("\nDescripción:")
print(fila["Descripcion"])

ID: 465887
Tipo: departamento_estandar
Título: VENTA DEPARTAMENTO 3 AMB + CONSTRUCCION MIXTA OPOR
Barrio: La Boca
Precio: 70000.0
Superficie total: 186.0
Superficie cubierta: 70.0
Precio/m²: 376.34

Descripción:
Gran oportunidad en el barrio de La Boca! No paga expensas y es apto crédito.

Venta departamento de 3 ambientes + construcción mixta de chapa y madera en el fondo de la propiedad.

Este departamento, con orientación este, se destaca por su excelente luminosidad y sus ambientes de medidas generosas. Cuenta con un amplio living comedor, dos dormitorios, un baño completo, una cocina funcional con lavadero independiente y un cómodo balcón corrido ideal para disfrutar del aire libre.

Además, en su valor se incluye una construcción mixta de chapa y madera ubicada al fondo de la propiedad, brindando un espacio extra con múltiples posibilidades de uso.

Medidas aproximadas:
Hall 2,42*1,92
Living/comedor 4,56*3,85
Cocina 4,08*2,38
Baño 2,34*1,48
Habitación principal 3,73*3,57
Habitación 3,35*3,2

Consultanos y vayamos a visitarla!

In [ ]:
extremos_bajos = df_limpio.nsmallest(20, "Precio_m2_Total").copy()

extremos_bajos["Porcentaje_Cubierto"] = (
    extremos_bajos["Superficie_Cubierta_m2"] /
    extremos_bajos["Superficie_Total_m2"] * 100
).round(1)

extremos_bajos[
    [
        "ID",
        "Titulo",
        "Barrio",
        "Precio_Valor",
        "Superficie_Total_m2",
        "Superficie_Cubierta_m2",
        "Porcentaje_Cubierto",
        "Precio_m2_Total"
    ]
]

,ID,Titulo,Barrio,Precio_Valor,Superficie_Total_m2,Superficie_Cubierta_m2,Porcentaje_Cubierto,Precio_m2_Total
2294,619962,VENTA DEPARTAMENTO 5 AMB VILLA SOLDATI A RECICLAR,Villa Soldati,29000.0,99.00,96.00,97.0,292.93
9094,465887,VENTA DEPARTAMENTO 3 AMB + CONSTRUCCION MIXTA ...,La Boca,70000.0,186.00,70.00,37.6,376.34
5070,590743,VENTA DEPARTAMENTO 5 AMBIENTES VILLA SOLDATI,Villa Soldati,30000.0,77.80,77.80,100.0,385.60
5977,579629,Venta 5 ambientes Villa Soldati,Villa Soldati,32500.0,83.00,75.00,90.4,391.57
8166,531879,"VENTA DEPTO 4 AMB LUGANO +PATIO TECH, LUMINOSO",Villa Lugano,31000.0,69.81,62.66,89.8,444.06
5922,580438,Departamento 5 ambientes en el Barrio Piedrabuena,Villa Lugano,44000.0,95.00,95.00,100.0,463.16
4897,592645,"DEPARTAMENTO 5 AMB, APTO CREDIT0",Villa Soldati,48000.0,101.57,92.87,91.4,472.58
3056,612297,DEPARTAMENTO EN VENTA - 4 AMBIENTES - LUGANO 1...,Villa Lugano,32000.0,65.00,65.00,100.0,492.31
6578,569285,VENTA DEPTO 5 AMB COCHERA,Centro / Microcentro,129000.0,248.26,248.26,100.0,519.62
3124,611628,VENTA DEPTO 4 AMB PIEDRA BUENA LUGANO,Villa Lugano,39000.0,74.97,74.97,100.0,520.21
4793,593849,VENTA DTO 4 AMB VILLA LUGANO,Villa Lugano,37000.0,71.00,71.00,100.0,521.13
7958,537178,"DEPTO 5 AMBIENTES EN VENTA,BARRIO PIEDRABUENA",Villa Lugano,49000.0,93.00,93.00,100.0,526.88
7763,543052,VENTA MONOAMBIENTE VILLA LUGANO B. PIEDRA BUENA,Villa Lugano,20000.0,37.93,30.32,79.9,527.29
2252,620307,DEPARTAMENTO VENTA 4 AMB POMPEYA TERRAZA PROPIA,Nueva Pompeya,125000.0,235.80,113.87,48.3,530.11
4867,592974,DEPARTAMENTO VENTA 4 AMB PARQUE PATRICIOS TERRAZA,Parque Patricios,125000.0,235.80,113.87,48.3,530.11
9643,55468,Venta Depto. 3 amb.c/balcón Villa Soldati,Villa Soldati,27800.0,52.00,48.00,92.3,534.62
8664,509302,departamento 5 ambientes a refaccionar / Centro,Monserrat,95000.0,172.30,172.30,100.0,551.36
9321,417823,Venta Departamento 3 AMB Villa Lugano,Villa Lugano,42000.0,74.66,64.64,86.6,562.55
3474,607910,DEPARTAMENTO VENTA 4 AMBIENTES PIEDRA BUENA LU...,Villa Lugano,39500.0,70.00,63.00,90.0,564.29
4553,596423,VENTA DEPARTAMENTO 4 AMBIENTES VILLA SOLDATI,Villa Soldati,35000.0,62.00,62.00,100.0,564.52

In [ ]:
fila = df_limpio.loc[df_limpio["ID"] == 569285].iloc[0]

print("ID:", fila["ID"])
print("Tipo:", fila["Tipo_Propiedad"])
print("Título:", fila["Titulo"])
print("Barrio:", fila["Barrio"])
print("Precio:", fila["Precio_Valor"])
print("Superficie total:", fila["Superficie_Total_m2"])
print("Superficie cubierta:", fila["Superficie_Cubierta_m2"])
print("Ambientes:", fila["Ambientes"])
print("Dormitorios:", fila["Dormitorios"])
print("Precio/m²:", fila["Precio_m2_Total"])
print("\nDescripción:")
print(fila["Descripcion"])

ID: 569285
Tipo: departamento_estandar
Título: VENTA DEPTO 5 AMB COCHERA
Barrio: Centro / Microcentro
Precio: 129000.0
Superficie total: 248.26
Superficie cubierta: 248.26
Ambientes: 5
Dormitorios: 4
Precio/m²: 519.62

Descripción:
PIEDRAS 70-MICROCENTRO PORTEÑO-OPORTUNIDAD -APTO VIVIENDA y PROFESIONAL-
Semipiso  premium de 236 m² cubiertos más dos cocheras cubiertas, ideal vivienda , estudio o Showroom.

Excelente opción residencial en edificio corporativo de gran categoría sobre la calle Piedras 77, en pleno Microcentro porteño.

La unidad cuenta con 235 m² totales, excelente luz natural y muy lindas vistas abiertas, desarrollándose en una planta funcional con gran potencial para reciclar y modernizar.

El edificio posee seguridad presencial las 24 hs, elegante hall de acceso y 3 ascensores, ofreciendo una imagen corporativa ideal para empresas, estudios profesionales, consultoras o coworking.

La propiedad dispone de:
• Dos Cocheras cubiertas
• Servicios centrales
• Calefacción fan-coil perimetral por radiadores de ventana
• Amplios espacios de trabajo
• Muy buena luminosidad natural
• Excelente conectividad y accesos

Ubicación estratégica en el corazón del Microcentro, a metros del histórico CAFE TORTONI, Av. de Mayo y del casco histórico porteño.

Excelente conectividad mediante múltiples medios de transporte:
• Subte Línea A (Estación Piedras)
• Cercanía a líneas C, D y E
• Metrobus 9 de Julio y Av. de Mayo
• Gran variedad de líneas de colectivo
• Rápido acceso a Puerto Madero, Plaza de Mayo y principales arterias de la ciudad

Una propiedad con enorme potencial para renovación integral y actualización estética, ideal para desarrollar oficinas AAA, showroom corporativo o inversión patrimonial o Vivienda en una ubicación estratégica de la ciudad.

In [ ]:
patron_potencial_obra = (
    r"potencial para reciclar|"
    r"potencial para refaccionar|"
    r"potencial para modernizar|"
    r"renovaci[oó]n integral"
)

mask_potencial_obra = (
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
    texto_propiedad.str.contains(
        patron_potencial_obra,
        case=False,
        na=False,
        regex=True
    )
)

print("Casos encontrados:", mask_potencial_obra.sum())

df_limpio.loc[
    mask_potencial_obra,
    ["ID", "Titulo", "Barrio", "Precio_m2_Total"]
].head(20)

Casos encontrados: 5

,ID,Titulo,Barrio,Precio_m2_Total
3155,611305,Departamento ideal para empezar a ser propiet...,Parque Chacabuco,1113.42
3481,607842,Venta 4 amb + dep V. Crespo. A refac. Financia...,Villa Crespo,643.94
3497,607641,VENTA DEPTO BELGRANO 3 AMB BALCON CORRIDO NUEVO,Belgrano Chico,2713.11
3602,606775,VENTA PASO AL 100 CABA 3 AMB LUMINOSO BALCON,Balvanera,973.68
6326,573714,VENTA DPTO DOS AMBIENTES PALERMO BOTANICO,Palermo,2149.24

In [ ]:
for _, fila in df_limpio.loc[mask_potencial_obra].iterrows():
    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])
    print("Barrio:", fila["Barrio"])
    print("Estado actual:", fila["Estado_Propiedad"])
    print("Descripción:")
    print(fila["Descripcion"])

================================================================================
ID: 611305
Título: Departamento ideal para empezar  a ser propietario
Barrio: Parque Chacabuco
Estado actual: Sin_clasificar
Descripción:
Departamento de 3 ambientes de 52,99 m², completamente remodelado a nuevo, con excelentes terminaciones y listo para habitar. La unidad ofrece ambientes cómodos, funcionales y una renovación integral que aporta confort y practicidad.

Ubicado en un primer piso por escalera, dentro de un monoblock de construcción antigua, su principal diferencial radica en el impecable estado de la propiedad. Si bien el edificio y el entorno no se destacan por su estética, el departamento representa una excelente oportunidad para quienes priorizan una vivienda renovada, de bajo mantenimiento y con una muy buena relación entre calidad y precio.

El departamento posee tanto gas como electricidad, el agua caliente es suministrada por un termotanque a gas, mientras que en la cocina todo funciona con electricidad, pudiendo el nuevo comprador convertirla a gas si deseara,  ya que el éste llega hasta la cocina, solo sería necesario realizar la conexión.

Posee una cochera cubierta que es considerada como un espacio común , y que en si existen lugares disponibles las unidades funcionales cuentan con una de ellas y también con un lugar de guardado para un segundo auto en una cochera descubierta, dentro del mismo predio en donde se encuentra el edificio, aspectos éstos que suman un plus muy importante, sobre todo en lo que se refiere a la posibilidad de no tener que dejar el auto en la calle o alquilar una cochera .

En cuanto a las expensas el monto es de $116.00, más $20.000, en caso de utilizar la cochera.

Cabe destacar que el departamento tiene dos dormitorios pero en la actualidad uno de ellos se encuentra dividido por un  durlock  lo que genera un tercer dormitorio, lo ofrece un espacio más, que puede ser utilizado o bien volverlo al estado original y convertirlo en 2 dormitorios.

================================================================================
ID: 607842
Título: Venta 4 amb + dep V. Crespo. A refac. Financiación
Barrio: Villa Crespo
Estado actual: Sin_clasificar
Descripción:
VENTA DEPARTAMENTO 4 AMBIENTES VILLA CRESPO CAPITAL FEDERAL

US$ 85000 + US$ 65000 financiado por Hipoteca Privada

SOLO 1150 US$ x m2 !!!!

Departamento de 132 m² ubicado estratégicamente en Villa Crespo, sobre calle Darwin, en edificio de 8 pisos construido en 1968. Unidad de 4 ambientes con excelente distribución y potencial de renovación, ideal para quienes buscan un inmueble con proyección.

La propiedad presenta una superficie total de 132 m², compuesta por 117 m² cubiertos y 15 m² semicubiertos. Distribuido en 5 ambientes con acceso principal y de servicio, ofrece doble circulación y óptima luminosidad por su orientación Este y ubicación en segundo piso al frente.

Cuenta con living-comedor amplio, 3 dormitorios con placard, cocina con comedor diario, baño completo, toilette con ducha, balcón corrido, lavadero y habitación de servicio con baño propio. Estado general regular, requiere actualización y refacción.

Ubicación privilegiada en Villa Crespo, zona dinámica próxima a Avenida Corrientes y Juan B. Justo. Excelente conectividad con múltiples medios de transporte. Cercano a puntos de interés como Movistar Arena y Cancha de Atlanta.

Oportunidad de inversión con potencial de revalorización mediante renovación integral.

================================================================================
ID: 607641
Título: VENTA DEPTO BELGRANO 3 AMB BALCON CORRIDO NUEVO
Barrio: Belgrano Chico
Estado actual: Sin_clasificar
Descripción:
DEPARTAMENTO DE 3 AMBIENTES EN VENTA EN BELGRANO CHICO, ZONA DE MAXIMA DEMANDA, 61 M² 2

TODO LO QUE BUSCAS Y NO ENCONTRAS EN UNA SOLA PROPUESTA:  UNIDAD DE 3 AMB. A ESTRENAR (HECHA A NUEVO COMPLETA),  2 DORMITORIOS.  BALCON CORRIDO. LUZ, SOL Y VENTILACION CRUZADA EN TODOS LOS AMBIENTES, PLACARDS GRANDES DE PISO A TECHO, ESPACIO PARA LAVARROPAS, COCINA CON ESPACIO PARA DESAYUNADOR,  BUENAS EXPENSAS Y A PASOS DE AV DEL LIBERTADOR, BARRANCAS DE BELGANO Y PARQUE REGATAS PALERMO. ZONA DE MAXIMO INTERES EN CABA.

Un refugio de luz y diseño se despliega en el corazón de Belgrano Chico, donde cada rincón cuenta una historia de confort y estilo de vida urbano. Este departamento de 61 m² es más que un espacio, es donde tus sueños encuentran su hogar.

UBICACIÓN PRIVILEGIADA

Situado en la intersección de Pampa y Migueletes,  en un sexto piso de un edificio de ocho plantas, este departamento se eleva como un mirador estratégico. A apenas una cuadra de Avenida del Libertador y La Pampa, goza de una ubicación envidiable a pasos del Parque Regatas y las Barrancas de Belgrano. La zona concentra parques, comercios y transporte, conformando el entorno ideal para quienes buscan vivir en el corazón porteño sin renunciar a la tranquilidad.

ESPACIOS LUMINOSOS Y FUNCIONALES
Sus ventanales generosos invitan la luz natural a cada rincón, transformando los ambientes en espacios luminosos y acogedores. El living comedor se expande hacia un balcón corrido de 7 m² que recibe sol de tarde y crea una transición perfecta entre el interior y el exterior. Imaginate disfrutar del atardecer porteño con un café en el amplio balcón, contemplando la vida de la ciudad.

COCINA EQUIPADA CON ESTILO
La cocina office, diseñada con elegancia funcional, presenta mesada de granito, alacenas completas y espacios estratégicos para electrodomésticos. Artefacto de cocina nueva con 4 hornallas. Cuenta con espacio para heladera alta y conexión de lavarropas, espacio para microondas, conformando un rincón pensado para quienes disfrutan preparar sus comidas con estilo, con espacio para mesa o barra. Linda ventana al exterior.

DORMITORIOS CONFORTABLES
El dormitorio principal ofrece un placard de piso a techo del ancho total de pared y salida directa al balcón corrido, garantizando privacidad y luminosidad.
El segundo dormitorio completa la distribución, brindando flexibilidad para adaptarse a tus necesidades.

PASILLO DE CIRCULACION CON PLACARD DE GUARDADO DE PISO A TECHO.

BAÑO COMPLETO
Baño equipado con ducha, vanitory, espejo lumínico LED,  pisos de porcelanato terminación madera  y ventana al exterior que asegura ventilación natural y claridad.

RENOVACIÓN INTEGRAL Y SERVICIOS ACTUALIZADOS

Departamento completamente hecho a nuevo en todos sus ambientes, que combina la solidez de lo clásico con las comodidades contemporáneas. Instalaciones eléctricas actualizadas, baño y cocina a estrenar, pisos nuevos, calefón y artefacto de cocina a estrenar a gas.


EL EDIFICIO
El edificio cuenta con encargado y excelente mantenimiento, reflejando el cuidado constante de la propiedad.
Buenas expensas.
Terraza de tendido.

CARACTERÍSTICAS DESTACADAS

• Superficie total: 61 m² (54 m² cubiertos, 7 m² semicubiertos)
• 2 dormitorios
• 1 baño completo
• Balcón corrido
• Cocina equipada con mesada de granito
• Aire acondicionado en LC
• Placard de piso a techo en dormitorio principal
• Piso 6 de edificio de 8 plantas
• Estado general: excelente
• A estrenar

SERVICIOS E INFRAESTRUCTURA

• Electricidad con instalación renovada
• Calefón y cocina a gas
• Agua incluida en expensas
• Edificio con encargado y excelente mantenimiento
• Ubicación privilegiada a pasos de parques, comercios y transporte


-----VENTA DIRECTA- NO ES APTO CREDITO---------------

Expensas: $240.000 (incluye agua)


Un espacio que no es solo un departamento, sino el escenario de tu próximo capítulo de vida en Belgrano. Contactanos para visitarlo y comenzar a armar tu próximo hogar.

================================================================================
ID: 606775
Título: VENTA PASO AL 100 CABA 3 AMB LUMINOSO BALCON
Barrio: Balvanera
Estado actual: Sin_clasificar
Descripción:
DEPARTAMENTO 3 AMBIENTES EN VENTA BALVANERA BUENOS AIRES PARA REMODELAR

Excelente oportunidad de inversión en una de las zonas con mayor demanda de la Ciudad de Buenos Aires. Este departamento ubicado sobre la calle Paso representa una alternativa sólida para quienes buscan invertir, reciclar o desarrollar un proyecto de renovación integral.

CARACTERÍSTICAS DE LA PROPIEDAD

Superficie y distribución

• 76 m² totales compuestos por 72 m² cubiertos y 4 m² semicubiertos
• Ubicado en el 5.º piso de un edificio de 7 pisos
• Distribución funcional y bien aprovechada
• Construcción original de 1960 con potencial de modernización

Ambientes

• Amplio living-comedor
• Dos dormitorios
• Dos baños completos
• Cocina independiente
• Lavadero separado
• Dependencia de servicio

Características constructivas

• Todos los ambientes principales orientados al frente
• Excelente luminosidad y ventilación natural
• Pisos de parquet originales que pueden recuperarse
• Balcón corrido al frente

POTENCIAL DE REVALORIZACIÓN

El departamento se encuentra en estado general bueno, aunque la cocina y los baños requieren actualización. Esta condición lo convierte en una excelente alternativa para inversores, desarrolladores o compradores que deseen personalizar su vivienda y capitalizar la diferencia de valor que ofrece una reforma integral. Su metraje, distribución y ubicación permiten proyectar una importante revalorización una vez modernizado.

UBICACIÓN ESTRATÉGICA

Situado en el corazón de Balvanera sobre la calle Paso, cuenta con excelente conectividad gracias a la cercanía de numerosas líneas de colectivo, estaciones de subte y tren. Se encuentra rodeado de comercios, bancos, centros de salud, universidades y una amplia oferta de servicios, lo que garantiza una demanda sostenida tanto para vivienda como para inversión.

Por su ubicación, superficie, distribución y potencial de mejora, representa una inversión sólida con posibilidades de obtener una importante valorización. Contactanos para coordinar una visita y descubrir todo el potencial de esta propiedad.

Las medidas expresadas son orientativas y las imágenes ilustrativas.

================================================================================
ID: 573714
Título: VENTA DPTO DOS AMBIENTES PALERMO BOTANICO
Barrio: Palermo
Estado actual: Sin_clasificar
Descripción:
DEPARTAMENTO 2 AMBIENTES PALERMO CAPITAL FEDERAL RAÚL SCALABRINI ORTIZ - APTO CRÉDITO

El equipo de RE/MAX presenta a la venta el siguiente departamento de dos ambientes con cocina independiente y lavadero, en ubicación privilegiada, abriéndose paso en el corazón de Palermo.
Este departamento de 41 m² invita a reimaginar el concepto de hogar compacto con diseño estratégico y mucho potencial de refacción.

CARACTERÍSTICAS PRINCIPALES
• Ubicación estratégica sobre Raúl Scalabrini Ortiz, entre Beruti y Juncal, zona de alta valorización inmobiliaria y gran impacto turístico, cultural y gastronómico.
• Ubicado en el piso 3° de un edificio de 9 pisos con cocheras en subsuelo.
• Edificado en 1968, con sólida construcción y potencial de renovación integral

DISTRIBUCIÓN INTELIGENTE
• Dormitorio con placard para máximo aprovechamiento del espacio
• Cocina independiente con sector de lavadero
• Baño completo

POTENCIAL DE INVERSIÓN
• Perfil apto para crédito hipotecario
• Zona con alta demanda de alquileres temporarios
• Oportunidad de revalorización mediante reforma

Una propiedad que combina ubicación, potencial y precio para inversores audaces que buscan transformar un espacio en su próximo proyecto de vida.
No dejes pasar esta oportunidad.
Contactanos para conocer más detalles y concretar tu visita.

Si tenés que vender tu propiedad no dejes de contactarnos para poder ayudarte y asesorarte.
¡MUDATE A LA VIDA QUE QUERES!

In [ ]:
patron_obra_nuevo = (
    r"para remodelar|"
    r"requiere actualizaci[oó]n|"
    r"requiere refacci[oó]n|"
    r"potencial de refacci[oó]n|"
    r"potencial de renovaci[oó]n|"
    r"potencial de modernizaci[oó]n|"
    r"potencial para reciclar|"
    r"potencial para refaccionar|"
    r"potencial para modernizar"
)

patron_reciclada_nuevo = (
    r"completamente remodelad[oa]|"
    r"completamente hecho a nuevo|"
    r"hech[oa] a nuevo completa"
)

print(
    "Posibles Necesita_obra:",
    (
        (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
        texto_propiedad.str.contains(
            patron_obra_nuevo, case=False, na=False, regex=True
        )
    ).sum()
)

print(
    "Posibles Reciclada_refaccionada:",
    (
        (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
        texto_propiedad.str.contains(
            patron_reciclada_nuevo, case=False, na=False, regex=True
        )
    ).sum()
)

Posibles Necesita_obra: 46
Posibles Reciclada_refaccionada: 6

In [ ]:
mask_reciclada_nuevo = (
    (df_limpio["Estado_Propiedad"] == "Sin_clasificar") &
    texto_propiedad.str.contains(
        patron_reciclada_nuevo,
        case=False,
        na=False,
        regex=True
    )
)

for _, fila in df_limpio.loc[mask_reciclada_nuevo].iterrows():
    print("\n" + "=" * 80)
    print("ID:", fila["ID"])
    print("Título:", fila["Titulo"])
    print("Barrio:", fila["Barrio"])
    print("Descripción:")
    print(fila["Descripcion"])

================================================================================
ID: 629386
Título: Dúplex en Caballito con balcón cerrado y cochera
Barrio: Caballito
Descripción:
Imperdible dúplex de 127 m² en una de las mejores zonas de Caballito — Excelente distribución, espacios amplios y cochera en estado impecable!

Se trata de un luminoso dúplex, ideal para quienes buscan comodidad, estilo y una ubicación privilegiada dentro de la ciudad. La propiedad ofrece una distribución súper funcional que separa perfectamente las áreas sociales de las privadas, brindando confort y privacidad.

-Planta alta, por el cual se ingresa: espacio social amplio

Al ingresar, nos recibe un gran living comedor, cómodo y versátil, con salida directa al balcón.
La cocina fue completamente remodelada, ofreciendo excelente espacio de guardado y la posibilidad de incorporar una mesa para uso diario, ideal para el día a día.

El balcón techado con cerramiento corredizo funciona como un ambiente extra: un espacio perfecto para reuniones sociales, creación de un home office o para adaptarlo a la necesidad de cada uno. Además, cuenta con parrilla propia, actualmente tapada, pero que puede utilizarse sin ningún inconveniente.

Completa este nivel un toilette de recepción, pensado para darle total comodidad a la zona social.

-Planta baja: sector privado súper cómodo

En la planta inferior se encuentra la habitación principal en suite, con vestidor y excelente capacidad de guardado.
Se suman dos dormitorios adicionales, ambos de buen tamaño y con ventilación natural, y un baño completo para uso de la planta.

Aspectos a tener en cuenta:

-Cochera incluida

-Distribución ideal

-Ambientes amplios y bien aprovechados

-Edificio tranquilo y de calidad


Situado en una de las zonas más buscadas de Caballito, rodeado de excelente oferta gastronómica, cafés, comercios, espacios verdes y múltiples opciones de transporte.

Un barrio con vida, servicios y fácil acceso a toda la ciudad.


¡No dudes en contactarme!

================================================================================
ID: 627609
Título: Venta 4 ambientes con dependecia Caballito
Barrio: Caballito
Descripción:
4 AMBIENTES CON DEPENDENCIA – SEMIPISO AL FRENTE SOBRE LA CALLE ESPINOSA

Hermoso semipiso de 4 ambientes con dependencia, al frente

Totalmente remodelado hace 3 años, con excelentes detalles de terminación

La propiedad cuenta con entrada principal y entrada de servicio.

Al ingresar, encontramos un amplio  living comedor al frente, muy luminoso, con pisos de parquet pulidos y plastificados, detalles de iluminación en cielorraso y un gran ventanal con salida a balcón corrido.

Cuenta además con toilette de recepción.

La cocina comedor es amplia y funcional, equipada con cocina industrial a gas, alacenas y bajo mesadas, con espacio para  una mesa para  cuatro personas
Posee excelente luz natural gracias a su ventana al aire y luz del edificio.

La propiedad dispone de dependencia de servicio y un práctico lavadero independiente, equipado con conexión para lavarropas, pileta de lavado, tender, termotanque a gas, placard de guardado y un amplio ventanal al aire y luz.

 Pasillo distribuidor conduce al sector privado de la propiedad.

El dormitorio principal es amplio y muy luminoso.
El segundo dormitorio se encuentra al frente y cuenta con amplio placard moderno, con puertas corredizas e interiores completos.
El tercer dormitorio también se destaca por su luminosidad y cuenta con placard.

La propiedad posee un baño completo,  equipado con sanitarios de primera calidad, mampara y vanitory.


Una excelente propiedad para quienes buscan amplitud, luminosidad, buena distribución y el confort de una vivienda completamente remodelada, en una ubicación privilegiada.

================================================================================
ID: 611305
Título: Departamento ideal para empezar  a ser propietario
Barrio: Parque Chacabuco
Descripción:
Departamento de 3 ambientes de 52,99 m², completamente remodelado a nuevo, con excelentes terminaciones y listo para habitar. La unidad ofrece ambientes cómodos, funcionales y una renovación integral que aporta confort y practicidad.

Ubicado en un primer piso por escalera, dentro de un monoblock de construcción antigua, su principal diferencial radica en el impecable estado de la propiedad. Si bien el edificio y el entorno no se destacan por su estética, el departamento representa una excelente oportunidad para quienes priorizan una vivienda renovada, de bajo mantenimiento y con una muy buena relación entre calidad y precio.

El departamento posee tanto gas como electricidad, el agua caliente es suministrada por un termotanque a gas, mientras que en la cocina todo funciona con electricidad, pudiendo el nuevo comprador convertirla a gas si deseara,  ya que el éste llega hasta la cocina, solo sería necesario realizar la conexión.

Posee una cochera cubierta que es considerada como un espacio común , y que en si existen lugares disponibles las unidades funcionales cuentan con una de ellas y también con un lugar de guardado para un segundo auto en una cochera descubierta, dentro del mismo predio en donde se encuentra el edificio, aspectos éstos que suman un plus muy importante, sobre todo en lo que se refiere a la posibilidad de no tener que dejar el auto en la calle o alquilar una cochera .

En cuanto a las expensas el monto es de $116.00, más $20.000, en caso de utilizar la cochera.

Cabe destacar que el departamento tiene dos dormitorios pero en la actualidad uno de ellos se encuentra dividido por un  durlock  lo que genera un tercer dormitorio, lo ofrece un espacio más, que puede ser utilizado o bien volverlo al estado original y convertirlo en 2 dormitorios.

================================================================================
ID: 610234
Título: DEPARTAMENTO PISO  4 AMB VENTA VILLA DEVOTO
Barrio: Villa Devoto
Descripción:
Piso de Categoría en Villa Devoto | 4 Ambientes | Balcones | Baulera

Exclusividad, luz natural, amplitud y privacidad en una de las zonas más valoradas de Villa Devoto.

Hay propiedades que ofrecen metros cuadrados. Otras ofrecen ubicación. Y algunas, muy pocas, ofrecen una forma diferente de vivir.

Sobre una de las calles residenciales más lindas de Villa Devoto, frente al Devoto School y a pocos minutos de Plaza Arenales, se encuentra este exclusivo piso de 4 ambientes completamente remodelado, donde la amplitud y la luz natural son protagonistas.

Luz natural durante todo el día, ventilación cruzada y privacidad que solo ofrece un edificio con un departamento por piso.

Ubicado en un edificio tipo PH de solo tres departamentos (uno por piso), esta propiedad brinda la tranquilidad y el confort de una casa con las ventajas de un departamento.

La combinación de un piso único, un edificio de tan solo tres unidades y una remodelación integral realizada con materiales de primera calidad convierte a esta propiedad en una oportunidad poco frecuente dentro del mercado de Villa Devoto.

Distribución y ambientes

Se accede a la propiedad por cómodas escaleras de tramos cortos y descansos amplios. Cuenta con entrada principal y entrada de servicio.

El living-comedor, amplio y muy luminoso, se integra con un balcón corrido al frente desde donde se disfruta una agradable vista abierta y al jardín del edificio.

La cocina comedor, completamente renovada, ofrece mobiliario a medida, excelente capacidad de guardado, gran comodidad para el uso diario y salida al balcón del contrafrente.

Dormitorio principal en suite, con vestidor, placard de pared a pared, salida al balcón y excelente vista abierta.

Segundo dormitorio con salida al balcón del contrafrente.

Tercer dormitorio / escritorio, ideal como home office o cuarto adicional.

Segundo baño completo.

Lavadero independiente con cerramiento de ladrillos de vidrio, que aporta aún más luminosidad.


Superficie total

119,30 m²

Cubiertos

101,02 m²

Balcones

18,28 m²

Baulera individual

2,59 m²

Detalles y confort

Remodelación integral con materiales de alta gama.

Tres equipos de aire acondicionado.

Persianas eléctricas.

Excelente capacidad de guardado.

Ambientes amplios, luminosos y muy ventilados.

Baulera y espacio guarda coche

La propiedad dispone además de una baulera individual y un espacio guarda coche ubicado en el subsuelo del edificio, con acceso mediante rampa y portón automático.

El espacio guarda coche no constituye una unidad funcional independiente.

Edificio

Tipo PH.

Solo 3 unidades funcionales.

Un departamento por piso.

Antigüedad aproximada: 50 años.

Expensas aproximadas: $265.000

Ubicación privilegiada

Pedro Morán, entre
Segurola y Marcos Paz

Una ubicación estratégica dentro del sector residencial de Villa Devoto, rodeada de espacios verdes, colegios de prestigio, comercios, propuestas gastronómicas y excelente conectividad.

Lo más valioso de esta propiedad

Piso único

Edificio de solo tres unidades

Remodelación integral de categoría

119,30 m² totales

Balcones al frente y contrafrente

Baulera

Espacio guardacoche

Frente al Devoto School

A minutos de Plaza Arenales

Si buscás amplitud, privacidad, calidad constructiva y una ubicación que conserve el espíritu residencial de Devoto, esta propiedad merece estar entre tus primeras opciones.

Contactanos para coordinar una visita y conocerla personalmente.

Aclaración: Las medidas y datos son aproximados y deberán verificarse con la documentación correspondiente.



================================================================================
ID: 607641
Título: VENTA DEPTO BELGRANO 3 AMB BALCON CORRIDO NUEVO
Barrio: Belgrano Chico
Descripción:
DEPARTAMENTO DE 3 AMBIENTES EN VENTA EN BELGRANO CHICO, ZONA DE MAXIMA DEMANDA, 61 M² 2

TODO LO QUE BUSCAS Y NO ENCONTRAS EN UNA SOLA PROPUESTA:  UNIDAD DE 3 AMB. A ESTRENAR (HECHA A NUEVO COMPLETA),  2 DORMITORIOS.  BALCON CORRIDO. LUZ, SOL Y VENTILACION CRUZADA EN TODOS LOS AMBIENTES, PLACARDS GRANDES DE PISO A TECHO, ESPACIO PARA LAVARROPAS, COCINA CON ESPACIO PARA DESAYUNADOR,  BUENAS EXPENSAS Y A PASOS DE AV DEL LIBERTADOR, BARRANCAS DE BELGANO Y PARQUE REGATAS PALERMO. ZONA DE MAXIMO INTERES EN CABA.

Un refugio de luz y diseño se despliega en el corazón de Belgrano Chico, donde cada rincón cuenta una historia de confort y estilo de vida urbano. Este departamento de 61 m² es más que un espacio, es donde tus sueños encuentran su hogar.

UBICACIÓN PRIVILEGIADA

Situado en la intersección de Pampa y Migueletes,  en un sexto piso de un edificio de ocho plantas, este departamento se eleva como un mirador estratégico. A apenas una cuadra de Avenida del Libertador y La Pampa, goza de una ubicación envidiable a pasos del Parque Regatas y las Barrancas de Belgrano. La zona concentra parques, comercios y transporte, conformando el entorno ideal para quienes buscan vivir en el corazón porteño sin renunciar a la tranquilidad.

ESPACIOS LUMINOSOS Y FUNCIONALES
Sus ventanales generosos invitan la luz natural a cada rincón, transformando los ambientes en espacios luminosos y acogedores. El living comedor se expande hacia un balcón corrido de 7 m² que recibe sol de tarde y crea una transición perfecta entre el interior y el exterior. Imaginate disfrutar del atardecer porteño con un café en el amplio balcón, contemplando la vida de la ciudad.

COCINA EQUIPADA CON ESTILO
La cocina office, diseñada con elegancia funcional, presenta mesada de granito, alacenas completas y espacios estratégicos para electrodomésticos. Artefacto de cocina nueva con 4 hornallas. Cuenta con espacio para heladera alta y conexión de lavarropas, espacio para microondas, conformando un rincón pensado para quienes disfrutan preparar sus comidas con estilo, con espacio para mesa o barra. Linda ventana al exterior.

DORMITORIOS CONFORTABLES
El dormitorio principal ofrece un placard de piso a techo del ancho total de pared y salida directa al balcón corrido, garantizando privacidad y luminosidad.
El segundo dormitorio completa la distribución, brindando flexibilidad para adaptarse a tus necesidades.

PASILLO DE CIRCULACION CON PLACARD DE GUARDADO DE PISO A TECHO.

BAÑO COMPLETO
Baño equipado con ducha, vanitory, espejo lumínico LED,  pisos de porcelanato terminación madera  y ventana al exterior que asegura ventilación natural y claridad.

RENOVACIÓN INTEGRAL Y SERVICIOS ACTUALIZADOS

Departamento completamente hecho a nuevo en todos sus ambientes, que combina la solidez de lo clásico con las comodidades contemporáneas. Instalaciones eléctricas actualizadas, baño y cocina a estrenar, pisos nuevos, calefón y artefacto de cocina a estrenar a gas.


EL EDIFICIO
El edificio cuenta con encargado y excelente mantenimiento, reflejando el cuidado constante de la propiedad.
Buenas expensas.
Terraza de tendido.

CARACTERÍSTICAS DESTACADAS

• Superficie total: 61 m² (54 m² cubiertos, 7 m² semicubiertos)
• 2 dormitorios
• 1 baño completo
• Balcón corrido
• Cocina equipada con mesada de granito
• Aire acondicionado en LC
• Placard de piso a techo en dormitorio principal
• Piso 6 de edificio de 8 plantas
• Estado general: excelente
• A estrenar

SERVICIOS E INFRAESTRUCTURA

• Electricidad con instalación renovada
• Calefón y cocina a gas
• Agua incluida en expensas
• Edificio con encargado y excelente mantenimiento
• Ubicación privilegiada a pasos de parques, comercios y transporte


-----VENTA DIRECTA- NO ES APTO CREDITO---------------

Expensas: $240.000 (incluye agua)


Un espacio que no es solo un departamento, sino el escenario de tu próximo capítulo de vida en Belgrano. Contactanos para visitarlo y comenzar a armar tu próximo hogar.

================================================================================
ID: 557268
Título: VENTA DEPARTAMENTO 2 AMBIENTES RECOLETA 2 BALCONES
Barrio: Recoleta
Descripción:
¡Excelente 2 Ambientes en Venta en la Mejor Zona de Recoleta!

Descubrí la combinación perfecta de tranquilidad y ubicación en este excepcional departamento de 2 ambientes, contrafrente con vista abierta, situado en la codiciada calle Marcelo T. de Alvear al 2400, en la Ciudad Autónoma de Buenos Aires.

Este luminoso departamento se encuentra en un edificio muy tranquilo, ideal para quienes buscan serenidad en el corazón de la ciudad. Ha sido cuidadosamente actualizado, destacando una cocina completamente remodelada con un diseño moderno y funcional.

Disfrutá de la comodidad de un lavadero independiente con conexión lista para tu lavarropas, y la eficiencia de un termotanque nuevo para agua caliente sin preocupaciones.

El confort está garantizado todo el año gracias a la calefacción por losa radiante.

La propiedad cuenta con un baño completo y dos encantadores balcones que aportan luz y aire fresco: uno con acceso directo desde el amplio living comedor, perfecto para disfrutar de tus mañanas o tardes, y otro con salida desde la habitación, brindando un espacio privado y acogedor.

Ubicado en una de las zonas más prestigiosas de la ciudad, tendrás a tu alcance una variada oferta de servicios, gastronomía, parques y excelente conectividad.

¡Una oportunidad imperdible para vivir o invertir en Recoleta! Coordiná tu visita.


- Los metros aquí publicados son aproximados. Los reales surgen de la escritura. Esta publicidad respeta lo establecido en el art. 4 y 8 de la ley 24.240

- En cumplimiento de las leyes provinciales vigentes que regulan el corretaje inmobiliario, Ley Nacional 25.028, Ley 22.802 de Lealtad Comercial, Ley 24.240 de Defensa al Consumidor, las normas del Código Civil y Comercial de la Nación y Constitucionales, los agentes NO ejercen el corretaje inmobiliario. Todas las operaciones inmobiliarias son objeto de intermediación y conclusión por parte de los martilleros y corredores colegiados, cuyos datos se exhiben debajo del nombre de la inmobiliaria.

In [ ]:
# Últimos ajustes de Estado_Propiedad validados manualmente

# Propiedades remodeladas/refaccionadas
df_limpio.loc[
    df_limpio["ID"].isin([629386, 627609, 611305, 610234, 607641, 557268]),
    "Estado_Propiedad"
] = "Reciclada_refaccionada"

# Propiedades que requieren obra
df_limpio.loc[
    df_limpio["ID"].isin([607842, 606775, 573714]),
    "Estado_Propiedad"
] = "Necesita_obra"

df_limpio["Estado_Propiedad"].value_counts()

Estado_Propiedad
Sin_clasificar            6170
Buen_estado               2000
Reciclada_refaccionada    1085
Necesita_obra              416
Name: count, dtype: int64

In [ ]:
print("=== CONTROL FINAL ===")

print("\nDimensiones:")
print(df_limpio.shape)

print("\nDuplicados exactos:")
print(df_limpio.duplicated().sum())

print("\nIDs duplicados:")
print(df_limpio["ID"].duplicated().sum())

print("\nValores faltantes:")
print(
    df_limpio.isna().sum()
    .loc[lambda x: x > 0]
    .sort_values(ascending=False)
)

print("\nTipo de propiedad:")
print(df_limpio["Tipo_Propiedad"].value_counts())

print("\nEstado de propiedad:")
print(df_limpio["Estado_Propiedad"].value_counts())

print("\nPrecio/m²:")
print(df_limpio["Precio_m2_Total"].describe().round(2))

=== CONTROL FINAL ===

Dimensiones:
(9671, 44)

Duplicados exactos:
0

IDs duplicados:
0

Valores faltantes:
Fecha_Publicacion         9671
Amenities                 1751
Expensas                  1006
Antiguedad                  38
Descripcion                 37
Apto_Credito                37
Longitud                     5
Latitud                      5
Moneda_Expensas              1
Superficie_Cubierta_m2       1
Precio_m2_Cubierto           1
dtype: int64

Tipo de propiedad:
Tipo_Propiedad
departamento_estandar        7449
departamento_monoambiente    1024
departamento_semipiso         518
departamento_piso             286
departamento_duplex           277
departamento_loft              54
departamento_triplex           38
departamento_penthouse         25
Name: count, dtype: int64

Estado de propiedad:
Estado_Propiedad
Sin_clasificar            6170
Buen_estado               2000
Reciclada_refaccionada    1085
Necesita_obra              416
Name: count, dtype: int64

Precio/m²:
count     9671.00
mean      2182.48
std        820.03
min        292.93
25%       1640.78
50%       2071.43
75%       2567.72
max      15403.42
Name: Precio_m2_Total, dtype: float64

In [ ]:
nombre_archivo = "remax_departamentos_caba_limpio.csv"

df_limpio.to_csv(nombre_archivo, index=False)

print("Dataset guardado correctamente")
print("Archivo:", nombre_archivo)
print("Dimensiones:", df_limpio.shape)

Dataset guardado correctamente
Archivo: remax_departamentos_caba_limpio.csv
Dimensiones: (9671, 44)

Resumen del notebook de limpieza

El objetivo de este notebook fue partir de la base original obtenida mediante scraping y construir una base limpia y consistente de departamentos usados en venta en CABA, orientada al posterior análisis de valuación, detección de propiedades subvaluadas y oportunidades de flipping.

La base original contenía 16.993 registros y 29 variables. El criterio de trabajo fue principalmente conservador: no eliminar observaciones simplemente por tener valores extremos o datos poco frecuentes, sino revisar si existía una razón concreta para considerar que una propiedad estaba fuera del universo de análisis o tenía información incorrecta.

1. Definición del universo de análisis

Primero se filtraron únicamente las categorías correspondientes a departamentos, excluyendo casas, PH originalmente clasificados como tales, terrenos, locales, oficinas, cocheras y otras tipologías.

También se verificó que las propiedades fueran operaciones de venta y que los precios estuvieran expresados en USD.

Como el objetivo es analizar departamentos usados, se buscaron y eliminaron publicaciones correspondientes a obra nueva, pozo, preventa, emprendimientos, desarrollos y propiedades a estrenar. Para esto no se utilizó únicamente la variable Antiguedad, ya que contenía valores negativos y ceros que podían tener distintas interpretaciones. Se combinaron esos datos con información extraída del título y la descripción.

2. Control de calidad de las variables

Se revisaron los valores faltantes, tipos de datos, duplicados y valores potencialmente inconsistentes.

Los duplicados no se eliminaron automáticamente. Por ejemplo, se encontraron publicaciones que compartían el mismo Link, pero correspondían a unidades diferentes dentro de un mismo desarrollo. Por eso se utilizaron principalmente ID e ID_Entidad para identificar las propiedades.

También se controlaron:

precios iguales o menores a cero;
superficies totales y cubiertas;
superficies cubiertas mayores a la superficie total;
cantidad de ambientes, dormitorios y baños;
antigüedad;
precio por metro cuadrado;
expensas y su moneda;
coordenadas geográficas;
barrios y ubicaciones faltantes.

Cuando se detectaron errores claros, se corrigieron sin eliminar innecesariamente la propiedad. Por ejemplo, una superficie cubierta igual a cero se transformó en faltante, un monoambiente con Ambientes = 0 se corrigió a 1 y algunas expensas o monedas evidentemente mal cargadas fueron corregidas o convertidas en faltantes.

3. Duplicados y propiedades no comparables

Se buscaron duplicados utilizando distintas combinaciones de variables. Se eliminaron únicamente aquellos registros que representaban realmente la misma propiedad repetida.

También se hizo una revisión adicional de propiedades que, aunque estaban clasificadas como departamentos en la fuente, podían corresponder a PH u otras situaciones especiales. Esto permitió eliminar 60 propiedades consideradas PH, manteniendo algunos casos donde el texto aclaraba que seguían siendo departamentos aunque tuvieran características similares a un PH.

Durante la revisión de valores extremos también se detectaron casos que no eran comparables con una compraventa residencial convencional. Por ejemplo, se eliminó una nuda propiedad con usufructo vitalicio, cuyo precio reducido respondía a una modalidad jurídica diferente, y una propiedad originalmente destinada a oficina profesional, aunque permitiera su transformación posterior en vivienda.

En cambio, no se eliminaron outliers solamente por presentar un precio/m² muy alto o muy bajo. Se revisaron los casos extremos y se comprobó que muchos podían explicarse por el barrio, el estado de conservación, grandes superficies descubiertas, cocheras o características premium.

4. Uso de título y descripción

Una parte importante del trabajo fue aprovechar las variables textuales Titulo y Descripcion para obtener información que no estaba estructurada originalmente.

Se creó la variable Estado_Propiedad, clasificando los departamentos en:

Necesita_obra
Buen_estado
Reciclada_refaccionada
Sin_clasificar

Para hacerlo se utilizaron expresiones presentes en los avisos, como “a refaccionar”, “a reciclar”, “requiere actualización”, “buen estado”, “excelente estado”, “reciclado”, “refaccionado” o “completamente remodelado”.

Se optó por mantener Sin_clasificar cuando el texto no daba evidencia suficiente, en lugar de asumir artificialmente el estado de la propiedad. Finalmente quedaron 416 departamentos que necesitan obra, 2.000 en buen estado, 1.085 reciclados/refaccionados y 6.170 sin clasificación.

Esta variable será especialmente importante para analizar la hipótesis relacionada con el potencial de flipping. Como primer control descriptivo, ya se observó que los departamentos que necesitan obra presentan un precio/m² considerablemente menor que aquellos en buen estado o reciclados, aunque esta relación deberá analizarse posteriormente controlando otras características.

5. Creación de variables de amenities

La variable Amenities contenía múltiples características separadas dentro de un mismo campo. En lugar de generar una variable para cada uno de los aproximadamente 95 valores encontrados, se seleccionaron aquellos con mayor utilidad para el análisis inmobiliario.

Se crearon variables binarias como:

Tiene_Balcon, Tiene_Ascensor, Tiene_Terraza, Tiene_Parrilla, Tiene_SUM, Tiene_Seguridad, Tiene_Aire_Acondicionado, Tiene_Baulera, Tiene_Patio, Tiene_Laundry, Tiene_Gimnasio, Tiene_Solarium y Tiene_Pileta.

También se creó Tiene_Cochera utilizando título y descripción. En este caso fue necesario distinguir entre una cochera realmente incluida en la venta y frases como “cochera opcional”, “posibilidad de comprar cochera” o “cochera no incluida”.

6. Coordenadas y ubicación

Se revisaron las coordenadas geográficas para detectar propiedades ubicadas aparentemente fuera de CABA. Se encontraron cinco casos donde la dirección y el barrio correspondían a CABA, pero las coordenadas eran claramente incorrectas.

Como la propiedad en sí seguía siendo válida, no se eliminaron esos registros: solamente se reemplazaron las coordenadas erróneas por valores faltantes.

Además, se decidió conservar el Barrio informado por la fuente, incluso cuando utiliza zonas comerciales como Palermo Chico o Barrio Norte. Más adelante se podrá realizar un cruce espacial utilizando latitud y longitud para obtener una clasificación oficial de barrios/comunas.

Resultado final

El dataset original tenía:

16.993 filas × 29 variables

Después del filtrado, limpieza, controles de calidad, eliminación de propiedades fuera del alcance y creación de nuevas variables, el archivo final quedó en:

9.671 filas × 44 variables

No quedaron duplicados exactos ni IDs duplicados.

Los faltantes que permanecen fueron conservados deliberadamente cuando no existía información suficiente para imputarlos. El principal caso es Fecha_Publicacion, que quedó completamente vacío debido a un problema en la extracción original y deberá revisarse en el proceso de scraping. También permanecen algunos faltantes en Amenities, Expensas, Antiguedad, Descripcion, Apto_Credito y unos pocos casos puntuales en coordenadas y superficie cubierta.

Finalmente, la base se exportó como:

remax_departamentos_caba_limpio.csv

En síntesis, el notebook transforma la base cruda del scraping en un dataset de departamentos usados en venta en CABA, depurado pero sin eliminar artificialmente la variabilidad real del mercado, y agrega variables útiles para estudiar valuación, subvaluación y potencial de flipping.